var searchData=
[
  ['dallavalledraglaw_38503',['DallavalleDragLaw',['../d4/d83/class_kratos_1_1_dallavalle_drag_law.html',1,'Kratos']]],
  ['damaddedmassconditionprocess_38504',['DamAddedMassConditionProcess',['../dc/dab/class_kratos_1_1_dam_added_mass_condition_process.html',1,'Kratos']]],
  ['damagedetectionresponse_38505',['DamageDetectionResponse',['../d2/d2f/classdamage__detection__response_1_1_damage_detection_response.html',1,'damage_detection_response']]],
  ['damagedplusdminusmasonry2dlaw_38506',['DamageDPlusDMinusMasonry2DLaw',['../d6/de5/class_kratos_1_1_damage_d_plus_d_minus_masonry2_d_law.html',1,'Kratos']]],
  ['damagedplusdminusmasonry3dlaw_38507',['DamageDPlusDMinusMasonry3DLaw',['../dc/d8b/class_kratos_1_1_damage_d_plus_d_minus_masonry3_d_law.html',1,'Kratos']]],
  ['damagemodel_38508',['DamageModel',['../da/db6/class_kratos_1_1_damage_model.html',1,'Kratos']]],
  ['damagemodel_3c_20linearelasticmodel_2c_20simojuyieldsurface_3c_20exponentialdamagehardeningrule_20_3e_20_3e_38509',['DamageModel&lt; LinearElasticModel, SimoJuYieldSurface&lt; ExponentialDamageHardeningRule &gt; &gt;',['../da/db6/class_kratos_1_1_damage_model.html',1,'Kratos']]],
  ['damagemodel_3c_20linearelasticmodel_2c_20simojuyieldsurface_3c_20modifiedexponentialdamagehardeningrule_20_3e_20_3e_38510',['DamageModel&lt; LinearElasticModel, SimoJuYieldSurface&lt; ModifiedExponentialDamageHardeningRule &gt; &gt;',['../da/db6/class_kratos_1_1_damage_model.html',1,'Kratos']]],
  ['damageparameters_38511',['DamageParameters',['../df/d71/struct_kratos_1_1_damage_d_plus_d_minus_masonry3_d_law_1_1_damage_parameters.html',1,'Kratos::DamageDPlusDMinusMasonry3DLaw::DamageParameters'],['../de/de9/struct_kratos_1_1_generic_small_strain_dplus_dminus_damage_1_1_damage_parameters.html',1,'Kratos::GenericSmallStrainDplusDminusDamage&lt; TConstLawIntegratorTensionType, TConstLawIntegratorCompressionType &gt;::DamageParameters']]],
  ['damanalysis_38512',['DamAnalysis',['../d5/d66/classdam__analysis_1_1_dam_analysis.html',1,'dam_analysis']]],
  ['damazenhaheatfluxprocess_38513',['DamAzenhaHeatFluxProcess',['../df/d85/class_kratos_1_1_dam_azenha_heat_flux_process.html',1,'Kratos']]],
  ['dambofangconditiontemperatureprocess_38514',['DamBofangConditionTemperatureProcess',['../d7/deb/class_kratos_1_1_dam_bofang_condition_temperature_process.html',1,'Kratos']]],
  ['dambreakbenchmark_38515',['DamBreakBenchmark',['../d7/d5a/classdam__break__benchmark_1_1_dam_break_benchmark.html',1,'dam_break_benchmark']]],
  ['dambreakmodeler_38516',['DamBreakModeler',['../d0/d15/classdam__break__modeler_1_1_dam_break_modeler.html',1,'dam_break_modeler']]],
  ['damchemomechanicalagingyoungprocess_38517',['DamChemoMechanicalAgingYoungProcess',['../db/dc9/class_kratos_1_1_dam_chemo_mechanical_aging_young_process.html',1,'Kratos']]],
  ['damconstructionutility_38518',['DamConstructionUtility',['../d1/dde/classdam__construction__utility_1_1_dam_construction_utility.html',1,'dam_construction_utility']]],
  ['dameigensolver_38519',['DamEigenSolver',['../da/d4a/classdam__eigen__solver_1_1_dam_eigen_solver.html',1,'dam_eigen_solver']]],
  ['damfixtemperatureconditionprocess_38520',['DamFixTemperatureConditionProcess',['../d4/d50/class_kratos_1_1_dam_fix_temperature_condition_process.html',1,'Kratos']]],
  ['damgroutingreferencetemperatureprocess_38521',['DamGroutingReferenceTemperatureProcess',['../d6/d6d/class_kratos_1_1_dam_grouting_reference_temperature_process.html',1,'Kratos']]],
  ['damhydroconditionloadprocess_38522',['DamHydroConditionLoadProcess',['../d1/d93/class_kratos_1_1_dam_hydro_condition_load_process.html',1,'Kratos']]],
  ['daminputtablenodalyoungmodulusprocess_38523',['DamInputTableNodalYoungModulusProcess',['../d4/d1b/class_kratos_1_1_dam_input_table_nodal_young_modulus_process.html',1,'Kratos']]],
  ['dammechanicalsolver_38524',['DamMechanicalSolver',['../d6/dcd/classdam__mechanical__solver_1_1_dam_mechanical_solver.html',1,'dam_mechanical_solver']]],
  ['damnodalreferencetemperatureprocess_38525',['DamNodalReferenceTemperatureProcess',['../dd/dc9/class_kratos_1_1_dam_nodal_reference_temperature_process.html',1,'Kratos']]],
  ['damnodalyoungmodulusprocess_38526',['DamNodalYoungModulusProcess',['../de/d36/class_kratos_1_1_dam_nodal_young_modulus_process.html',1,'Kratos']]],
  ['damnoorzaiheatfluxprocess_38527',['DamNoorzaiHeatFluxProcess',['../df/d74/class_kratos_1_1_dam_noorzai_heat_flux_process.html',1,'Kratos']]],
  ['dampingfunction_38528',['DampingFunction',['../de/d7b/class_kratos_1_1_damping_function.html',1,'Kratos']]],
  ['dampingutilities_38529',['DampingUtilities',['../d1/d07/class_kratos_1_1_damping_utilities.html',1,'Kratos']]],
  ['dampscheme_38530',['DamPScheme',['../d0/dc0/class_kratos_1_1_dam_p_scheme.html',1,'Kratos']]],
  ['damrandomfieldsvariableprocess_38531',['DamRandomFieldsVariableProcess',['../dc/d75/class_kratos_1_1_dam_random_fields_variable_process.html',1,'Kratos']]],
  ['damreservoirconstanttemperatureprocess_38532',['DamReservoirConstantTemperatureProcess',['../d1/d4e/class_kratos_1_1_dam_reservoir_constant_temperature_process.html',1,'Kratos']]],
  ['damreservoirmonitoringtemperatureprocess_38533',['DamReservoirMonitoringTemperatureProcess',['../df/dc3/class_kratos_1_1_dam_reservoir_monitoring_temperature_process.html',1,'Kratos']]],
  ['damselfweightsolver_38534',['DamSelfweightSolver',['../d4/dd6/classdam__selfweight__solver_1_1_dam_selfweight_solver.html',1,'dam_selfweight_solver']]],
  ['damtemperaturebydeviceprocess_38535',['DamTemperaturebyDeviceProcess',['../d0/d9e/class_kratos_1_1_dam_temperatureby_device_process.html',1,'Kratos']]],
  ['damthermomechanicsolver_38536',['DamThermoMechanicSolver',['../dc/d6b/classdam__thermo__mechanic__solver_1_1_dam_thermo_mechanic_solver.html',1,'dam_thermo_mechanic_solver']]],
  ['damtsolairheatfluxprocess_38537',['DamTSolAirHeatFluxProcess',['../d6/d11/class_kratos_1_1_dam_t_sol_air_heat_flux_process.html',1,'Kratos']]],
  ['damupliftcircularconditionloadprocess_38538',['DamUpliftCircularConditionLoadProcess',['../df/d42/class_kratos_1_1_dam_uplift_circular_condition_load_process.html',1,'Kratos']]],
  ['damupliftconditionloadprocess_38539',['DamUpliftConditionLoadProcess',['../da/d2a/class_kratos_1_1_dam_uplift_condition_load_process.html',1,'Kratos']]],
  ['damupmechanicalsolver_38540',['DamUPMechanicalSolver',['../df/d0e/classdam___u_p__mechanical__solver_1_1_dam_u_p_mechanical_solver.html',1,'dam_UP_mechanical_solver']]],
  ['damupscheme_38541',['DamUPScheme',['../d2/da8/class_kratos_1_1_dam_u_p_scheme.html',1,'Kratos']]],
  ['damupsolver_38542',['DamUPSolver',['../dc/d1e/classdam___p__solver_1_1_dam_u_p_solver.html',1,'dam_P_solver']]],
  ['damupthermomechanicsolver_38543',['DamUPThermoMechanicSolver',['../de/d77/classdam___u_p__thermo__mechanic__solver_1_1_dam_u_p_thermo_mechanic_solver.html',1,'dam_UP_thermo_mechanic_solver']]],
  ['damwestergaardconditionloadprocess_38544',['DamWestergaardConditionLoadProcess',['../db/d5f/class_kratos_1_1_dam_westergaard_condition_load_process.html',1,'Kratos']]],
  ['data_38545',['Data',['../d0/d88/class_kratos_1_1_literal_flat_expression_1_1_data.html',1,'Kratos::LiteralFlatExpression']]],
  ['databuffers_38546',['DataBuffers',['../d9/d9a/struct_kratos_1_1_python_1_1_co_sim_i_o___wrappers_1_1_data_buffers.html',1,'Kratos::Python::CoSimIO_Wrappers']]],
  ['datacommunicator_38547',['DataCommunicator',['../dc/d92/class_kratos_1_1_data_communicator.html',1,'Kratos']]],
  ['datadifferenceresidual_38548',['DataDifferenceResidual',['../d3/d14/classconvergence__accelerators_1_1convergence__accelerator__wrapper_1_1_data_difference_residual.html',1,'convergence_accelerators::convergence_accelerator_wrapper']]],
  ['dataitem_38549',['DataItem',['../d5/d8b/classcore_1_1xdmf_1_1_data_item.html',1,'core::xdmf']]],
  ['datalogger_38550',['DataLogger',['../da/d6c/classloggers_1_1data__logger__factory_1_1_data_logger.html',1,'loggers::data_logger_factory']]],
  ['datatypetraits_38551',['DataTypeTraits',['../dd/d0b/class_kratos_1_1_data_type_traits.html',1,'Kratos']]],
  ['datatypetraits_3c_20array_5f1d_3c_20tdatatype_2c_20tsize_20_3e_20_3e_38552',['DataTypeTraits&lt; array_1d&lt; TDataType, TSize &gt; &gt;',['../d5/d52/class_kratos_1_1_data_type_traits_3_01array__1d_3_01_t_data_type_00_01_t_size_01_4_01_4.html',1,'Kratos']]],
  ['datatypetraits_3c_20densematrix_3c_20tdatatype_20_3e_20_3e_38553',['DataTypeTraits&lt; DenseMatrix&lt; TDataType &gt; &gt;',['../d3/d44/class_kratos_1_1_data_type_traits_3_01_dense_matrix_3_01_t_data_type_01_4_01_4.html',1,'Kratos']]],
  ['datatypetraits_3c_20densevector_3c_20tdatatype_20_3e_20_3e_38554',['DataTypeTraits&lt; DenseVector&lt; TDataType &gt; &gt;',['../d8/d7b/class_kratos_1_1_data_type_traits_3_01_dense_vector_3_01_t_data_type_01_4_01_4.html',1,'Kratos']]],
  ['datatypetraits_3c_20std_3a_3astring_20_3e_38555',['DataTypeTraits&lt; std::string &gt;',['../d6/dd2/class_kratos_1_1_data_type_traits_3_01std_1_1string_01_4.html',1,'Kratos']]],
  ['datatypetraits_3c_20std_3a_3avector_3c_20tdatatype_20_3e_20_3e_38556',['DataTypeTraits&lt; std::vector&lt; TDataType &gt; &gt;',['../d4/dd4/class_kratos_1_1_data_type_traits_3_01std_1_1vector_3_01_t_data_type_01_4_01_4.html',1,'Kratos']]],
  ['datavaluecontainer_38557',['DataValueContainer',['../d7/dfa/class_kratos_1_1_data_value_container.html',1,'Kratos']]],
  ['dconvectiondiffusionexplicit_38558',['DConvectionDiffusionExplicit',['../d6/d56/class_kratos_1_1_d_convection_diffusion_explicit.html',1,'Kratos']]],
  ['dconvectiondiffusionexplicit_3c_202_2c_203_20_3e_38559',['DConvectionDiffusionExplicit&lt; 2, 3 &gt;',['../d6/d56/class_kratos_1_1_d_convection_diffusion_explicit.html',1,'Kratos']]],
  ['dconvectiondiffusionexplicit_3c_203_2c_204_20_3e_38560',['DConvectionDiffusionExplicit&lt; 3, 4 &gt;',['../d6/d56/class_kratos_1_1_d_convection_diffusion_explicit.html',1,'Kratos']]],
  ['deactivateconditionsoninactiveelements_38561',['DeactivateConditionsOnInactiveElements',['../dd/ded/class_kratos_1_1_deactivate_conditions_on_inactive_elements.html',1,'Kratos']]],
  ['deactivatemodelpartoperation_38562',['DeactivateModelPartOperation',['../d8/de3/class_kratos_1_1_deactivate_model_part_operation.html',1,'Kratos']]],
  ['decompressedmaterialbtstest_38563',['DecompressedMaterialBTSTest',['../d0/db7/classdecompressed__material__bts__test_1_1_decompressed_material_b_t_s_test.html',1,'decompressed_material_bts_test.DecompressedMaterialBTSTest'],['../d2/daa/classdecompressed__material__triaxials__and__bts__tests_1_1_decompressed_material_b_t_s_test.html',1,'decompressed_material_triaxials_and_bts_tests.DecompressedMaterialBTSTest']]],
  ['decompressedmaterialtriaxialtest_38564',['DecompressedMaterialTriaxialTest',['../d1/d17/classdecompressed__material__triaxial__test_1_1_decompressed_material_triaxial_test.html',1,'decompressed_material_triaxial_test.DecompressedMaterialTriaxialTest'],['../d6/d47/classdecompressed__material__triaxials__and__bts__tests_1_1_decompressed_material_triaxial_test.html',1,'decompressed_material_triaxials_and_bts_tests.DecompressedMaterialTriaxialTest']]],
  ['defaultcontroller_38565',['DefaultController',['../d2/d60/classcore_1_1controllers_1_1_default_controller.html',1,'core::controllers']]],
  ['define2dwakeprocess_38566',['Define2DWakeProcess',['../db/dcf/class_kratos_1_1_define2_d_wake_process.html',1,'Kratos']]],
  ['define3dwakeprocess_38567',['Define3DWakeProcess',['../d3/d72/class_kratos_1_1_define3_d_wake_process.html',1,'Kratos']]],
  ['defineembeddedwakeprocess_38568',['DefineEmbeddedWakeProcess',['../df/d56/classdefine__embedded__wake__process__2d_1_1_define_embedded_wake_process.html',1,'define_embedded_wake_process_2d.DefineEmbeddedWakeProcess'],['../de/dd9/class_kratos_1_1_define_embedded_wake_process.html',1,'Kratos::DefineEmbeddedWakeProcess']]],
  ['definewakeprocess_38569',['DefineWakeProcess',['../d6/da1/classdefine__wake__process_1_1_define_wake_process.html',1,'define_wake_process']]],
  ['definewakeprocess2d_38570',['DefineWakeProcess2D',['../d2/d7a/classdefine__wake__process__2d_1_1_define_wake_process2_d.html',1,'define_wake_process_2d']]],
  ['definewakeprocess3d_38571',['DefineWakeProcess3D',['../dd/dc0/classdefine__wake__process__3d_1_1_define_wake_process3_d.html',1,'define_wake_process_3d']]],
  ['deflatedcgsolver_38572',['DeflatedCGSolver',['../d5/d31/class_kratos_1_1_deflated_c_g_solver.html',1,'Kratos']]],
  ['deflationutils_38573',['DeflationUtils',['../d0/dbf/class_kratos_1_1_deflation_utils.html',1,'Kratos']]],
  ['deletemodelpartsmodeler_38574',['DeleteModelPartsModeler',['../d1/db7/classmodelers_1_1delete__model__parts__modeler_1_1_delete_model_parts_modeler.html',1,'modelers::delete_model_parts_modeler']]],
  ['deleteoldh5files_38575',['DeleteOldH5Files',['../d3/d15/classcore_1_1operations_1_1system_1_1_delete_old_h5_files.html',1,'core::operations::system']]],
  ['deltatimeparameters_38576',['DeltaTimeParameters',['../d2/de4/struct_kratos_1_1_explicit_central_differences_scheme_1_1_delta_time_parameters.html',1,'Kratos::ExplicitCentralDifferencesScheme&lt; TSparseSpace, TDenseSpace &gt;::DeltaTimeParameters'],['../d7/d98/struct_kratos_1_1_explicit_hamilton_scheme_1_1_delta_time_parameters.html',1,'Kratos::ExplicitHamiltonScheme&lt; TSparseSpace, TDenseSpace &gt;::DeltaTimeParameters'],['../d2/ddb/struct_kratos_1_1_explicit_multi_stage_kim_scheme_1_1_delta_time_parameters.html',1,'Kratos::ExplicitMultiStageKimScheme&lt; TSparseSpace, TDenseSpace &gt;::DeltaTimeParameters']]],
  ['dem_5fcompound_5fconstitutive_5flaw_38577',['DEM_compound_constitutive_law',['../da/d24/class_kratos_1_1_d_e_m__compound__constitutive__law.html',1,'Kratos']]],
  ['dem_5fcompound_5fconstitutive_5flaw_5ffor_5fpbm_38578',['DEM_compound_constitutive_law_for_PBM',['../d5/d16/class_kratos_1_1_d_e_m__compound__constitutive__law__for___p_b_m.html',1,'Kratos']]],
  ['dem_5fd_5fbentonite_5fcolloid_38579',['DEM_D_Bentonite_Colloid',['../d3/db4/class_kratos_1_1_d_e_m___d___bentonite___colloid.html',1,'Kratos']]],
  ['dem_5fd_5fconical_5fdamage_38580',['DEM_D_Conical_damage',['../dc/d9e/class_kratos_1_1_d_e_m___d___conical__damage.html',1,'Kratos']]],
  ['dem_5fd_5fdmt_5fcohesive_5flaw_38581',['DEM_D_DMT_Cohesive_Law',['../d4/da6/class_kratos_1_1_d_e_m___d___d_m_t___cohesive___law.html',1,'Kratos']]],
  ['dem_5fd_5fhertz_5fconfined_38582',['DEM_D_Hertz_confined',['../d9/d4e/class_kratos_1_1_d_e_m___d___hertz__confined.html',1,'Kratos']]],
  ['dem_5fd_5fhertz_5fviscous_5fcoulomb_38583',['DEM_D_Hertz_viscous_Coulomb',['../df/de3/class_kratos_1_1_d_e_m___d___hertz__viscous___coulomb.html',1,'Kratos']]],
  ['dem_5fd_5fhertz_5fviscous_5fcoulomb2d_38584',['DEM_D_Hertz_viscous_Coulomb2D',['../de/d52/class_kratos_1_1_d_e_m___d___hertz__viscous___coulomb2_d.html',1,'Kratos']]],
  ['dem_5fd_5fhertz_5fviscous_5fcoulomb_5fnestle_38585',['DEM_D_Hertz_viscous_Coulomb_Nestle',['../d8/d3e/class_kratos_1_1_d_e_m___d___hertz__viscous___coulomb___nestle.html',1,'Kratos']]],
  ['dem_5fd_5fjkr_5fcohesive_5flaw_38586',['DEM_D_JKR_Cohesive_Law',['../de/dc0/class_kratos_1_1_d_e_m___d___j_k_r___cohesive___law.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fclassic_38587',['DEM_D_Linear_classic',['../d9/d9a/class_kratos_1_1_d_e_m___d___linear__classic.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fconfined_38588',['DEM_D_Linear_confined',['../d4/dde/class_kratos_1_1_d_e_m___d___linear__confined.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fcustom_5fconstants_38589',['DEM_D_Linear_Custom_Constants',['../dd/d2b/class_kratos_1_1_d_e_m___d___linear___custom___constants.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fhighstiffness_38590',['DEM_D_Linear_HighStiffness',['../d9/db6/class_kratos_1_1_d_e_m___d___linear___high_stiffness.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fhighstiffness_5f2d_38591',['DEM_D_Linear_HighStiffness_2D',['../d5/d5d/class_kratos_1_1_d_e_m___d___linear___high_stiffness__2_d.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fviscous_5fcoulomb_38592',['DEM_D_Linear_viscous_Coulomb',['../d6/d53/class_kratos_1_1_d_e_m___d___linear__viscous___coulomb.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fviscous_5fcoulomb2d_38593',['DEM_D_Linear_viscous_Coulomb2D',['../d6/de2/class_kratos_1_1_d_e_m___d___linear__viscous___coulomb2_d.html',1,'Kratos']]],
  ['dem_5fd_5fquadratic_38594',['DEM_D_Quadratic',['../d3/d7a/class_kratos_1_1_d_e_m___d___quadratic.html',1,'Kratos']]],
  ['dem_5fd_5fstress_5fdependent_5fcohesive_38595',['DEM_D_Stress_Dependent_Cohesive',['../da/df2/class_kratos_1_1_d_e_m___d___stress___dependent___cohesive.html',1,'Kratos']]],
  ['dem_5fd_5fvoid_38596',['DEM_D_void',['../d0/d05/class_kratos_1_1_d_e_m___d__void.html',1,'Kratos']]],
  ['dem_5fdempack_38597',['DEM_Dempack',['../d1/d5a/class_kratos_1_1_d_e_m___dempack.html',1,'Kratos']]],
  ['dem_5fdempack2d_38598',['DEM_Dempack2D',['../d1/dc8/class_kratos_1_1_d_e_m___dempack2_d.html',1,'Kratos']]],
  ['dem_5fdempack2d_5fdev_38599',['DEM_Dempack2D_dev',['../d8/dc2/class_kratos_1_1_d_e_m___dempack2_d__dev.html',1,'Kratos']]],
  ['dem_5fdempack_5fdev_38600',['DEM_Dempack_dev',['../d2/d18/class_kratos_1_1_d_e_m___dempack__dev.html',1,'Kratos']]],
  ['dem_5fdempack_5ftorque_38601',['DEM_Dempack_torque',['../d3/d8c/class_kratos_1_1_d_e_m___dempack__torque.html',1,'Kratos']]],
  ['dem_5fexponentialhc_38602',['DEM_ExponentialHC',['../d2/d68/class_kratos_1_1_d_e_m___exponential_h_c.html',1,'Kratos']]],
  ['dem_5ffem_5fsearch_38603',['DEM_FEM_Search',['../d3/ddb/class_kratos_1_1_d_e_m___f_e_m___search.html',1,'Kratos']]],
  ['dem_5ffor_5fcoupling_5fsolution_38604',['DEM_for_coupling_Solution',['../de/d61/class_main_d_e_m__for__coupling_1_1_d_e_m__for__coupling___solution.html',1,'MainDEM_for_coupling']]],
  ['dem_5fforce_5fbased_5finlet_38605',['DEM_Force_Based_Inlet',['../d0/d49/class_kratos_1_1_d_e_m___force___based___inlet.html',1,'Kratos']]],
  ['dem_5finlet_38606',['DEM_Inlet',['../de/d2f/class_kratos_1_1_d_e_m___inlet.html',1,'Kratos']]],
  ['dem_5finlet_5fprocess_38607',['DEM_Inlet_Process',['../d5/d22/class_d_e_m__inlet__process_1_1_d_e_m___inlet___process.html',1,'DEM_inlet_process']]],
  ['dem_5fkdem_38608',['DEM_KDEM',['../da/de4/class_kratos_1_1_d_e_m___k_d_e_m.html',1,'Kratos']]],
  ['dem_5fkdem2d_38609',['DEM_KDEM2D',['../dc/d05/class_kratos_1_1_d_e_m___k_d_e_m2_d.html',1,'Kratos']]],
  ['dem_5fkdem_5fcamclay_38610',['DEM_KDEM_CamClay',['../dd/df4/class_kratos_1_1_d_e_m___k_d_e_m___cam_clay.html',1,'Kratos']]],
  ['dem_5fkdem_5ffissured_5frock_5fcl_38611',['DEM_KDEM_Fissured_Rock_CL',['../d9/df1/class_kratos_1_1_d_e_m___k_d_e_m___fissured___rock___c_l.html',1,'Kratos']]],
  ['dem_5fkdem_5fmohr_5fcoulomb_38612',['DEM_KDEM_Mohr_Coulomb',['../d6/d54/class_kratos_1_1_d_e_m___k_d_e_m___mohr___coulomb.html',1,'Kratos']]],
  ['dem_5fkdem_5frankine_38613',['DEM_KDEM_Rankine',['../d5/da1/class_kratos_1_1_d_e_m___k_d_e_m___rankine.html',1,'Kratos']]],
  ['dem_5fkdem_5fsoft_5ftorque_38614',['DEM_KDEM_soft_torque',['../dc/d56/class_kratos_1_1_d_e_m___k_d_e_m__soft__torque.html',1,'Kratos']]],
  ['dem_5fkdem_5fsoft_5ftorque_5fwith_5fnoise_38615',['DEM_KDEM_soft_torque_with_noise',['../d6/d61/class_kratos_1_1_d_e_m___k_d_e_m__soft__torque__with__noise.html',1,'Kratos']]],
  ['dem_5fkdem_5fwith_5fdamage_38616',['DEM_KDEM_with_damage',['../d6/dc8/class_kratos_1_1_d_e_m___k_d_e_m__with__damage.html',1,'Kratos']]],
  ['dem_5fkdem_5fwith_5fdamage_5fparallel_5fbond_38617',['DEM_KDEM_with_damage_parallel_bond',['../db/d54/class_kratos_1_1_d_e_m___k_d_e_m__with__damage__parallel__bond.html',1,'Kratos']]],
  ['dem_5fkdem_5fwith_5fdamage_5fparallel_5fbond_5f2d_38618',['DEM_KDEM_with_damage_parallel_bond_2D',['../d3/d00/class_kratos_1_1_d_e_m___k_d_e_m__with__damage__parallel__bond__2_d.html',1,'Kratos']]],
  ['dem_5fkdem_5fwith_5fdamage_5fparallel_5fbond_5fcapped_38619',['DEM_KDEM_with_damage_parallel_bond_capped',['../de/d4b/class_kratos_1_1_d_e_m___k_d_e_m__with__damage__parallel__bond__capped.html',1,'Kratos']]],
  ['dem_5fkdem_5fwith_5fdamage_5fparallel_5fbond_5fhertz_38620',['DEM_KDEM_with_damage_parallel_bond_Hertz',['../da/d4e/class_kratos_1_1_d_e_m___k_d_e_m__with__damage__parallel__bond___hertz.html',1,'Kratos']]],
  ['dem_5fkdem_5fwith_5fdamage_5fparallel_5fbond_5fhertz_5f2d_38621',['DEM_KDEM_with_damage_parallel_bond_Hertz_2D',['../d4/d5a/class_kratos_1_1_d_e_m___k_d_e_m__with__damage__parallel__bond___hertz__2_d.html',1,'Kratos']]],
  ['dem_5fkdemfabric_38622',['DEM_KDEMFabric',['../d7/d0b/class_kratos_1_1_d_e_m___k_d_e_m_fabric.html',1,'Kratos']]],
  ['dem_5fkdemfabric2d_38623',['DEM_KDEMFabric2D',['../d2/d78/class_kratos_1_1_d_e_m___k_d_e_m_fabric2_d.html',1,'Kratos']]],
  ['dem_5fparallel_5fbond_38624',['DEM_parallel_bond',['../d0/d7f/class_kratos_1_1_d_e_m__parallel__bond.html',1,'Kratos']]],
  ['dem_5fparallel_5fbond_5ffor_5fmembrane_38625',['DEM_parallel_bond_for_membrane',['../db/dd2/class_kratos_1_1_d_e_m__parallel__bond__for__membrane.html',1,'Kratos']]],
  ['dem_5fsmooth_5fjoint_38626',['DEM_smooth_joint',['../d7/de1/class_kratos_1_1_d_e_m__smooth__joint.html',1,'Kratos']]],
  ['demanalysisstage_38627',['DEMAnalysisStage',['../dd/d91/class_d_e_m__analysis__stage_1_1_d_e_m_analysis_stage.html',1,'DEM_analysis_stage']]],
  ['demanalysisstagewithflush_38628',['DEMAnalysisStageWithFlush',['../d2/da8/class_kratos_d_e_m_analysis_1_1_d_e_m_analysis_stage_with_flush.html',1,'KratosDEMAnalysis.DEMAnalysisStageWithFlush'],['../dc/d42/class_main_kratos_thermal_d_e_m_analysis_1_1_d_e_m_analysis_stage_with_flush.html',1,'MainKratosThermalDEMAnalysis.DEMAnalysisStageWithFlush']]],
  ['dembeamconstitutivelaw_38629',['DEMBeamConstitutiveLaw',['../df/d5a/class_kratos_1_1_d_e_m_beam_constitutive_law.html',1,'Kratos']]],
  ['dembenchmarksanalysisstage_38630',['DEMBenchmarksAnalysisStage',['../d3/d15/class_d_e_m__benchmarks__analysis_1_1_d_e_m_benchmarks_analysis_stage.html',1,'DEM_benchmarks_analysis']]],
  ['demcontact_38631',['DemContact',['../d4/d5c/class_kratos_1_1_dem_contact.html',1,'Kratos']]],
  ['demcontinuumconstitutivelaw_38632',['DEMContinuumConstitutiveLaw',['../da/df9/class_kratos_1_1_d_e_m_continuum_constitutive_law.html',1,'Kratos']]],
  ['demcoupledfluiddynamicsanalysis_38633',['DEMCoupledFluidDynamicsAnalysis',['../dd/d98/class_d_e_m__coupled__fluid__dynamics__analysis_1_1_d_e_m_coupled_fluid_dynamics_analysis.html',1,'DEM_coupled_fluid_dynamics_analysis']]],
  ['demcoupledpfemfluiddynamicsanalysis_38634',['DEMCoupledPFEMFluidDynamicsAnalysis',['../dd/d5b/class_d_e_m__coupled__pfem__fluid__dynamics__analysis_1_1_d_e_m_coupled_p_f_e_m_fluid_dynamics_analysis.html',1,'DEM_coupled_pfem_fluid_dynamics_analysis']]],
  ['demdiscontinuumconstitutivelaw_38635',['DEMDiscontinuumConstitutiveLaw',['../d5/dcb/class_kratos_1_1_d_e_m_discontinuum_constitutive_law.html',1,'Kratos']]],
  ['demenergycalculator_38636',['DEMEnergyCalculator',['../d0/def/class_d_e_m__procedures_1_1_d_e_m_energy_calculator.html',1,'DEM_procedures.DEMEnergyCalculator'],['../d4/d42/class_d_e_m__procedures__mpi_1_1_d_e_m_energy_calculator.html',1,'DEM_procedures_mpi.DEMEnergyCalculator']]],
  ['demfemprocedures_38637',['DEMFEMProcedures',['../d6/d8b/class_d_e_m__procedures_1_1_d_e_m_f_e_m_procedures.html',1,'DEM_procedures.DEMFEMProcedures'],['../d4/dc3/class_d_e_m__procedures__mpi_1_1_d_e_m_f_e_m_procedures.html',1,'DEM_procedures_mpi.DEMFEMProcedures']]],
  ['demfemutilities_38638',['DEMFEMUtilities',['../d3/d38/class_kratos_1_1_d_e_m_f_e_m_utilities.html',1,'Kratos']]],
  ['demflags_38639',['DEMFlags',['../d0/d83/class_kratos_1_1_d_e_m_flags.html',1,'Kratos']]],
  ['demintegrationscheme_38640',['DEMIntegrationScheme',['../db/dc1/class_kratos_1_1_d_e_m_integration_scheme.html',1,'Kratos']]],
  ['demio_38641',['DEMIo',['../dd/db9/class_d_e_m__procedures_1_1_d_e_m_io.html',1,'DEM_procedures.DEMIo'],['../d6/d8f/class_d_e_m__procedures__mpi_1_1_d_e_m_io.html',1,'DEM_procedures_mpi.DEMIo'],['../d3/dc4/class_d_e_m__procedures__mpi__no__partitions_1_1_d_e_m_io.html',1,'DEM_procedures_mpi_no_partitions.DEMIo']]],
  ['demporomechanicscouplingsolver_38642',['DemPoroMechanicsCouplingSolver',['../dc/d52/classdem__poromechanics__coupling__analysis__stage_1_1_dem_poro_mechanics_coupling_solver.html',1,'dem_poromechanics_coupling_analysis_stage']]],
  ['demrestartutility_38643',['DEMRestartUtility',['../d8/d41/class_d_e_m__restart__utility_1_1_d_e_m_restart_utility.html',1,'DEM_restart_utility']]],
  ['demrollingfrictionmodel_38644',['DEMRollingFrictionModel',['../d1/d4a/class_kratos_1_1_d_e_m_rolling_friction_model.html',1,'Kratos']]],
  ['demrollingfrictionmodelbounded_38645',['DEMRollingFrictionModelBounded',['../d0/d86/class_kratos_1_1_d_e_m_rolling_friction_model_bounded.html',1,'Kratos']]],
  ['demrollingfrictionmodelconstanttorque_38646',['DEMRollingFrictionModelConstantTorque',['../d0/d18/class_kratos_1_1_d_e_m_rolling_friction_model_constant_torque.html',1,'Kratos']]],
  ['demrollingfrictionmodelviscoustorque_38647',['DEMRollingFrictionModelViscousTorque',['../d1/dce/class_kratos_1_1_d_e_m_rolling_friction_model_viscous_torque.html',1,'Kratos']]],
  ['demsaverestartprocess_38648',['DEMSaveRestartProcess',['../d2/d21/class_d_e_m__save__restart__process_1_1_d_e_m_save_restart_process.html',1,'DEM_save_restart_process']]],
  ['demsearch_38649',['DEMSearch',['../db/da5/class_kratos_1_1_d_e_m_search.html',1,'Kratos']]],
  ['demsearch_3c_20omp_5fdemsearch_20_3e_38650',['DEMSearch&lt; OMP_DEMSearch &gt;',['../db/da5/class_kratos_1_1_d_e_m_search.html',1,'Kratos']]],
  ['demsearchutilities_38651',['DemSearchUtilities',['../df/de0/class_kratos_1_1_dem_search_utilities.html',1,'Kratos']]],
  ['demstructurescouplingflags_38652',['DemStructuresCouplingFlags',['../d0/d3c/class_kratos_1_1_dem_structures_coupling_flags.html',1,'Kratos']]],
  ['demstructurescouplinggidoutput_38653',['DemStructuresCouplingGiDOutput',['../da/dfb/classdem__structures__coupling__gid__output_1_1_dem_structures_coupling_gi_d_output.html',1,'dem_structures_coupling_gid_output']]],
  ['demstructurescouplingutilities_38654',['DemStructuresCouplingUtilities',['../dc/d25/class_kratos_1_1_dem_structures_coupling_utilities.html',1,'Kratos']]],
  ['demthermalflags_38655',['DEMThermalFlags',['../d3/d9f/class_kratos_1_1_d_e_m_thermal_flags.html',1,'Kratos']]],
  ['demwall_38656',['DEMWall',['../d7/d8a/class_kratos_1_1_d_e_m_wall.html',1,'Kratos']]],
  ['demwrapper_38657',['DEMWrapper',['../dc/d13/classsolver__wrappers_1_1kratos_1_1dem__wrapper_1_1_d_e_m_wrapper.html',1,'solver_wrappers::kratos::dem_wrapper']]],
  ['denseeigenvaluesolver_38658',['DenseEigenvalueSolver',['../d1/d60/class_kratos_1_1_dense_eigenvalue_solver.html',1,'Kratos']]],
  ['densehouseholderqrdecomposition_38659',['DenseHouseholderQRDecomposition',['../d4/d05/class_kratos_1_1_dense_householder_q_r_decomposition.html',1,'Kratos']]],
  ['denselinearsolverfactory_38660',['DenseLinearSolverFactory',['../d0/da5/class_kratos_1_1_dense_linear_solver_factory.html',1,'Kratos']]],
  ['denseqrdecomposition_38661',['DenseQRDecomposition',['../db/d82/class_kratos_1_1_dense_q_r_decomposition.html',1,'Kratos']]],
  ['denseqrdecomposition_3c_20tdensespace_20_3e_38662',['DenseQRDecomposition&lt; TDenseSpace &gt;',['../db/d82/class_kratos_1_1_dense_q_r_decomposition.html',1,'Kratos']]],
  ['densesingularvaluedecomposition_38663',['DenseSingularValueDecomposition',['../d7/df0/class_kratos_1_1_dense_singular_value_decomposition.html',1,'Kratos']]],
  ['densesingularvaluedecomposition_3c_20tdensespace_20_3e_38664',['DenseSingularValueDecomposition&lt; TDenseSpace &gt;',['../d7/df0/class_kratos_1_1_dense_singular_value_decomposition.html',1,'Kratos']]],
  ['densityfunction_38665',['DensityFunction',['../d1/dcb/class_kratos_1_1_density_function.html',1,'Kratos']]],
  ['densityfunctionnormal_38666',['DensityFunctionNormal',['../de/db8/class_kratos_1_1_density_function_normal.html',1,'Kratos']]],
  ['densityfunctionpolynomial_38667',['DensityFunctionPolynomial',['../db/d85/class_kratos_1_1_density_function_polynomial.html',1,'Kratos']]],
  ['deprecationmanager_38668',['DeprecationManager',['../d1/d8b/classdeprecation__management_1_1_deprecation_manager.html',1,'deprecation_management']]],
  ['depthintegrationinputprocess_38669',['DepthIntegrationInputProcess',['../dd/dfe/classdepth__integration__input__process_1_1_depth_integration_input_process.html',1,'depth_integration_input_process']]],
  ['depthintegrationoutputprocess_38670',['DepthIntegrationOutputProcess',['../d9/d0f/classdepth__integration__output__process_1_1_depth_integration_output_process.html',1,'depth_integration_output_process']]],
  ['depthintegrationprocess_38671',['DepthIntegrationProcess',['../db/de0/class_kratos_1_1_depth_integration_process.html',1,'Kratos']]],
  ['derivative_38672',['Derivative',['../d7/ddd/class_kratos_1_1_q_s_v_m_s_derivative_utilities_1_1_derivative.html',1,'Kratos::QSVMSDerivativeUtilities']]],
  ['derivative_3c_200_20_3e_38673',['Derivative&lt; 0 &gt;',['../d7/ddd/class_kratos_1_1_q_s_v_m_s_derivative_utilities_1_1_derivative.html',1,'Kratos::QSVMSDerivativeUtilities']]],
  ['derivative_3c_20tcomponentindex_20_3e_38674',['Derivative&lt; TComponentIndex &gt;',['../d7/ddd/class_kratos_1_1_q_s_v_m_s_derivative_utilities_1_1_derivative.html',1,'Kratos::QSVMSDerivativeUtilities']]],
  ['derivativedata_38675',['DerivativeData',['../db/d37/class_kratos_1_1_derivative_data.html',1,'Kratos']]],
  ['derivativedata_3c_20tdim_2c_20tnumnodes_2c_20tnumnodes_20_3e_38676',['DerivativeData&lt; TDim, TNumNodes, TNumNodes &gt;',['../db/d37/class_kratos_1_1_derivative_data.html',1,'Kratos']]],
  ['derivativedatafrictional_38677',['DerivativeDataFrictional',['../d5/d9c/class_kratos_1_1_derivative_data_frictional.html',1,'Kratos']]],
  ['derivativerecovery_38678',['DerivativeRecovery',['../dc/db2/class_kratos_1_1_derivative_recovery.html',1,'Kratos']]],
  ['derivativerecoverymeshingtools_38679',['DerivativeRecoveryMeshingTools',['../d3/de3/class_kratos_1_1_derivative_recovery_meshing_tools.html',1,'Kratos']]],
  ['derivativerecoverystrategy_38680',['DerivativeRecoveryStrategy',['../da/def/classderivative__recovery_1_1derivative__recovery__strategy_1_1_derivative_recovery_strategy.html',1,'derivative_recovery::derivative_recovery_strategy']]],
  ['derivativesrecoverer_38681',['DerivativesRecoverer',['../d4/d08/classderivative__recovery_1_1recoverer_1_1_derivatives_recoverer.html',1,'derivative_recovery::recoverer']]],
  ['derivativesrecoveryprocess_38682',['DerivativesRecoveryProcess',['../d3/d42/classderivatives__recovery__process_1_1_derivatives_recovery_process.html',1,'derivatives_recovery_process']]],
  ['derivativesrecoveryutility_38683',['DerivativesRecoveryUtility',['../db/df0/class_kratos_1_1_derivatives_recovery_utility.html',1,'Kratos']]],
  ['derivativesutilities_38684',['DerivativesUtilities',['../d8/dfa/class_kratos_1_1_derivatives_utilities.html',1,'Kratos']]],
  ['designlogger_38685',['DesignLogger',['../d6/d7d/classloggers_1_1design__logger__base_1_1_design_logger.html',1,'loggers::design_logger_base']]],
  ['designloggergid_38686',['DesignLoggerGID',['../d5/d0a/classloggers_1_1design__logger__gid_1_1_design_logger_g_i_d.html',1,'loggers::design_logger_gid']]],
  ['designloggerunv_38687',['DesignLoggerUNV',['../d4/d23/classloggers_1_1design__logger__unv_1_1_design_logger_u_n_v.html',1,'loggers::design_logger_unv']]],
  ['designloggervtk_38688',['DesignLoggerVTK',['../de/d93/classloggers_1_1design__logger__vtk_1_1_design_logger_v_t_k.html',1,'loggers::design_logger_vtk']]],
  ['det_38689',['det',['../d1/d12/interfacetensors_1_1det.html',1,'tensors']]],
  ['dev_38690',['dev',['../df/d52/interfacetensors_1_1dev.html',1,'tensors']]],
  ['deviatoricplaneshapeutilities_38691',['DeviatoricPlaneShapeUtilities',['../dc/df3/class_kratos_1_1_deviatoric_plane_shape_utilities.html',1,'Kratos']]],
  ['diagonal_38692',['Diagonal',['../df/d30/struct_kratos_1_1_brep_trimming_utilities_1_1_diagonal.html',1,'Kratos::BrepTrimmingUtilities']]],
  ['diagonalpreconditioner_38693',['DiagonalPreconditioner',['../da/df4/class_kratos_1_1_diagonal_preconditioner.html',1,'Kratos']]],
  ['differentdatadifferenceresidual_38694',['DifferentDataDifferenceResidual',['../d2/dc9/classconvergence__accelerators_1_1convergence__accelerator__wrapper_1_1_different_data_difference_residual.html',1,'convergence_accelerators::convergence_accelerator_wrapper']]],
  ['differentialoperator_38695',['DifferentialOperator',['../d3/dc9/classderivatives__recovery__process_1_1_derivatives_recovery_process_1_1_differential_operator.html',1,'derivatives_recovery_process::DerivativesRecoveryProcess']]],
  ['directconductionbobcomplete_38696',['DirectConductionBOBComplete',['../d5/d46/class_kratos_1_1_direct_conduction_b_o_b_complete.html',1,'Kratos']]],
  ['directconductionbobmodified_38697',['DirectConductionBOBModified',['../d0/d0b/class_kratos_1_1_direct_conduction_b_o_b_modified.html',1,'Kratos']]],
  ['directconductionbobsimple_38698',['DirectConductionBOBSimple',['../d7/df4/class_kratos_1_1_direct_conduction_b_o_b_simple.html',1,'Kratos']]],
  ['directconductioncollision_38699',['DirectConductionCollision',['../d6/d2c/class_kratos_1_1_direct_conduction_collision.html',1,'Kratos']]],
  ['directconductionmodel_38700',['DirectConductionModel',['../d0/daf/class_kratos_1_1_direct_conduction_model.html',1,'Kratos']]],
  ['directconductionpipe_38701',['DirectConductionPipe',['../dd/d00/class_kratos_1_1_direct_conduction_pipe.html',1,'Kratos']]],
  ['directcopytransfer_38702',['DirectCopyTransfer',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20array_5f1d_3c_20double_2c_20tdim_20_3e_20_3e_38703',['DirectCopyTransfer&lt; array_1d&lt; double, TDim &gt; &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20bool_20_3e_38704',['DirectCopyTransfer&lt; bool &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20double_20_3e_38705',['DirectCopyTransfer&lt; double &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20int_20_3e_38706',['DirectCopyTransfer&lt; int &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20kratos_3a_3aflags_20_3e_38707',['DirectCopyTransfer&lt; Kratos::Flags &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directiondampingutilities_38708',['DirectionDampingUtilities',['../d9/df2/class_kratos_1_1_direction_damping_utilities.html',1,'Kratos']]],
  ['directorsvariables_38709',['DirectorsVariables',['../d5/d76/struct_kratos_1_1_beam_element_1_1_directors_variables.html',1,'Kratos::BeamElement']]],
  ['directorutilities_38710',['DirectorUtilities',['../d4/d36/class_kratos_1_1_director_utilities.html',1,'Kratos']]],
  ['directsolver_38711',['DirectSolver',['../df/dc7/class_kratos_1_1_direct_solver.html',1,'Kratos']]],
  ['directsolver_3c_20tsparsespacetype_2c_20tdensespacetype_2c_20reorderer_3c_20tsparsespacetype_2c_20tdensespacetype_20_3e_20_3e_38712',['DirectSolver&lt; TSparseSpaceType, TDenseSpaceType, Reorderer&lt; TSparseSpaceType, TDenseSpaceType &gt; &gt;',['../df/dc7/class_kratos_1_1_direct_solver.html',1,'Kratos']]],
  ['directsolver_3c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3aglobal_2c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_2c_20reorderer_3c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3aglobal_2c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_20_3e_20_3e_38713',['DirectSolver&lt; typename SpaceType&lt; typename TSolverType::Scalar &gt;::Global, typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local, Reorderer&lt; typename SpaceType&lt; typename TSolverType::Scalar &gt;::Global, typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local &gt; &gt;',['../df/dc7/class_kratos_1_1_direct_solver.html',1,'Kratos']]],
  ['directsolver_3c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_2c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_2c_20reorderer_3c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_2c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_20_3e_20_3e_38714',['DirectSolver&lt; typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local, typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local, Reorderer&lt; typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local, typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local &gt; &gt;',['../df/dc7/class_kratos_1_1_direct_solver.html',1,'Kratos']]],
  ['discontinuousshapefunctionsutilities_38715',['DiscontinuousShapeFunctionsUtilities',['../d7/d64/class_kratos_1_1_discontinuous_shape_functions_utilities.html',1,'Kratos']]],
  ['discontinuousshapefunctionsutilities_5f2d_38716',['DiscontinuousShapeFunctionsUtilities_2D',['../d4/d20/class_kratos_1_1_discontinuous_shape_functions_utilities__2_d.html',1,'Kratos']]],
  ['discreteelement_38717',['DiscreteElement',['../d0/ddc/class_kratos_1_1_discrete_element.html',1,'Kratos']]],
  ['discreteparticleconfigure_38718',['DiscreteParticleConfigure',['../dc/dff/class_kratos_1_1_discrete_particle_configure.html',1,'Kratos']]],
  ['discreterandomvariable_38719',['DiscreteRandomVariable',['../d5/dfa/class_kratos_1_1_discrete_random_variable.html',1,'Kratos']]],
  ['displacementcontactcriteria_38720',['DisplacementContactCriteria',['../d1/df2/class_kratos_1_1_displacement_contact_criteria.html',1,'Kratos']]],
  ['displacementcontrolcondition_38721',['DisplacementControlCondition',['../d1/dc1/class_kratos_1_1_displacement_control_condition.html',1,'Kratos']]],
  ['displacementcriteria_38722',['DisplacementCriteria',['../d3/d7f/class_kratos_1_1_displacement_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultipliercontactcriteria_38723',['DisplacementLagrangeMultiplierContactCriteria',['../d9/d87/class_kratos_1_1_displacement_lagrange_multiplier_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultiplierfrictionalcontactcriteria_38724',['DisplacementLagrangeMultiplierFrictionalContactCriteria',['../d2/dd3/class_kratos_1_1_displacement_lagrange_multiplier_frictional_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultipliermixedcontactcriteria_38725',['DisplacementLagrangeMultiplierMixedContactCriteria',['../d0/d61/class_kratos_1_1_displacement_lagrange_multiplier_mixed_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultipliermixedfrictionalcontactcriteria_38726',['DisplacementLagrangeMultiplierMixedFrictionalContactCriteria',['../d3/d27/class_kratos_1_1_displacement_lagrange_multiplier_mixed_frictional_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultiplierresidualcontactcriteria_38727',['DisplacementLagrangeMultiplierResidualContactCriteria',['../d0/dbc/class_kratos_1_1_displacement_lagrange_multiplier_residual_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultiplierresidualfrictionalcontactcriteria_38728',['DisplacementLagrangeMultiplierResidualFrictionalContactCriteria',['../d8/df9/class_kratos_1_1_displacement_lagrange_multiplier_residual_frictional_contact_criteria.html',1,'Kratos']]],
  ['displacementresidualcontactcriteria_38729',['DisplacementResidualContactCriteria',['../d8/db2/class_kratos_1_1_displacement_residual_contact_criteria.html',1,'Kratos']]],
  ['displacementsensor_38730',['DisplacementSensor',['../d7/d20/class_kratos_1_1_displacement_sensor.html',1,'Kratos']]],
  ['displacementshiftedboundarycondition_38731',['DisplacementShiftedBoundaryCondition',['../d4/d1b/class_kratos_1_1_displacement_shifted_boundary_condition.html',1,'Kratos']]],
  ['dispnewtonianfluid3dlaw_38732',['DispNewtonianFluid3DLaw',['../d9/d82/class_kratos_1_1_disp_newtonian_fluid3_d_law.html',1,'Kratos']]],
  ['dispnewtonianfluidplanestrain2dlaw_38733',['DispNewtonianFluidPlaneStrain2DLaw',['../d2/da8/class_kratos_1_1_disp_newtonian_fluid_plane_strain2_d_law.html',1,'Kratos']]],
  ['distancecalculationelementsimplex_38734',['DistanceCalculationElementSimplex',['../d7/d6e/class_kratos_1_1_distance_calculation_element_simplex.html',1,'Kratos']]],
  ['distancecalculationelementsimplex_3c_202_20_3e_38735',['DistanceCalculationElementSimplex&lt; 2 &gt;',['../d7/d6e/class_kratos_1_1_distance_calculation_element_simplex.html',1,'Kratos']]],
  ['distancecalculationelementsimplex_3c_203_20_3e_38736',['DistanceCalculationElementSimplex&lt; 3 &gt;',['../d7/d6e/class_kratos_1_1_distance_calculation_element_simplex.html',1,'Kratos']]],
  ['distancecalculator_38737',['DistanceCalculator',['../d9/d3e/class_kratos_1_1_distance_calculator.html',1,'Kratos']]],
  ['distancecalculator1_38738',['DistanceCalculator1',['../d5/d36/class_kratos_1_1_distance_calculator1.html',1,'Kratos']]],
  ['distanceimportutility_38739',['DistanceImportUtility',['../d8/da8/classread__distance__from__file_1_1_distance_import_utility.html',1,'read_distance_from_file']]],
  ['distancemodificationprocess_38740',['DistanceModificationProcess',['../d9/dd2/class_kratos_1_1_distance_modification_process.html',1,'Kratos']]],
  ['distancesmoothingelement_38741',['DistanceSmoothingElement',['../db/dad/class_kratos_1_1_distance_smoothing_element.html',1,'Kratos']]],
  ['distancesmoothingprocess_38742',['DistanceSmoothingProcess',['../d9/d27/class_kratos_1_1_distance_smoothing_process.html',1,'Kratos']]],
  ['distancespatialcontainersconditionconfigure_38743',['DistanceSpatialContainersConditionConfigure',['../da/d90/class_kratos_1_1_distance_spatial_containers_condition_configure.html',1,'Kratos']]],
  ['distancespatialcontainersconfigure_38744',['DistanceSpatialContainersConfigure',['../d1/d71/class_kratos_1_1_distance_spatial_containers_configure.html',1,'Kratos::DistanceSpatialContainersConfigure'],['../d0/d1c/class_kratos_1_1_internals_1_1_distance_spatial_containers_configure.html',1,'Kratos::Internals::DistanceSpatialContainersConfigure']]],
  ['distributedamgclcsrspmmutilities_38745',['DistributedAmgclCSRSpMMUtilities',['../d4/dee/class_kratos_1_1_distributed_amgcl_c_s_r_sp_m_m_utilities.html',1,'Kratos']]],
  ['distributedcsrmatrix_38746',['DistributedCsrMatrix',['../d7/d64/class_kratos_1_1_distributed_csr_matrix.html',1,'Kratos']]],
  ['distributedfilter_38747',['DistributedFilter',['../d7/dc4/class_kratos_1_1_logger_message_1_1_distributed_filter.html',1,'Kratos::LoggerMessage']]],
  ['distributedgidoutputprocess_38748',['DistributedGiDOutputProcess',['../da/d6d/classdistributed__gid__output__process_1_1_distributed_gi_d_output_process.html',1,'distributed_gid_output_process']]],
  ['distributedimportmodelpartutility_38749',['DistributedImportModelPartUtility',['../d9/d32/classdistributed__import__model__part__utility_1_1_distributed_import_model_part_utility.html',1,'distributed_import_model_part_utility']]],
  ['distributedmodelpartinitializer_38750',['DistributedModelPartInitializer',['../dd/db3/class_kratos_1_1_distributed_model_part_initializer.html',1,'Kratos']]],
  ['distributednumbering_38751',['DistributedNumbering',['../da/da4/class_kratos_1_1_distributed_numbering.html',1,'Kratos']]],
  ['distributednumbering_3c_20indextype_20_3e_38752',['DistributedNumbering&lt; IndexType &gt;',['../da/da4/class_kratos_1_1_distributed_numbering.html',1,'Kratos']]],
  ['distributednumbering_3c_20std_3a_3asize_5ft_20_3e_38753',['DistributedNumbering&lt; std::size_t &gt;',['../da/da4/class_kratos_1_1_distributed_numbering.html',1,'Kratos']]],
  ['distributedrestartutility_38754',['DistributedRestartUtility',['../d4/d2d/classdistributed__restart__utility_1_1_distributed_restart_utility.html',1,'distributed_restart_utility']]],
  ['distributedsearchinformation_38755',['DistributedSearchInformation',['../da/d45/struct_kratos_1_1_distributed_search_information.html',1,'Kratos']]],
  ['distributedsparsegraph_38756',['DistributedSparseGraph',['../d2/dcc/class_kratos_1_1_distributed_sparse_graph.html',1,'Kratos']]],
  ['distributedsystemvector_38757',['DistributedSystemVector',['../df/dcf/class_kratos_1_1_distributed_system_vector.html',1,'Kratos']]],
  ['distributedtestcase_38758',['DistributedTestCase',['../db/dc9/class_kratos_1_1_testing_1_1_distributed_test_case.html',1,'Kratos::Testing']]],
  ['distributedvectorexporter_38759',['DistributedVectorExporter',['../db/d00/class_kratos_1_1_distributed_vector_exporter.html',1,'Kratos']]],
  ['distributedvectorexporter_3c_20std_3a_3asize_5ft_20_3e_38760',['DistributedVectorExporter&lt; std::size_t &gt;',['../db/d00/class_kratos_1_1_distributed_vector_exporter.html',1,'Kratos']]],
  ['distributedvectorimporter_38761',['DistributedVectorImporter',['../d4/d23/class_kratos_1_1_distributed_vector_importer.html',1,'Kratos']]],
  ['distributeloadonsurfaceprocess_38762',['DistributeLoadOnSurfaceProcess',['../d5/d20/class_kratos_1_1_distribute_load_on_surface_process.html',1,'Kratos']]],
  ['distributepointvaluesoperation_38763',['DistributePointValuesOperation',['../dc/d46/classcoupling__operations_1_1distribute__point__values_1_1_distribute_point_values_operation.html',1,'coupling_operations::distribute_point_values']]],
  ['divergencefreerefinementprocess_38764',['DivergenceFreeRefinementProcess',['../d4/de1/classdivergencefree__refinement__process_1_1_divergence_free_refinement_process.html',1,'divergencefree_refinement_process']]],
  ['dividegeometry_38765',['DivideGeometry',['../d6/de8/class_kratos_1_1_divide_geometry.html',1,'Kratos']]],
  ['dividetetrahedra3d4_38766',['DivideTetrahedra3D4',['../db/d9f/class_kratos_1_1_divide_tetrahedra3_d4.html',1,'Kratos']]],
  ['dividetetrahedra3d4_3c_20kratos_3a_3anode_20_3e_38767',['DivideTetrahedra3D4&lt; Kratos::Node &gt;',['../db/d9f/class_kratos_1_1_divide_tetrahedra3_d4.html',1,'Kratos']]],
  ['dividetriangle2d3_38768',['DivideTriangle2D3',['../da/df0/class_kratos_1_1_divide_triangle2_d3.html',1,'Kratos']]],
  ['dividetriangle2d3_3c_20kratos_3a_3anode_20_3e_38769',['DivideTriangle2D3&lt; Kratos::Node &gt;',['../da/df0/class_kratos_1_1_divide_triangle2_d3.html',1,'Kratos']]],
  ['dividetriangle3d3_38770',['DivideTriangle3D3',['../d9/d7d/class_kratos_1_1_divide_triangle3_d3.html',1,'Kratos']]],
  ['division_38771',['Division',['../dc/d2a/struct_kratos_1_1_binary_operations_1_1_division.html',1,'Kratos::BinaryOperations']]],
  ['dof_38772',['Dof',['../dc/d58/class_kratos_1_1_dof.html',1,'Kratos']]],
  ['dof_5fiterator_5fequal_38773',['dof_iterator_equal',['../dd/d0b/struct_kratos_1_1_block_builder_and_solver_1_1dof__iterator__equal.html',1,'Kratos::BlockBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::dof_iterator_equal'],['../d7/d15/struct_kratos_1_1_reduction_builder_and_solver_1_1dof__iterator__equal.html',1,'Kratos::ReductionBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::dof_iterator_equal']]],
  ['dof_5fiterator_5fhash_38774',['dof_iterator_hash',['../d1/d5d/struct_kratos_1_1_block_builder_and_solver_1_1dof__iterator__hash.html',1,'Kratos::BlockBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::dof_iterator_hash'],['../dd/d96/struct_kratos_1_1_reduction_builder_and_solver_1_1dof__iterator__hash.html',1,'Kratos::ReductionBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::dof_iterator_hash']]],
  ['dofdata_38775',['DofData',['../d6/ddd/struct_kratos_1_1_mesh_tying_mortar_condition_1_1_dof_data.html',1,'Kratos::MeshTyingMortarCondition']]],
  ['dofidaccess_38776',['DofIdAccess',['../df/d56/class_kratos_1_1_m_p_i_internals_1_1_dof_id_access.html',1,'Kratos::MPIInternals']]],
  ['dofpointercomparor_38777',['DofPointerComparor',['../d7/dbc/struct_kratos_1_1_dof_pointer_comparor.html',1,'Kratos']]],
  ['dofpointerhasher_38778',['DofPointerHasher',['../df/dc1/struct_kratos_1_1_dof_pointer_hasher.html',1,'Kratos']]],
  ['dofscriterion_38779',['DofsCriterion',['../d8/d29/class_kratos_1_1_dofs_criterion.html',1,'Kratos']]],
  ['doftrait_38780',['DofTrait',['../dc/d06/struct_kratos_1_1_dof_trait.html',1,'Kratos']]],
  ['dofupdater_38781',['DofUpdater',['../d3/d3f/class_kratos_1_1_dof_updater.html',1,'Kratos']]],
  ['domain_38782',['Domain',['../d1/d20/classcore_1_1xdmf_1_1_domain.html',1,'core::xdmf']]],
  ['domainentitiesidcontainer_38783',['DomainEntitiesIdContainer',['../d5/d75/class_kratos_1_1_morton_divide_input_to_partitions_process_1_1_domain_entities_id_container.html',1,'Kratos::MortonDivideInputToPartitionsProcess']]],
  ['domainpanel2d_38784',['DomainPanel2D',['../de/dee/classprojection__utilities_1_1_domain_panel2_d.html',1,'projection_utilities']]],
  ['domainpanel3d_38785',['DomainPanel3D',['../d5/d16/classprojection__utilities_1_1_domain_panel3_d.html',1,'projection_utilities']]],
  ['domainsizeexpressionio_38786',['DomainSizeExpressionIO',['../d7/d20/class_kratos_1_1_domain_size_expression_i_o.html',1,'Kratos']]],
  ['domainutilities_38787',['DomainUtilities',['../dc/d27/classdomain__utilities_1_1_domain_utilities.html',1,'domain_utilities']]],
  ['dpgvms_38788',['DPGVMS',['../d7/d1a/class_kratos_1_1_d_p_g_v_m_s.html',1,'Kratos']]],
  ['dpgvms_3c_202_20_3e_38789',['DPGVMS&lt; 2 &gt;',['../d7/d1a/class_kratos_1_1_d_p_g_v_m_s.html',1,'Kratos']]],
  ['dpgvms_3c_203_20_3e_38790',['DPGVMS&lt; 3 &gt;',['../d7/d1a/class_kratos_1_1_d_p_g_v_m_s.html',1,'Kratos']]],
  ['dpstate_38791',['DPState',['../d3/dd5/struct_kratos_1_1_brep_trimming_utilities_1_1_d_p_state.html',1,'Kratos::BrepTrimmingUtilities']]],
  ['dragandmomentutilities_38792',['DragAndMomentUtilities',['../d6/d33/class_kratos_1_1_drag_and_moment_utilities.html',1,'Kratos']]],
  ['draglaw_38793',['DragLaw',['../db/dfa/class_kratos_1_1_drag_law.html',1,'Kratos']]],
  ['dragresponsefunction_38794',['DragResponseFunction',['../d3/de1/class_kratos_1_1_drag_response_function.html',1,'Kratos']]],
  ['dragutilities_38795',['DragUtilities',['../dd/de9/class_kratos_1_1_drag_utilities.html',1,'Kratos']]],
  ['drainedupwsmallstrainelement_38796',['DrainedUPwSmallStrainElement',['../db/d66/class_kratos_1_1_drained_u_pw_small_strain_element.html',1,'Kratos']]],
  ['drainedupwsmallstrainelement_3c_202_2c_203_20_3e_38797',['DrainedUPwSmallStrainElement&lt; 2, 3 &gt;',['../db/d66/class_kratos_1_1_drained_u_pw_small_strain_element.html',1,'Kratos']]],
  ['drainedupwsmallstrainelement_3c_202_2c_204_20_3e_38798',['DrainedUPwSmallStrainElement&lt; 2, 4 &gt;',['../db/d66/class_kratos_1_1_drained_u_pw_small_strain_element.html',1,'Kratos']]],
  ['drainedupwsmallstrainelement_3c_203_2c_204_20_3e_38799',['DrainedUPwSmallStrainElement&lt; 3, 4 &gt;',['../db/d66/class_kratos_1_1_drained_u_pw_small_strain_element.html',1,'Kratos']]],
  ['drainedupwsmallstrainelement_3c_203_2c_208_20_3e_38800',['DrainedUPwSmallStrainElement&lt; 3, 8 &gt;',['../db/d66/class_kratos_1_1_drained_u_pw_small_strain_element.html',1,'Kratos']]],
  ['dropletdynamicsanalysis_38801',['DropletDynamicsAnalysis',['../d3/d17/classdroplet__dynamics__analysis_1_1_droplet_dynamics_analysis.html',1,'droplet_dynamics_analysis']]],
  ['dropletdynamicselement_38802',['DropletDynamicsElement',['../db/da2/class_kratos_1_1_droplet_dynamics_element.html',1,'Kratos']]],
  ['dropletdynamicselement_3c_20kratos_3a_3atwofluidnavierstokesdata_3c_202_2c_203_20_3e_20_3e_38803',['DropletDynamicsElement&lt; Kratos::TwoFluidNavierStokesData&lt; 2, 3 &gt; &gt;',['../db/da2/class_kratos_1_1_droplet_dynamics_element.html',1,'Kratos']]],
  ['dropletdynamicselement_3c_20kratos_3a_3atwofluidnavierstokesdata_3c_203_2c_204_20_3e_20_3e_38804',['DropletDynamicsElement&lt; Kratos::TwoFluidNavierStokesData&lt; 3, 4 &gt; &gt;',['../db/da2/class_kratos_1_1_droplet_dynamics_element.html',1,'Kratos']]],
  ['dropletdynamicssolver_38805',['DropletDynamicsSolver',['../d3/d72/classdroplet__dynamics__solver_1_1_droplet_dynamics_solver.html',1,'droplet_dynamics_solver']]],
  ['druckerpragerplasticpotential_38806',['DruckerPragerPlasticPotential',['../d1/da5/class_kratos_1_1_drucker_prager_plastic_potential.html',1,'Kratos']]],
  ['druckerprageryieldsurface_38807',['DruckerPragerYieldSurface',['../d5/d72/class_kratos_1_1_drucker_prager_yield_surface.html',1,'Kratos']]],
  ['duallagrangemultiplieroperators_38808',['DualLagrangeMultiplierOperators',['../de/d18/class_kratos_1_1_dual_lagrange_multiplier_operators.html',1,'Kratos']]],
  ['duallagrangemultiplieroperators_3c_20tnumnodes_2c_20tnumnodes_20_3e_38809',['DualLagrangeMultiplierOperators&lt; TNumNodes, TNumNodes &gt;',['../de/d18/class_kratos_1_1_dual_lagrange_multiplier_operators.html',1,'Kratos']]],
  ['duallagrangemultiplieroperatorswithderivatives_38810',['DualLagrangeMultiplierOperatorsWithDerivatives',['../d2/de0/class_kratos_1_1_dual_lagrange_multiplier_operators_with_derivatives.html',1,'Kratos']]],
  ['dummyio_38811',['DummyIO',['../db/d0f/classsolver__wrappers_1_1dummy__io_1_1_dummy_i_o.html',1,'solver_wrappers::dummy_io']]],
  ['dummysolverwrapper_38812',['DummySolverWrapper',['../d9/d0b/classhelpers_1_1dummy__solver__wrapper_1_1_dummy_solver_wrapper.html',1,'helpers::dummy_solver_wrapper']]],
  ['duplicatemeshmodeler_38813',['DuplicateMeshModeler',['../de/dc7/class_kratos_1_1_duplicate_mesh_modeler.html',1,'Kratos']]],
  ['dvms_38814',['DVMS',['../dc/d6e/class_kratos_1_1_d_v_m_s.html',1,'Kratos']]],
  ['dvms_3c_20kratos_3a_3aqsvmsdata_3c_202_2c_203_20_3e_20_3e_38815',['DVMS&lt; Kratos::QSVMSData&lt; 2, 3 &gt; &gt;',['../dc/d6e/class_kratos_1_1_d_v_m_s.html',1,'Kratos']]],
  ['dvms_3c_20kratos_3a_3aqsvmsdata_3c_203_2c_204_20_3e_20_3e_38816',['DVMS&lt; Kratos::QSVMSData&lt; 3, 4 &gt; &gt;',['../dc/d6e/class_kratos_1_1_d_v_m_s.html',1,'Kratos']]],
  ['dvmsdemcoupled_38817',['DVMSDEMCoupled',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_202_2c_203_20_3e_20_3e_38818',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 2, 3 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_202_2c_204_20_3e_20_3e_38819',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 2, 4 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_202_2c_206_20_3e_20_3e_38820',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 2, 6 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_202_2c_209_20_3e_20_3e_38821',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 2, 9 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_203_2c_2027_20_3e_20_3e_38822',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 3, 27 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_203_2c_204_20_3e_20_3e_38823',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 3, 4 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_203_2c_208_20_3e_20_3e_38824',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 3, 8 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dynamicarraytypetransfer_38825',['DynamicArrayTypeTransfer',['../d9/d1c/struct_kratos_1_1_m_p_i_internals_1_1_dynamic_array_type_transfer.html',1,'Kratos::MPIInternals']]],
  ['dynamicarraytypetransfer_3c_20matrix_20_3e_38826',['DynamicArrayTypeTransfer&lt; Matrix &gt;',['../d9/d1c/struct_kratos_1_1_m_p_i_internals_1_1_dynamic_array_type_transfer.html',1,'Kratos::MPIInternals']]],
  ['dynamicarraytypetransfer_3c_20vector_20_3e_38827',['DynamicArrayTypeTransfer&lt; Vector &gt;',['../d9/d1c/struct_kratos_1_1_m_p_i_internals_1_1_dynamic_array_type_transfer.html',1,'Kratos::MPIInternals']]],
  ['dynamicscheme_38828',['DynamicScheme',['../db/d8f/class_kratos_1_1_dynamic_scheme.html',1,'Kratos']]],
  ['dynamicsmagorinsky_38829',['DynamicSmagorinsky',['../d3/d3f/classdynamic__smagorinsky__utilities_1_1_dynamic_smagorinsky.html',1,'dynamic_smagorinsky_utilities']]],
  ['dynamicsmagorinskyutils_38830',['DynamicSmagorinskyUtils',['../d7/dd1/class_kratos_1_1_dynamic_smagorinsky_utils.html',1,'Kratos']]],
  ['dynamicvms_38831',['DynamicVMS',['../de/d8f/class_kratos_1_1_dynamic_v_m_s.html',1,'Kratos']]]
];
