var searchData=
[
  ['fabricsmallstrainumatmodel_39822',['FabricSmallStrainUmatModel',['../d0/d9a/class_kratos_1_1_fabric_small_strain_umat_model.html',1,'Kratos']]],
  ['face_39823',['face',['../d5/d21/struct_c_sharp_kratos_wrapper_1_1face.html',1,'CSharpKratosWrapper']]],
  ['faceangleresponsefunction_39824',['FaceAngleResponseFunction',['../d8/d53/classresponse__functions_1_1face__angle_1_1_face_angle_response_function.html',1,'response_functions::face_angle']]],
  ['faceangleresponsefunctionutility_39825',['FaceAngleResponseFunctionUtility',['../df/dcd/class_kratos_1_1_face_angle_response_function_utility.html',1,'Kratos']]],
  ['facedatabuffer_39826',['FaceDataBuffer',['../db/d24/class_kratos_1_1_rigid_face3_d_1_1_face_data_buffer.html',1,'Kratos::RigidFace3D']]],
  ['faceheatutilities_39827',['FaceHeatUtilities',['../dc/d45/class_kratos_1_1_face_heat_utilities.html',1,'Kratos']]],
  ['facehistorydatabase_39828',['FaceHistoryDatabase',['../d5/de0/class_kratos_1_1_analytic_face_watcher_1_1_face_history_database.html',1,'Kratos::AnalyticFaceWatcher']]],
  ['faceparticleimpactdataofallparticlessingletimestep_39829',['FaceParticleImpactDataOfAllParticlesSingleTimeStep',['../d9/d99/class_kratos_1_1_analytic_particle_watcher_1_1_face_particle_impact_data_of_all_particles_single_time_step.html',1,'Kratos::AnalyticParticleWatcher']]],
  ['faceparticleimpactdataofalltimestepssingleparticle_39830',['FaceParticleImpactDataOfAllTimeStepsSingleParticle',['../de/db9/class_kratos_1_1_analytic_particle_watcher_1_1_face_particle_impact_data_of_all_time_steps_single_particle.html',1,'Kratos::AnalyticParticleWatcher']]],
  ['factory_39831',['Factory',['../d5/d9b/class_kratos_1_1_factory.html',1,'Kratos']]],
  ['factorybase_39832',['FactoryBase',['../d7/da4/class_kratos_1_1_factory_base.html',1,'Kratos']]],
  ['fast_5ffilling_5fcreator_39833',['Fast_Filling_Creator',['../d4/da4/class_kratos_1_1_fast___filling___creator.html',1,'Kratos']]],
  ['fasttransferbetweenmodelpartsprocess_39834',['FastTransferBetweenModelPartsProcess',['../d4/d39/class_kratos_1_1_fast_transfer_between_model_parts_process.html',1,'Kratos']]],
  ['fatiguevariables_39835',['FatigueVariables',['../df/d3a/struct_kratos_1_1_h_c_f_data_container_1_1_fatigue_variables.html',1,'Kratos::HCFDataContainer']]],
  ['fde_5fsolve_39836',['fde_solve',['../d2/d26/classfde__solve_1_1fde__solve.html',1,'fde_solve']]],
  ['feastconditionnumberutility_39837',['FEASTConditionNumberUtility',['../d8/da6/class_kratos_1_1_f_e_a_s_t_condition_number_utility.html',1,'Kratos']]],
  ['feasteigensystemsolver_39838',['FEASTEigensystemSolver',['../d7/de8/class_kratos_1_1_f_e_a_s_t_eigensystem_solver.html',1,'Kratos']]],
  ['features_39839',['Features',['../db/d3d/struct_kratos_1_1_constitutive_law_1_1_features.html',1,'Kratos::ConstitutiveLaw::Features'],['../da/d53/struct_kratos_1_1_shell_cross_section_1_1_features.html',1,'Kratos::ShellCrossSection::Features']]],
  ['fem_5fcoefficient_5fmatrix_5fgenerator_39840',['FEM_coefficient_matrix_generator',['../d2/d51/classode__solve_1_1_f_e_m__coefficient__matrix__generator.html',1,'ode_solve']]],
  ['fem_5ffor_5fcoupling_5fsolution_39841',['FEM_for_coupling_Solution',['../da/d28/class_main_f_e_m__for__coupling_1_1_f_e_m__for__coupling___solution.html',1,'MainFEM_for_coupling']]],
  ['fem_5ffor_5fpfem_5fcoupling_5fsolution_39842',['FEM_for_PFEM_coupling_Solution',['../d9/d43/class_main_f_e_m__for___p_f_e_m__coupling_1_1_f_e_m__for___p_f_e_m__coupling___solution.html',1,'MainFEM_for_PFEM_coupling']]],
  ['fem_5fload_5fvector_5fgenerator_39843',['FEM_load_vector_generator',['../d2/dd1/classode__solve_1_1_f_e_m__load__vector__generator.html',1,'ode_solve']]],
  ['fem_5fsolution_39844',['FEM_Solution',['../d7/d09/class_main_fem_dem_1_1_f_e_m___solution.html',1,'MainFemDem']]],
  ['femdemcoupledgidoutput_39845',['FemDemCoupledGiDOutput',['../d5/d9a/classfem__dem__coupled__gid__output_1_1_fem_dem_coupled_gi_d_output.html',1,'fem_dem_coupled_gid_output']]],
  ['femdemcouplingutilities_39846',['FEMDEMCouplingUtilities',['../de/d67/class_kratos_1_1_f_e_m_d_e_m_coupling_utilities.html',1,'Kratos']]],
  ['femdemmechanicalsolver_39847',['FemDemMechanicalSolver',['../df/d72/class_fem_dem_mechanical_solver_1_1_fem_dem_mechanical_solver.html',1,'FemDemMechanicalSolver']]],
  ['femdemparticlecreatordestructor_39848',['FemDemParticleCreatorDestructor',['../da/d27/class_f_e_m_d_e_m_particle_creator_destructor_1_1_fem_dem_particle_creator_destructor.html',1,'FEMDEMParticleCreatorDestructor']]],
  ['femdemresidualcriteria_39849',['FemDemResidualCriteria',['../d1/d03/class_kratos_1_1_fem_dem_residual_criteria.html',1,'Kratos']]],
  ['fetidynamiccoupledsolver_39850',['FetiDynamicCoupledSolver',['../d2/d30/classcoupled__solvers_1_1feti__dynamic__coupled__solver_1_1_feti_dynamic_coupled_solver.html',1,'coupled_solvers::feti_dynamic_coupled_solver']]],
  ['fetidynamiccouplingutilities_39851',['FetiDynamicCouplingUtilities',['../da/d77/class_kratos_1_1_feti_dynamic_coupling_utilities.html',1,'Kratos']]],
  ['fic_39852',['FIC',['../db/d97/class_kratos_1_1_f_i_c.html',1,'Kratos']]],
  ['fic_3c_20kratos_3a_3aficdata_3c_202_2c_203_20_3e_20_3e_39853',['FIC&lt; Kratos::FICData&lt; 2, 3 &gt; &gt;',['../db/d97/class_kratos_1_1_f_i_c.html',1,'Kratos']]],
  ['fic_3c_20kratos_3a_3aficdata_3c_202_2c_204_20_3e_20_3e_39854',['FIC&lt; Kratos::FICData&lt; 2, 4 &gt; &gt;',['../db/d97/class_kratos_1_1_f_i_c.html',1,'Kratos']]],
  ['fic_3c_20kratos_3a_3aficdata_3c_203_2c_204_20_3e_20_3e_39855',['FIC&lt; Kratos::FICData&lt; 3, 4 &gt; &gt;',['../db/d97/class_kratos_1_1_f_i_c.html',1,'Kratos']]],
  ['fic_3c_20kratos_3a_3aficdata_3c_203_2c_208_20_3e_20_3e_39856',['FIC&lt; Kratos::FICData&lt; 3, 8 &gt; &gt;',['../db/d97/class_kratos_1_1_f_i_c.html',1,'Kratos']]],
  ['fic_3c_20kratos_3a_3atimeintegratedficdata_3c_202_2c_203_20_3e_20_3e_39857',['FIC&lt; Kratos::TimeIntegratedFICData&lt; 2, 3 &gt; &gt;',['../db/d97/class_kratos_1_1_f_i_c.html',1,'Kratos']]],
  ['fic_3c_20kratos_3a_3atimeintegratedficdata_3c_203_2c_204_20_3e_20_3e_39858',['FIC&lt; Kratos::TimeIntegratedFICData&lt; 3, 4 &gt; &gt;',['../db/d97/class_kratos_1_1_f_i_c.html',1,'Kratos']]],
  ['ficdata_39859',['FICData',['../db/d08/class_kratos_1_1_f_i_c_data.html',1,'Kratos']]],
  ['ficdata_3c_20tdim_2c_20tnumnodes_2c_20true_20_3e_39860',['FICData&lt; TDim, TNumNodes, true &gt;',['../db/d08/class_kratos_1_1_f_i_c_data.html',1,'Kratos']]],
  ['ficelementvariables_39861',['FICElementVariables',['../d4/db7/struct_kratos_1_1_u_pl_small_strain_f_i_c_element_1_1_f_i_c_element_variables.html',1,'Kratos::UPlSmallStrainFICElement&lt; TDim, TNumNodes &gt;::FICElementVariables'],['../d0/d06/struct_kratos_1_1_u_pw_small_strain_f_i_c_element_1_1_f_i_c_element_variables.html',1,'Kratos::UPwSmallStrainFICElement&lt; TDim, TNumNodes &gt;::FICElementVariables']]],
  ['ficspecializedaddtimeintegratedsystem_39862',['FICSpecializedAddTimeIntegratedSystem',['../dc/da2/class_kratos_1_1_internals_1_1_f_i_c_specialized_add_time_integrated_system.html',1,'Kratos::Internals']]],
  ['ficspecializedaddtimeintegratedsystem_3c_20telementdata_2c_20false_20_3e_39863',['FICSpecializedAddTimeIntegratedSystem&lt; TElementData, false &gt;',['../db/d6e/class_kratos_1_1_internals_1_1_f_i_c_specialized_add_time_integrated_system_3_01_t_element_data_00_01false_01_4.html',1,'Kratos::Internals']]],
  ['ficspecializedaddtimeintegratedsystem_3c_20telementdata_2c_20true_20_3e_39864',['FICSpecializedAddTimeIntegratedSystem&lt; TElementData, true &gt;',['../d3/db2/class_kratos_1_1_internals_1_1_f_i_c_specialized_add_time_integrated_system_3_01_t_element_data_00_01true_01_4.html',1,'Kratos::Internals']]],
  ['field_39865',['Field',['../d1/dba/classcellular__flow__derivative__recovery__errors_1_1_field.html',1,'cellular_flow_derivative_recovery_errors']]],
  ['fieldutility_39866',['FieldUtility',['../dd/d68/class_kratos_1_1_field_utility.html',1,'Kratos']]],
  ['figure_39867',['Figure',['../da/dba/classcellular__flow__derivative__recovery__errors_1_1_figure.html',1,'cellular_flow_derivative_recovery_errors']]],
  ['file_39868',['File',['../d9/d89/class_kratos_1_1_h_d_f5_1_1_file.html',1,'Kratos::HDF5']]],
  ['fileinpututility_39869',['FileInputUtility',['../de/d38/class_kratos_1_1_file_input_utility.html',1,'Kratos']]],
  ['filelogger_39870',['FileLogger',['../de/d17/classlogger__utilities_1_1_file_logger.html',1,'logger_utilities']]],
  ['fileloggeroutput_39871',['FileLoggerOutput',['../d8/d37/class_kratos_1_1_file_logger_output.html',1,'Kratos']]],
  ['filenamedata_39872',['FileNameData',['../de/d3a/class_kratos_1_1_file_name_data_collector_1_1_file_name_data.html',1,'Kratos::FileNameDataCollector']]],
  ['filenamedatacollector_39873',['FileNameDataCollector',['../d2/dec/class_kratos_1_1_file_name_data_collector.html',1,'Kratos']]],
  ['fileserializer_39874',['FileSerializer',['../df/d60/class_kratos_1_1_file_serializer.html',1,'Kratos']]],
  ['filesystemextensions_39875',['FilesystemExtensions',['../d7/d88/class_kratos_1_1_filesystem_extensions.html',1,'Kratos']]],
  ['fillcommunicator_39876',['FillCommunicator',['../db/da6/class_kratos_1_1_fill_communicator.html',1,'Kratos']]],
  ['filter_39877',['Filter',['../dd/d99/classfilter_1_1_filter.html',1,'filter']]],
  ['filteredaccumreduction_39878',['FilteredAccumReduction',['../da/d8a/class_kratos_1_1_filtered_accum_reduction.html',1,'Kratos']]],
  ['filterfunction_39879',['FilterFunction',['../de/d20/class_kratos_1_1_filter_function.html',1,'Kratos']]],
  ['findconditionsneighboursprocess_39880',['FindConditionsNeighboursProcess',['../de/d36/class_kratos_1_1_find_conditions_neighbours_process.html',1,'Kratos']]],
  ['findcontactsinskinmodelpart_39881',['FindContactsInSkinModelPart',['../d7/dc1/class_kratos_1_1_find_contacts_in_skin_model_part.html',1,'Kratos']]],
  ['findglobalnodalelementalneighboursprocess_39882',['FindGlobalNodalElementalNeighboursProcess',['../da/d86/class_kratos_1_1_find_global_nodal_elemental_neighbours_process.html',1,'Kratos']]],
  ['findglobalnodalentityneighboursprocess_39883',['FindGlobalNodalEntityNeighboursProcess',['../d8/de0/class_kratos_1_1_find_global_nodal_entity_neighbours_process.html',1,'Kratos']]],
  ['findglobalnodalentityneighboursprocess_3c_20modelpart_3a_3aelementscontainertype_20_3e_39884',['FindGlobalNodalEntityNeighboursProcess&lt; ModelPart::ElementsContainerType &gt;',['../d8/de0/class_kratos_1_1_find_global_nodal_entity_neighbours_process.html',1,'Kratos']]],
  ['findglobalnodalneighboursprocess_39885',['FindGlobalNodalNeighboursProcess',['../da/d21/class_kratos_1_1_find_global_nodal_neighbours_process.html',1,'Kratos']]],
  ['findintersectedgeometricalobjectsprocess_39886',['FindIntersectedGeometricalObjectsProcess',['../d9/d0e/class_kratos_1_1_find_intersected_geometrical_objects_process.html',1,'Kratos']]],
  ['findintersectedgeometricalobjectswithobbcontactsearchprocess_39887',['FindIntersectedGeometricalObjectsWithOBBContactSearchProcess',['../d6/d13/class_kratos_1_1_find_intersected_geometrical_objects_with_o_b_b_contact_search_process.html',1,'Kratos']]],
  ['findintersectedgeometricalobjectswithobbprocess_39888',['FindIntersectedGeometricalObjectsWithOBBProcess',['../d1/dfd/class_kratos_1_1_find_intersected_geometrical_objects_with_o_b_b_process.html',1,'Kratos']]],
  ['findneighbourelementsofconditionsprocess_39889',['FindNeighbourElementsOfConditionsProcess',['../d2/d3f/class_kratos_1_1_find_neighbour_elements_of_conditions_process.html',1,'Kratos']]],
  ['findnodalhforrigidwallsprocess_39890',['FindNodalHForRigidWallsProcess',['../d4/dc1/class_kratos_1_1_find_nodal_h_for_rigid_walls_process.html',1,'Kratos']]],
  ['findnodalhprocess_39891',['FindNodalHProcess',['../d5/d27/class_kratos_1_1_find_nodal_h_process.html',1,'Kratos']]],
  ['findnodalhsettings_39892',['FindNodalHSettings',['../d0/dc2/struct_kratos_1_1_find_nodal_h_settings.html',1,'Kratos']]],
  ['findnodalneighboursforentitiesprocess_39893',['FindNodalNeighboursForEntitiesProcess',['../d6/de4/class_kratos_1_1_find_nodal_neighbours_for_entities_process.html',1,'Kratos']]],
  ['findnodalneighboursforentitiesprocess_3c_20modelpart_3a_3aelementscontainertype_20_3e_39894',['FindNodalNeighboursForEntitiesProcess&lt; ModelPart::ElementsContainerType &gt;',['../d6/de4/class_kratos_1_1_find_nodal_neighbours_for_entities_process.html',1,'Kratos']]],
  ['findnodalneighboursprocess_39895',['FindNodalNeighboursProcess',['../de/ddc/class_kratos_1_1_find_nodal_neighbours_process.html',1,'Kratos']]],
  ['findnodalneighbourssurfaceprocess_39896',['FindNodalNeighboursSurfaceProcess',['../d7/dcf/class_kratos_1_1_find_nodal_neighbours_surface_process.html',1,'Kratos']]],
  ['findtriplepoint_39897',['FindTriplePoint',['../d8/d4a/class_kratos_1_1_find_triple_point.html',1,'Kratos']]],
  ['finitedifferencebodyfitteddragshapesensitivityanalysis_39898',['FiniteDifferenceBodyFittedDragShapeSensitivityAnalysis',['../d2/d01/classfinite__difference__sensitivity__utilities_1_1_finite_difference_body_fitted_drag_shape_sensitivity_analysis.html',1,'finite_difference_sensitivity_utilities']]],
  ['finitedifferenceutility_39899',['FiniteDifferenceUtility',['../dc/d83/class_kratos_1_1_finite_difference_utility.html',1,'Kratos']]],
  ['finitedifferencevelocitypressurenormsquareshapesensitivityanalysis_39900',['FiniteDifferenceVelocityPressureNormSquareShapeSensitivityAnalysis',['../d5/d98/classfinite__difference__sensitivity__utilities_1_1_finite_difference_velocity_pressure_norm_square_shape_sensitivity_analysis.html',1,'finite_difference_sensitivity_utilities']]],
  ['finitestrainisotropicplasticityfactory_39901',['FiniteStrainIsotropicPlasticityFactory',['../d4/d3f/class_kratos_1_1_finite_strain_isotropic_plasticity_factory.html',1,'Kratos']]],
  ['finitestrainkinematicplasticityfactory_39902',['FiniteStrainKinematicPlasticityFactory',['../d4/df4/class_kratos_1_1_finite_strain_kinematic_plasticity_factory.html',1,'Kratos']]],
  ['firstderivativesgradientcalculation_39903',['FirstDerivativesGradientCalculation',['../d8/dc4/struct_kratos_1_1_measurement_residual_response_function_utilities_1_1_first_derivatives_gradient_calculation.html',1,'Kratos::MeasurementResidualResponseFunctionUtilities']]],
  ['firstorderscalarvariable_39904',['FirstOrderScalarVariable',['../d7/da1/struct_kratos_1_1_first_order_scalar_variable.html',1,'Kratos']]],
  ['fixedmeshaleutilities_39905',['FixedMeshALEUtilities',['../db/da3/class_kratos_1_1_fixed_mesh_a_l_e_utilities.html',1,'Kratos']]],
  ['fixedpressure2d_39906',['FixedPressure2D',['../df/d9d/class_kratos_1_1_fixed_pressure2_d.html',1,'Kratos']]],
  ['fixedpressure3d_39907',['FixedPressure3D',['../d4/d14/class_kratos_1_1_fixed_pressure3_d.html',1,'Kratos']]],
  ['fixedsizememorypool_39908',['FixedSizeMemoryPool',['../d9/d84/class_kratos_1_1_fixed_size_memory_pool.html',1,'Kratos']]],
  ['fixedvelocity2d_39909',['FixedVelocity2D',['../d4/dd0/class_kratos_1_1_fixed_velocity2_d.html',1,'Kratos']]],
  ['fixedvelocity3d_39910',['FixedVelocity3D',['../dc/ddb/class_kratos_1_1_fixed_velocity3_d.html',1,'Kratos']]],
  ['fixfreevelocityonnodesprocess_39911',['FixFreeVelocityOnNodesProcess',['../d9/df0/class_kratos_1_1_fix_free_velocity_on_nodes_process.html',1,'Kratos']]],
  ['fixscalardofprocess_39912',['FixScalarDofProcess',['../db/dd9/class_kratos_1_1_fix_scalar_dof_process.html',1,'Kratos']]],
  ['fixscalarpfemdofprocess_39913',['FixScalarPfemDofProcess',['../d1/d86/class_kratos_1_1_fix_scalar_pfem_dof_process.html',1,'Kratos']]],
  ['fixscalarvariableprocess_39914',['FixScalarVariableProcess',['../d6/dcf/classfix__scalar__variable__process_1_1_fix_scalar_variable_process.html',1,'fix_scalar_variable_process']]],
  ['fixvectorvariableprocess_39915',['FixVectorVariableProcess',['../d4/d6b/classfix__vector__variable__process_1_1_fix_vector_variable_process.html',1,'fix_vector_variable_process']]],
  ['flags_39916',['Flags',['../d9/d4f/class_kratos_1_1_flags.html',1,'Kratos']]],
  ['flowerwrapper_39917',['FLOWerWrapper',['../d1/dc3/classsolver__wrappers_1_1external_1_1flower__wrapper_1_1_f_l_o_wer_wrapper.html',1,'solver_wrappers::external::flower_wrapper']]],
  ['flowoutputprocess_39918',['FlowOutputProcess',['../d7/de3/classflow__output__process_1_1_flow_output_process.html',1,'flow_output_process']]],
  ['flowratesliputility_39919',['FlowRateSlipUtility',['../d3/d66/class_kratos_1_1_flow_rate_slip_utility.html',1,'Kratos']]],
  ['flowratesliputility_3c_20localsystemmatrixtype_2c_20localsystemvectortype_2c_20double_20_3e_39920',['FlowRateSlipUtility&lt; LocalSystemMatrixType, LocalSystemVectorType, double &gt;',['../d3/d66/class_kratos_1_1_flow_rate_slip_utility.html',1,'Kratos']]],
  ['flowrule_39921',['FlowRule',['../d8/dc0/class_kratos_1_1_flow_rule.html',1,'Kratos']]],
  ['flowstationaritycheck_39922',['FlowStationarityCheck',['../d5/df0/class_kratos_1_1_flow_stationarity_check.html',1,'Kratos']]],
  ['fluid2dgls_5fexpl_39923',['Fluid2DGLS_expl',['../d8/d5c/class_kratos_1_1_fluid2_d_g_l_s__expl.html',1,'Kratos']]],
  ['fluid_5fphase_5fpfem2_5fexplicit_5fstrategy_39924',['Fluid_Phase_PFEM2_Explicit_Strategy',['../d8/d66/class_kratos_1_1_fluid___phase___p_f_e_m2___explicit___strategy.html',1,'Kratos']]],
  ['fluidadjointelement_39925',['FluidAdjointElement',['../d5/dc2/class_kratos_1_1_fluid_adjoint_element.html',1,'Kratos']]],
  ['fluidadjointelement_3c_202_2c_203_2c_20kratos_3a_3aqsvmsadjointelementdata_3c_202_2c_203_20_3e_20_3e_39926',['FluidAdjointElement&lt; 2, 3, Kratos::QSVMSAdjointElementData&lt; 2, 3 &gt; &gt;',['../d5/dc2/class_kratos_1_1_fluid_adjoint_element.html',1,'Kratos']]],
  ['fluidadjointelement_3c_202_2c_204_2c_20kratos_3a_3aqsvmsadjointelementdata_3c_202_2c_204_20_3e_20_3e_39927',['FluidAdjointElement&lt; 2, 4, Kratos::QSVMSAdjointElementData&lt; 2, 4 &gt; &gt;',['../d5/dc2/class_kratos_1_1_fluid_adjoint_element.html',1,'Kratos']]],
  ['fluidadjointelement_3c_203_2c_204_2c_20kratos_3a_3aqsvmsadjointelementdata_3c_203_2c_204_20_3e_20_3e_39928',['FluidAdjointElement&lt; 3, 4, Kratos::QSVMSAdjointElementData&lt; 3, 4 &gt; &gt;',['../d5/dc2/class_kratos_1_1_fluid_adjoint_element.html',1,'Kratos']]],
  ['fluidadjointelement_3c_203_2c_208_2c_20kratos_3a_3aqsvmsadjointelementdata_3c_203_2c_208_20_3e_20_3e_39929',['FluidAdjointElement&lt; 3, 8, Kratos::QSVMSAdjointElementData&lt; 3, 8 &gt; &gt;',['../d5/dc2/class_kratos_1_1_fluid_adjoint_element.html',1,'Kratos']]],
  ['fluidadjointsliputilities_39930',['FluidAdjointSlipUtilities',['../da/d00/class_kratos_1_1_fluid_adjoint_slip_utilities.html',1,'Kratos']]],
  ['fluidadjointtestutilities_39931',['FluidAdjointTestUtilities',['../d8/da3/class_kratos_1_1_fluid_adjoint_test_utilities.html',1,'Kratos']]],
  ['fluidadjointutilities_39932',['FluidAdjointUtilities',['../da/da9/class_kratos_1_1_fluid_adjoint_utilities.html',1,'Kratos']]],
  ['fluidauxiliaryutilities_39933',['FluidAuxiliaryUtilities',['../d8/d98/class_kratos_1_1_fluid_auxiliary_utilities.html',1,'Kratos']]],
  ['fluidcalculationutilities_39934',['FluidCalculationUtilities',['../dd/d43/class_kratos_1_1_fluid_calculation_utilities.html',1,'Kratos']]],
  ['fluidcharacteristicnumbersutilities_39935',['FluidCharacteristicNumbersUtilities',['../dd/d50/class_kratos_1_1_fluid_characteristic_numbers_utilities.html',1,'Kratos']]],
  ['fluidchimeraanalysis_39936',['FluidChimeraAnalysis',['../d4/ddc/classfluid__chimera__analysis_1_1_fluid_chimera_analysis.html',1,'fluid_chimera_analysis']]],
  ['fluidconstitutivelaw_39937',['FluidConstitutiveLaw',['../da/d17/class_kratos_1_1_fluid_constitutive_law.html',1,'Kratos']]],
  ['fluidcoupleddemanalysisstage_39938',['FluidCoupledDEMAnalysisStage',['../db/d7a/classfluid__coupled___d_e_m__analysis_1_1_fluid_coupled_d_e_m_analysis_stage.html',1,'fluid_coupled_DEM_analysis']]],
  ['fluiddemsolver_39939',['FluidDEMSolver',['../d8/d2f/classfluid___d_e_m__coupling__solver_1_1_fluid_d_e_m_solver.html',1,'fluid_DEM_coupling_solver']]],
  ['fluiddynamicsanalysis_39940',['FluidDynamicsAnalysis',['../da/da4/classfluid__dynamics__analysis_1_1_fluid_dynamics_analysis.html',1,'fluid_dynamics_analysis']]],
  ['fluiddynamicsanalysisrve_39941',['FluidDynamicsAnalysisRve',['../d6/d22/classfluid__dynamics__analysis__rve_1_1_fluid_dynamics_analysis_rve.html',1,'fluid_dynamics_analysis_rve']]],
  ['fluiddynamicsanalysisrve_39942',['FluidDynamicsAnalysisRVE',['../d2/df7/classfluid__dynamics__analysis__rve_1_1_fluid_dynamics_analysis_r_v_e.html',1,'fluid_dynamics_analysis_rve']]],
  ['fluiddynamicshydraulicsanalysis_39943',['FluidDynamicsHydraulicsAnalysis',['../d9/dce/classfluid__dynamics__hydraulic__analysis_1_1_fluid_dynamics_hydraulics_analysis.html',1,'fluid_dynamics_hydraulic_analysis']]],
  ['fluiddynamicswrapper_39944',['FluidDynamicsWrapper',['../da/d40/classsolver__wrappers_1_1kratos_1_1fluid__dynamics__wrapper_1_1_fluid_dynamics_wrapper.html',1,'solver_wrappers::kratos::fluid_dynamics_wrapper']]],
  ['fluidelement_39945',['FluidElement',['../dd/d83/class_kratos_1_1_fluid_element.html',1,'Kratos']]],
  ['fluidelementdata_39946',['FluidElementData',['../d0/dfc/class_kratos_1_1_fluid_element_data.html',1,'Kratos']]],
  ['fluidelementdata_3c_20tdim_2c_20tnumnodes_2c_20false_20_3e_39947',['FluidElementData&lt; TDim, TNumNodes, false &gt;',['../d0/dfc/class_kratos_1_1_fluid_element_data.html',1,'Kratos']]],
  ['fluidelementdata_3c_20tdim_2c_20tnumnodes_2c_20true_20_3e_39948',['FluidElementData&lt; TDim, TNumNodes, true &gt;',['../d0/dfc/class_kratos_1_1_fluid_element_data.html',1,'Kratos']]],
  ['fluidelementtimeintegrationdetail_39949',['FluidElementTimeIntegrationDetail',['../da/da8/class_kratos_1_1_internals_1_1_fluid_element_time_integration_detail.html',1,'Kratos::Internals']]],
  ['fluidelementtimeintegrationdetail_3c_20telementdata_2c_20false_20_3e_39950',['FluidElementTimeIntegrationDetail&lt; TElementData, false &gt;',['../d5/d72/class_kratos_1_1_internals_1_1_fluid_element_time_integration_detail_3_01_t_element_data_00_01false_01_4.html',1,'Kratos::Internals']]],
  ['fluidelementtimeintegrationdetail_3c_20telementdata_2c_20true_20_3e_39951',['FluidElementTimeIntegrationDetail&lt; TElementData, true &gt;',['../da/d28/class_kratos_1_1_internals_1_1_fluid_element_time_integration_detail_3_01_t_element_data_00_01true_01_4.html',1,'Kratos::Internals']]],
  ['fluidelementutilities_39952',['FluidElementUtilities',['../df/dc5/class_kratos_1_1_fluid_element_utilities.html',1,'Kratos']]],
  ['fluidfieldutility_39953',['FluidFieldUtility',['../d4/d28/class_kratos_1_1_fluid_field_utility.html',1,'Kratos']]],
  ['fluidfractionfieldutility_39954',['FluidFractionFieldUtility',['../da/daa/classswimming___d_e_m__procedures_1_1_fluid_fraction_field_utility.html',1,'swimming_DEM_procedures']]],
  ['fluidfractiontestanalysis_39955',['FluidFractionTestAnalysis',['../da/dcc/classfluid__fraction__test__analysis_1_1_fluid_fraction_test_analysis.html',1,'fluid_fraction_test_analysis']]],
  ['fluidfractiontestsolver_39956',['FluidFractionTestSolver',['../da/d85/classfluid__fraction__test__solver_1_1_fluid_fraction_test_solver.html',1,'fluid_fraction_test_solver']]],
  ['fluidhdf5loader_39957',['FluidHDF5Loader',['../d5/d8e/classhdf5__io__tools_1_1_fluid_h_d_f5_loader.html',1,'hdf5_io_tools']]],
  ['fluidhdf5loaderpid_39958',['FluidHDF5LoaderPID',['../d5/d01/class_p_i_d_1_1hdf5__io__tools___p_i_d_1_1_fluid_h_d_f5_loader_p_i_d.html',1,'PID::hdf5_io_tools_PID']]],
  ['fluidmesher_39959',['FluidMesher',['../d9/dc0/classfluid__mesher_1_1_fluid_mesher.html',1,'fluid_mesher']]],
  ['fluidmeshingdomain_39960',['FluidMeshingDomain',['../dd/daa/classfluid__meshing__domain_1_1_fluid_meshing_domain.html',1,'fluid_meshing_domain']]],
  ['fluidmeshingstrategy_39961',['FluidMeshingStrategy',['../d1/d46/classfluid__meshing__strategy_1_1_fluid_meshing_strategy.html',1,'fluid_meshing_strategy']]],
  ['fluidmeshutilities_39962',['FluidMeshUtilities',['../d7/d13/class_kratos_1_1_fluid_mesh_utilities.html',1,'Kratos']]],
  ['fluidrefiningmesher_39963',['FluidRefiningMesher',['../df/d6e/classfluid__refining__mesher_1_1_fluid_refining_mesher.html',1,'fluid_refining_mesher']]],
  ['fluidsolver_39964',['FluidSolver',['../d8/d58/classfluid__solver_1_1_fluid_solver.html',1,'fluid_solver']]],
  ['fluidsolverconfiguration_39965',['FluidSolverConfiguration',['../da/d29/class_project_parameters_1_1_fluid_solver_configuration.html',1,'ProjectParameters']]],
  ['fluidtestutilities_39966',['FluidTestUtilities',['../d2/d42/class_kratos_1_1_fluid_test_utilities.html',1,'Kratos']]],
  ['fluidtransportanalysis_39967',['FluidTransportAnalysis',['../d1/d0a/classfluid__transport__analysis_1_1_fluid_transport_analysis.html',1,'fluid_transport_analysis']]],
  ['fluidtransportcouplinganalysis_39968',['FluidTransportCouplingAnalysis',['../d0/da1/classfluid__transport__coupling__analysis_1_1_fluid_transport_coupling_analysis.html',1,'fluid_transport_coupling_analysis']]],
  ['fluidtransportreplacesolver_39969',['FluidTransportReplaceSolver',['../dd/d3a/classfluid__transport__replace__solver_1_1_fluid_transport_replace_solver.html',1,'fluid_transport_replace_solver']]],
  ['fluidtransportsolver_39970',['FluidTransportSolver',['../d3/ddc/classfluid__transport__solver_1_1_fluid_transport_solver.html',1,'fluid_transport_solver']]],
  ['fluxcondition_39971',['FluxCondition',['../d1/d18/class_kratos_1_1_flux_condition.html',1,'Kratos']]],
  ['fluxcondition_3c_202_20_3e_39972',['FluxCondition&lt; 2 &gt;',['../d1/d18/class_kratos_1_1_flux_condition.html',1,'Kratos']]],
  ['fluxcondition_3c_203_20_3e_39973',['FluxCondition&lt; 3 &gt;',['../d1/d18/class_kratos_1_1_flux_condition.html',1,'Kratos']]],
  ['fluxcondition_3c_204_20_3e_39974',['FluxCondition&lt; 4 &gt;',['../d1/d18/class_kratos_1_1_flux_condition.html',1,'Kratos']]],
  ['fluxcorrectedshallowwaterscheme_39975',['FluxCorrectedShallowWaterScheme',['../d2/d8f/class_kratos_1_1_flux_corrected_shallow_water_scheme.html',1,'Kratos']]],
  ['fluxcorrectedtransportconvectionprocess_39976',['FluxCorrectedTransportConvectionProcess',['../d0/d3a/class_kratos_1_1_flux_corrected_transport_convection_process.html',1,'Kratos']]],
  ['fluxlimiter_39977',['FluxLimiter',['../d5/d59/class_kratos_1_1_flux_limiter.html',1,'Kratos']]],
  ['fluxlimiter_3c_20localsystemvectortype_20_3e_39978',['FluxLimiter&lt; LocalSystemVectorType &gt;',['../d5/d59/class_kratos_1_1_flux_limiter.html',1,'Kratos']]],
  ['fnv1a32hash_39979',['FNV1a32Hash',['../d4/d70/class_kratos_1_1_f_n_v1a32_hash.html',1,'Kratos']]],
  ['fnv1a64hash_39980',['FNV1a64Hash',['../de/d2f/class_kratos_1_1_f_n_v1a64_hash.html',1,'Kratos']]],
  ['footingproblemprocess_39981',['FootingProblemProcess',['../d9/da5/classfooting__problem__process_1_1_footing_problem_process.html',1,'footing_problem_process']]],
  ['forceandtorqueutils_39982',['ForceAndTorqueUtils',['../db/de2/class_kratos_1_1_force_and_torque_utils.html',1,'Kratos']]],
  ['formfindingmechanicalsolver_39983',['FormfindingMechanicalSolver',['../d9/d3e/classstructural__mechanics__formfinding__solver_1_1_formfinding_mechanical_solver.html',1,'structural_mechanics_formfinding_solver']]],
  ['formfindingstrategy_39984',['FormfindingStrategy',['../d0/d57/class_kratos_1_1_formfinding_strategy.html',1,'Kratos']]],
  ['formulationparameters_39985',['FormulationParameters',['../d2/dfd/classsymbolic__generation_1_1compressible__navier__stokes_1_1src_1_1symbolic__parameters_1_1_formulation_parameters.html',1,'symbolic_generation::compressible_navier_stokes::src::symbolic_parameters']]],
  ['forwardeulerscheme_39986',['ForwardEulerScheme',['../d3/da4/class_kratos_1_1_forward_euler_scheme.html',1,'Kratos']]],
  ['fracstepsolver_39987',['FracStepSolver',['../d1/d0b/classfrac__step__solver_q_1_1_frac_step_solver.html',1,'frac_step_solverQ']]],
  ['fracstepstrategy_39988',['FracStepStrategy',['../df/dd4/class_kratos_1_1_frac_step_strategy.html',1,'Kratos']]],
  ['fractionalstep_39989',['FractionalStep',['../dc/d81/class_kratos_1_1_fractional_step.html',1,'Kratos']]],
  ['fractionalstep_3c_202_20_3e_39990',['FractionalStep&lt; 2 &gt;',['../dc/d81/class_kratos_1_1_fractional_step.html',1,'Kratos']]],
  ['fractionalstep_3c_203_20_3e_39991',['FractionalStep&lt; 3 &gt;',['../dc/d81/class_kratos_1_1_fractional_step.html',1,'Kratos']]],
  ['fractionalstepdiscontinuous_39992',['FractionalStepDiscontinuous',['../d0/dfa/class_kratos_1_1_fractional_step_discontinuous.html',1,'Kratos']]],
  ['fractionalstepdiscontinuous_3c_202_20_3e_39993',['FractionalStepDiscontinuous&lt; 2 &gt;',['../d0/dfa/class_kratos_1_1_fractional_step_discontinuous.html',1,'Kratos']]],
  ['fractionalstepdiscontinuous_3c_203_20_3e_39994',['FractionalStepDiscontinuous&lt; 3 &gt;',['../d0/dfa/class_kratos_1_1_fractional_step_discontinuous.html',1,'Kratos']]],
  ['fractionalstepkbasedwallcondition_39995',['FractionalStepKBasedWallCondition',['../df/d1f/class_kratos_1_1_fractional_step_k_based_wall_condition.html',1,'Kratos']]],
  ['fractionalstepkbasedwallcondition_3c_202_2c_202_20_3e_39996',['FractionalStepKBasedWallCondition&lt; 2, 2 &gt;',['../df/d1f/class_kratos_1_1_fractional_step_k_based_wall_condition.html',1,'Kratos']]],
  ['fractionalstepkbasedwallcondition_3c_203_2c_203_20_3e_39997',['FractionalStepKBasedWallCondition&lt; 3, 3 &gt;',['../df/d1f/class_kratos_1_1_fractional_step_k_based_wall_condition.html',1,'Kratos']]],
  ['fractionalstepkepsilonransformulation_39998',['FractionalStepKEpsilonRansFormulation',['../d0/dbc/classfractional__step__k__epsilon__rans__formulation_1_1_fractional_step_k_epsilon_rans_formulation.html',1,'fractional_step_k_epsilon_rans_formulation']]],
  ['fractionalstepkomegaransformulation_39999',['FractionalStepKOmegaRansFormulation',['../dd/ddb/classfractional__step__k__omega__rans__formulation_1_1_fractional_step_k_omega_rans_formulation.html',1,'fractional_step_k_omega_rans_formulation']]],
  ['fractionalstepkomegasstransformulation_40000',['FractionalStepKOmegaSSTRansFormulation',['../d9/d5d/classfractional__step__k__omega__sst__rans__formulation_1_1_fractional_step_k_omega_s_s_t_rans_formulation.html',1,'fractional_step_k_omega_sst_rans_formulation']]],
  ['fractionalsteppfem22d_40001',['FractionalStepPFEM22D',['../d7/dfa/class_kratos_1_1_fractional_step_p_f_e_m22_d.html',1,'Kratos']]],
  ['fractionalsteppfem23d_40002',['FractionalStepPFEM23D',['../d3/d13/class_kratos_1_1_fractional_step_p_f_e_m23_d.html',1,'Kratos']]],
  ['fractionalstepsettings_40003',['FractionalStepSettings',['../d3/ded/class_kratos_1_1_fractional_step_settings.html',1,'Kratos']]],
  ['fractionalstepsettingsforchimera_40004',['FractionalStepSettingsForChimera',['../db/d93/class_kratos_1_1_fractional_step_settings_for_chimera.html',1,'Kratos']]],
  ['fractionalstepsettingsperiodic_40005',['FractionalStepSettingsPeriodic',['../dd/d93/class_kratos_1_1_fractional_step_settings_periodic.html',1,'Kratos']]],
  ['fractionalstepstrategy_40006',['FractionalStepStrategy',['../d2/d4a/class_kratos_1_1_fractional_step_strategy.html',1,'Kratos']]],
  ['fractionalstepstrategyforchimera_40007',['FractionalStepStrategyForChimera',['../d6/d81/class_kratos_1_1_fractional_step_strategy_for_chimera.html',1,'Kratos']]],
  ['fractionalstepvelocitypressureransformulation_40008',['FractionalStepVelocityPressureRansFormulation',['../d6/d54/classfractional__step__velocity__pressure__rans__formulation_1_1_fractional_step_velocity_pressure_rans_formulation.html',1,'fractional_step_velocity_pressure_rans_formulation']]],
  ['fracturepoint_40009',['FracturePoint',['../de/dca/struct_kratos_1_1_fracture_propagation2_d_utilities_1_1_fracture_point.html',1,'Kratos::FracturePropagation2DUtilities::FracturePoint'],['../d2/dc3/struct_kratos_1_1_fracture_propagation3_d_utilities_1_1_fracture_point.html',1,'Kratos::FracturePropagation3DUtilities::FracturePoint']]],
  ['fracturepropagation2dutilities_40010',['FracturePropagation2DUtilities',['../d2/dbd/class_kratos_1_1_fracture_propagation2_d_utilities.html',1,'Kratos']]],
  ['fracturepropagation3dutilities_40011',['FracturePropagation3DUtilities',['../d2/d76/class_kratos_1_1_fracture_propagation3_d_utilities.html',1,'Kratos']]],
  ['fracturepropagationutility_40012',['FracturePropagationUtility',['../dc/d16/classporomechanics__fracture__propagation__utility_1_1_fracture_propagation_utility.html',1,'poromechanics_fracture_propagation_utility']]],
  ['freescalardofprocess_40013',['FreeScalarDofProcess',['../da/dce/class_kratos_1_1_free_scalar_dof_process.html',1,'Kratos']]],
  ['freescalarpfemdofprocess_40014',['FreeScalarPfemDofProcess',['../d6/ddd/class_kratos_1_1_free_scalar_pfem_dof_process.html',1,'Kratos']]],
  ['freesurfaceanalysis_40015',['FreeSurfaceAnalysis',['../de/dc9/classfree__surface__analysis_1_1_free_surface_analysis.html',1,'free_surface_analysis']]],
  ['freesurfacecondition_40016',['FreeSurfaceCondition',['../da/d4d/class_kratos_1_1_free_surface_condition.html',1,'Kratos']]],
  ['freesurfacecondition_3c_202_2c_202_20_3e_40017',['FreeSurfaceCondition&lt; 2, 2 &gt;',['../da/d4d/class_kratos_1_1_free_surface_condition.html',1,'Kratos']]],
  ['freesurfacecondition_3c_203_2c_203_20_3e_40018',['FreeSurfaceCondition&lt; 3, 3 &gt;',['../da/d4d/class_kratos_1_1_free_surface_condition.html',1,'Kratos']]],
  ['freesurfacecondition_3c_203_2c_204_20_3e_40019',['FreeSurfaceCondition&lt; 3, 4 &gt;',['../da/d4d/class_kratos_1_1_free_surface_condition.html',1,'Kratos']]],
  ['frictionallaw_40020',['FrictionalLaw',['../d6/d0e/class_kratos_1_1_frictional_law.html',1,'Kratos']]],
  ['frictionallawwithderivative_40021',['FrictionalLawWithDerivative',['../d6/d6d/class_kratos_1_1_frictional_law_with_derivative.html',1,'Kratos']]],
  ['frictionallawwithderivative_3c_20tdim_2c_20tnumnodes_2c_20tnormalvariation_2c_20tnumnodes_20_3e_40022',['FrictionalLawWithDerivative&lt; TDim, TNumNodes, TNormalVariation, TNumNodes &gt;',['../d6/d6d/class_kratos_1_1_frictional_law_with_derivative.html',1,'Kratos']]],
  ['frictionalviscoplastic2dlaw_40023',['FrictionalViscoplastic2DLaw',['../d9/d05/class_kratos_1_1_frictional_viscoplastic2_d_law.html',1,'Kratos']]],
  ['frictionalviscoplastic3dlaw_40024',['FrictionalViscoplastic3DLaw',['../d1/de8/class_kratos_1_1_frictional_viscoplastic3_d_law.html',1,'Kratos']]],
  ['frictionalviscoplastictemperaturedependent2dlaw_40025',['FrictionalViscoplasticTemperatureDependent2DLaw',['../db/dc9/class_kratos_1_1_frictional_viscoplastic_temperature_dependent2_d_law.html',1,'Kratos']]],
  ['frictionalviscoplastictemperaturedependent3dlaw_40026',['FrictionalViscoplasticTemperatureDependent3DLaw',['../d2/d48/class_kratos_1_1_frictional_viscoplastic_temperature_dependent3_d_law.html',1,'Kratos']]],
  ['frictionlaw_40027',['FrictionLaw',['../d0/de5/class_kratos_1_1_friction_law.html',1,'Kratos']]],
  ['frictionlawsfactory_40028',['FrictionLawsFactory',['../d1/d3d/class_kratos_1_1_friction_laws_factory.html',1,'Kratos']]],
  ['frictionlawvariables_40029',['FrictionLawVariables',['../db/d12/struct_kratos_1_1_friction_law_1_1_friction_law_variables.html',1,'Kratos::FrictionLaw']]],
  ['fromjsoncheckresultprocess_40030',['FromJsonCheckResultProcess',['../db/dc9/classfrom__json__check__result__process_1_1_from_json_check_result_process.html',1,'from_json_check_result_process']]],
  ['fromjsoncheckresultprocess_40031',['FromJSONCheckResultProcess',['../d6/d22/class_kratos_1_1_from_j_s_o_n_check_result_process.html',1,'Kratos']]],
  ['fsgeneralizedwallcondition_40032',['FSGeneralizedWallCondition',['../d3/d96/class_kratos_1_1_f_s_generalized_wall_condition.html',1,'Kratos']]],
  ['fsgeneralizedwallcondition_3c_202_2c_202_20_3e_40033',['FSGeneralizedWallCondition&lt; 2, 2 &gt;',['../d3/d96/class_kratos_1_1_f_s_generalized_wall_condition.html',1,'Kratos']]],
  ['fsgeneralizedwallcondition_3c_203_2c_203_20_3e_40034',['FSGeneralizedWallCondition&lt; 3, 3 &gt;',['../d3/d96/class_kratos_1_1_f_s_generalized_wall_condition.html',1,'Kratos']]],
  ['fsianalysis_40035',['FsiAnalysis',['../d7/d4a/classfsi__analysis_1_1_fsi_analysis.html',1,'fsi_analysis']]],
  ['fsianalysis_40036',['FSIAnalysis',['../d8/df4/classfsi__analysis_1_1_f_s_i_analysis.html',1,'fsi_analysis']]],
  ['fsicouplinginterface_40037',['FSICouplingInterface',['../d5/dee/classfsi__coupling__interface_1_1_f_s_i_coupling_interface.html',1,'fsi_coupling_interface']]],
  ['fsiutils_40038',['FSIUtils',['../d0/d2d/class_kratos_1_1_f_s_i_utils.html',1,'Kratos']]],
  ['fsperiodiccondition_40039',['FSPeriodicCondition',['../d9/dcc/class_kratos_1_1_f_s_periodic_condition.html',1,'Kratos']]],
  ['fsperiodiccondition_3c_202_20_3e_40040',['FSPeriodicCondition&lt; 2 &gt;',['../d9/dcc/class_kratos_1_1_f_s_periodic_condition.html',1,'Kratos']]],
  ['fsperiodiccondition_3c_203_20_3e_40041',['FSPeriodicCondition&lt; 3 &gt;',['../d9/dcc/class_kratos_1_1_f_s_periodic_condition.html',1,'Kratos']]],
  ['fswernerwenglewallcondition_40042',['FSWernerWengleWallCondition',['../dc/da6/class_kratos_1_1_f_s_werner_wengle_wall_condition.html',1,'Kratos']]],
  ['fswernerwenglewallcondition_3c_202_2c_202_20_3e_40043',['FSWernerWengleWallCondition&lt; 2, 2 &gt;',['../dc/da6/class_kratos_1_1_f_s_werner_wengle_wall_condition.html',1,'Kratos']]],
  ['fswernerwenglewallcondition_3c_203_2c_203_20_3e_40044',['FSWernerWengleWallCondition&lt; 3, 3 &gt;',['../dc/da6/class_kratos_1_1_f_s_werner_wengle_wall_condition.html',1,'Kratos']]],
  ['functional_40045',['Functional',['../d1/d34/classhinsberg__optimization_1_1_functional.html',1,'hinsberg_optimization.Functional'],['../d0/dd7/classhinsberg__optimization__3_1_1_functional.html',1,'hinsberg_optimization_3.Functional'],['../d9/d48/classhinsberg__optimization__4_1_1_functional.html',1,'hinsberg_optimization_4.Functional']]],
  ['functionparser_40046',['FunctionParser',['../d3/d8f/class_kratos_1_1_function_parser.html',1,'Kratos']]]
];
