var searchData=
[
  ['nanoparticle_41773',['NanoParticle',['../d5/d02/class_kratos_1_1_nano_particle.html',1,'Kratos']]],
  ['navier_5fslip_5fmonolithic_5fhelper_41774',['navier_slip_monolithic_helper',['../dd/dd2/classapply__wall__law__process_1_1_apply_wall_law_process_1_1navier__slip__monolithic__helper.html',1,'apply_wall_law_process::ApplyWallLawProcess']]],
  ['navierslipwalllaw_41775',['NavierSlipWallLaw',['../dc/d45/class_kratos_1_1_navier_slip_wall_law.html',1,'Kratos']]],
  ['navierstokes_41776',['NavierStokes',['../d6/d90/class_kratos_1_1_navier_stokes.html',1,'Kratos']]],
  ['navierstokes_3c_202_20_3e_41777',['NavierStokes&lt; 2 &gt;',['../d6/d90/class_kratos_1_1_navier_stokes.html',1,'Kratos']]],
  ['navierstokes_3c_203_20_3e_41778',['NavierStokes&lt; 3 &gt;',['../d6/d90/class_kratos_1_1_navier_stokes.html',1,'Kratos']]],
  ['navierstokes_3c_20tdim_2c_20tdim_2b1_20_3e_41779',['NavierStokes&lt; TDim, TDim+1 &gt;',['../d6/d90/class_kratos_1_1_navier_stokes.html',1,'Kratos']]],
  ['navierstokesalefluidsolver_41780',['NavierStokesAleFluidSolver',['../d4/d19/classnavier__stokes__ale__fluid__solver_1_1_navier_stokes_ale_fluid_solver.html',1,'navier_stokes_ale_fluid_solver']]],
  ['navierstokescompressibleexplicitsolver_41781',['NavierStokesCompressibleExplicitSolver',['../d4/d41/classnavier__stokes__compressible__explicit__solver_1_1_navier_stokes_compressible_explicit_solver.html',1,'navier_stokes_compressible_explicit_solver']]],
  ['navierstokesembeddedmonolithicsolver_41782',['NavierStokesEmbeddedMonolithicSolver',['../d1/d59/classnavier__stokes__embedded__solver_1_1_navier_stokes_embedded_monolithic_solver.html',1,'navier_stokes_embedded_solver']]],
  ['navierstokesmonolithicsolver_41783',['NavierStokesMonolithicSolver',['../d3/dee/classnavier__stokes__monolithic__solver_1_1_navier_stokes_monolithic_solver.html',1,'navier_stokes_monolithic_solver']]],
  ['navierstokesmpiembeddedmonolithicsolver_41784',['NavierStokesMPIEmbeddedMonolithicSolver',['../d7/d28/classtrilinos__navier__stokes__embedded__solver_1_1_navier_stokes_m_p_i_embedded_monolithic_solver.html',1,'trilinos_navier_stokes_embedded_solver']]],
  ['navierstokesmpitwofluidssolver_41785',['NavierStokesMPITwoFluidsSolver',['../d3/d4b/classtrilinos__navier__stokes__two__fluids__solver_1_1_navier_stokes_m_p_i_two_fluids_solver.html',1,'trilinos_navier_stokes_two_fluids_solver']]],
  ['navierstokesp2p1continuouswallcondition_41786',['NavierStokesP2P1ContinuousWallCondition',['../d7/d04/class_kratos_1_1_navier_stokes_p2_p1_continuous_wall_condition.html',1,'Kratos']]],
  ['navierstokesp2p1continuouswallcondition_3c_202_20_3e_41787',['NavierStokesP2P1ContinuousWallCondition&lt; 2 &gt;',['../d7/d04/class_kratos_1_1_navier_stokes_p2_p1_continuous_wall_condition.html',1,'Kratos']]],
  ['navierstokesp2p1continuouswallcondition_3c_203_20_3e_41788',['NavierStokesP2P1ContinuousWallCondition&lt; 3 &gt;',['../d7/d04/class_kratos_1_1_navier_stokes_p2_p1_continuous_wall_condition.html',1,'Kratos']]],
  ['navierstokessolverfractionalstep_41789',['NavierStokesSolverFractionalStep',['../d9/db5/classnavier__stokes__solver__fractionalstep_1_1_navier_stokes_solver_fractional_step.html',1,'navier_stokes_solver_fractionalstep']]],
  ['navierstokessolverfractionalstepforchimera_41790',['NavierStokesSolverFractionalStepForChimera',['../de/d32/classnavier__stokes__solver__fractionalstep__chimera_1_1_navier_stokes_solver_fractional_step_for_chimera.html',1,'navier_stokes_solver_fractionalstep_chimera']]],
  ['navierstokessolvermonolithicchimera_41791',['NavierStokesSolverMonolithicChimera',['../d4/d03/classnavier__stokes__solver__vmsmonolithic__chimera_1_1_navier_stokes_solver_monolithic_chimera.html',1,'navier_stokes_solver_vmsmonolithic_chimera']]],
  ['navierstokessolvermonolithicdem_41792',['NavierStokesSolverMonolithicDEM',['../dc/d1e/classnavier__stokes__solver__vms__monolithic___d_e_m_coupled_1_1_navier_stokes_solver_monolithic_d_e_m.html',1,'navier_stokes_solver_vms_monolithic_DEMCoupled']]],
  ['navierstokestwofluidshydraulicsolver_41793',['NavierStokesTwoFluidsHydraulicSolver',['../d2/d90/classnavier__stokes__two__fluid__hydraulic__solver_1_1_navier_stokes_two_fluids_hydraulic_solver.html',1,'navier_stokes_two_fluid_hydraulic_solver']]],
  ['navierstokestwofluidssolver_41794',['NavierStokesTwoFluidsSolver',['../dc/d43/classnavier__stokes__two__fluids__solver_1_1_navier_stokes_two_fluids_solver.html',1,'navier_stokes_two_fluids_solver']]],
  ['navierstokeswallcondition_41795',['NavierStokesWallCondition',['../d3/dfc/class_kratos_1_1_navier_stokes_wall_condition.html',1,'Kratos']]],
  ['navierstokeswallcondition_3c_202_2c_202_20_3e_41796',['NavierStokesWallCondition&lt; 2, 2 &gt;',['../d3/dfc/class_kratos_1_1_navier_stokes_wall_condition.html',1,'Kratos']]],
  ['navierstokeswallcondition_3c_202_2c_202_2c_20kratos_3a_3alinearlogwalllaw_3c_202_2c_202_20_3e_20_3e_41797',['NavierStokesWallCondition&lt; 2, 2, Kratos::LinearLogWallLaw&lt; 2, 2 &gt; &gt;',['../d3/dfc/class_kratos_1_1_navier_stokes_wall_condition.html',1,'Kratos']]],
  ['navierstokeswallcondition_3c_202_2c_202_2c_20kratos_3a_3anavierslipwalllaw_3c_202_2c_202_20_3e_20_3e_41798',['NavierStokesWallCondition&lt; 2, 2, Kratos::NavierSlipWallLaw&lt; 2, 2 &gt; &gt;',['../d3/dfc/class_kratos_1_1_navier_stokes_wall_condition.html',1,'Kratos']]],
  ['navierstokeswallcondition_3c_203_2c_203_20_3e_41799',['NavierStokesWallCondition&lt; 3, 3 &gt;',['../d3/dfc/class_kratos_1_1_navier_stokes_wall_condition.html',1,'Kratos']]],
  ['navierstokeswallcondition_3c_203_2c_203_2c_20kratos_3a_3alinearlogwalllaw_3c_203_2c_203_20_3e_20_3e_41800',['NavierStokesWallCondition&lt; 3, 3, Kratos::LinearLogWallLaw&lt; 3, 3 &gt; &gt;',['../d3/dfc/class_kratos_1_1_navier_stokes_wall_condition.html',1,'Kratos']]],
  ['navierstokeswallcondition_3c_203_2c_203_2c_20kratos_3a_3anavierslipwalllaw_3c_203_2c_203_20_3e_20_3e_41801',['NavierStokesWallCondition&lt; 3, 3, Kratos::NavierSlipWallLaw&lt; 3, 3 &gt; &gt;',['../d3/dfc/class_kratos_1_1_navier_stokes_wall_condition.html',1,'Kratos']]],
  ['navierstokeswallcondition_3c_20tdim_2c_20tnumnodes_2c_20twallmodel_2e_2e_2e_20_3e_41802',['NavierStokesWallCondition&lt; TDim, TNumNodes, TWallModel... &gt;',['../d3/dfc/class_kratos_1_1_navier_stokes_wall_condition.html',1,'Kratos']]],
  ['nearestelementinterfaceinfo_41803',['NearestElementInterfaceInfo',['../dc/d66/class_kratos_1_1_nearest_element_interface_info.html',1,'Kratos']]],
  ['nearestelementlocalsystem_41804',['NearestElementLocalSystem',['../dc/dae/class_kratos_1_1_nearest_element_local_system.html',1,'Kratos']]],
  ['nearestelementmapper_41805',['NearestElementMapper',['../d2/d01/class_kratos_1_1_nearest_element_mapper.html',1,'Kratos']]],
  ['nearestelementoptions_41806',['NearestElementOptions',['../d6/d79/struct_kratos_1_1_nearest_element_options.html',1,'Kratos']]],
  ['nearestentityexplicitdamping_41807',['NearestEntityExplicitDamping',['../d2/d6c/class_kratos_1_1_nearest_entity_explicit_damping.html',1,'Kratos']]],
  ['nearestneighborinterfaceinfo_41808',['NearestNeighborInterfaceInfo',['../d9/d21/class_kratos_1_1_nearest_neighbor_interface_info.html',1,'Kratos']]],
  ['nearestneighborlocalsystem_41809',['NearestNeighborLocalSystem',['../dc/dde/class_kratos_1_1_nearest_neighbor_local_system.html',1,'Kratos']]],
  ['nearestneighbormapper_41810',['NearestNeighborMapper',['../d2/d14/class_kratos_1_1_nearest_neighbor_mapper.html',1,'Kratos']]],
  ['nearestpointutilities_41811',['NearestPointUtilities',['../d3/d13/class_kratos_1_1_nearest_point_utilities.html',1,'Kratos']]],
  ['neighbours_41812',['Neighbours',['../dd/d4d/class_kratos_1_1_neighbours.html',1,'Kratos']]],
  ['neohookeanj_5f1squaredmodel_41813',['NeoHookeanJ_1SquaredModel',['../db/dcc/class_kratos_1_1_neo_hookean_j__1_squared_model.html',1,'Kratos']]],
  ['neohookeanlnjsquaredmodel_41814',['NeoHookeanLnJSquaredModel',['../dd/d1c/class_kratos_1_1_neo_hookean_ln_j_squared_model.html',1,'Kratos']]],
  ['neohookeanmodel_41815',['NeoHookeanModel',['../d9/d80/class_kratos_1_1_neo_hookean_model.html',1,'Kratos']]],
  ['newhenckytrescaplasticaxisym2dlaw_41816',['NewHenckyTrescaPlasticAxisym2DLaw',['../dd/ddf/class_kratos_1_1_new_hencky_tresca_plastic_axisym2_d_law.html',1,'Kratos']]],
  ['newhenckytrescaplasticplanestrain2dlaw_41817',['NewHenckyTrescaPlasticPlaneStrain2DLaw',['../d7/dff/class_kratos_1_1_new_hencky_tresca_plastic_plane_strain2_d_law.html',1,'Kratos']]],
  ['newmark_41818',['Newmark',['../de/d93/class_kratos_1_1_time_discretization_1_1_newmark.html',1,'Kratos::TimeDiscretization']]],
  ['newmarkdynamicupwscheme_41819',['NewmarkDynamicUPwScheme',['../d5/d7c/class_kratos_1_1_newmark_dynamic_u_pw_scheme.html',1,'Kratos']]],
  ['newmarkmethod_41820',['NewmarkMethod',['../df/d06/class_kratos_1_1_newmark_method.html',1,'Kratos::NewmarkMethod&lt; TVariableType, TValueType &gt;'],['../de/de4/struct_kratos_1_1_residual_based_bossak_displacement_rotation_scheme_1_1_newmark_method.html',1,'Kratos::ResidualBasedBossakDisplacementRotationScheme&lt; TSparseSpace, TDenseSpace &gt;::NewmarkMethod'],['../d7/d7c/struct_kratos_1_1_residual_based_bossak_displacement_scheme_1_1_newmark_method.html',1,'Kratos::ResidualBasedBossakDisplacementScheme&lt; TSparseSpace, TDenseSpace &gt;::NewmarkMethod'],['../d6/de5/struct_kratos_1_1_residual_based_bossak_scheme_1_1_newmark_method.html',1,'Kratos::ResidualBasedBossakScheme&lt; TSparseSpace, TDenseSpace &gt;::NewmarkMethod']]],
  ['newmarkparameters_41821',['NewmarkParameters',['../dc/d5c/struct_kratos_1_1_newmark_method_1_1_newmark_parameters.html',1,'Kratos::NewmarkMethod']]],
  ['newmarkquasistaticdampedupwscheme_41822',['NewmarkQuasistaticDampedUPwScheme',['../d4/d1f/class_kratos_1_1_newmark_quasistatic_damped_u_pw_scheme.html',1,'Kratos']]],
  ['newmarkquasistaticpwscheme_41823',['NewmarkQuasistaticPwScheme',['../d7/d1e/class_kratos_1_1_newmark_quasistatic_pw_scheme.html',1,'Kratos']]],
  ['newmarkquasistaticupwscheme_41824',['NewmarkQuasistaticUPwScheme',['../d7/db5/class_kratos_1_1_newmark_quasistatic_u_pw_scheme.html',1,'Kratos']]],
  ['newmarkstepmethod_41825',['NewmarkStepMethod',['../d4/db7/class_kratos_1_1_newmark_step_method.html',1,'Kratos']]],
  ['newmarksteprotationmethod_41826',['NewmarkStepRotationMethod',['../da/d6a/class_kratos_1_1_newmark_step_rotation_method.html',1,'Kratos']]],
  ['newtondraglaw_41827',['NewtonDragLaw',['../d5/d32/class_kratos_1_1_newton_drag_law.html',1,'Kratos']]],
  ['newtonian2dlaw_41828',['Newtonian2DLaw',['../df/d3c/class_kratos_1_1_newtonian2_d_law.html',1,'Kratos']]],
  ['newtonian3dlaw_41829',['Newtonian3DLaw',['../d7/d48/class_kratos_1_1_newtonian3_d_law.html',1,'Kratos']]],
  ['newtonianfluid3dlaw_41830',['NewtonianFluid3DLaw',['../d1/db3/class_kratos_1_1_newtonian_fluid3_d_law.html',1,'Kratos']]],
  ['newtonianfluidplanestrain2dlaw_41831',['NewtonianFluidPlaneStrain2DLaw',['../d6/d20/class_kratos_1_1_newtonian_fluid_plane_strain2_d_law.html',1,'Kratos']]],
  ['newtoniantemperaturedependent2dlaw_41832',['NewtonianTemperatureDependent2DLaw',['../d9/d49/class_kratos_1_1_newtonian_temperature_dependent2_d_law.html',1,'Kratos']]],
  ['newtoniantemperaturedependent3dlaw_41833',['NewtonianTemperatureDependent3DLaw',['../df/df5/class_kratos_1_1_newtonian_temperature_dependent3_d_law.html',1,'Kratos']]],
  ['newtoniantwofluid2dlaw_41834',['NewtonianTwoFluid2DLaw',['../d8/dbe/class_kratos_1_1_newtonian_two_fluid2_d_law.html',1,'Kratos']]],
  ['newtoniantwofluid3dlaw_41835',['NewtonianTwoFluid3DLaw',['../de/ded/class_kratos_1_1_newtonian_two_fluid3_d_law.html',1,'Kratos']]],
  ['newtonraphsonstrategy_41836',['NewtonRaphsonStrategy',['../d7/da5/class_kratos_1_1_newton_raphson_strategy.html',1,'Kratos']]],
  ['newtrescayieldcriterion_41837',['NewTrescaYieldCriterion',['../d8/de5/class_kratos_1_1_new_tresca_yield_criterion.html',1,'Kratos']]],
  ['nistutils_41838',['NistUtils',['../dc/d06/class_kratos_1_1_nist_utils.html',1,'Kratos']]],
  ['nitschestabilizationmodelpartprocess_41839',['NitscheStabilizationModelPartProcess',['../dc/df2/class_kratos_1_1_nitsche_stabilization_model_part_process.html',1,'Kratos']]],
  ['nitschestabilizationprocess_41840',['NitscheStabilizationProcess',['../d5/d32/classnitsche__stabilization__process_1_1_nitsche_stabilization_process.html',1,'nitsche_stabilization_process']]],
  ['nloptalgorithms_41841',['NLOPTAlgorithms',['../d0/da0/classalgorithms_1_1_n_l_o_p_t__algorithms_1_1_n_l_o_p_t_algorithms.html',1,'algorithms::NLOPT_algorithms']]],
  ['nn_5from_5finterface_41842',['NN_ROM_Interface',['../db/dba/classrom__nn__interface_1_1_n_n___r_o_m___interface.html',1,'rom_nn_interface']]],
  ['nodalconcentratedelement_41843',['NodalConcentratedElement',['../d4/d9f/class_kratos_1_1_nodal_concentrated_element.html',1,'Kratos']]],
  ['nodalcontaineraccess_41844',['NodalContainerAccess',['../d3/d22/class_kratos_1_1_m_p_i_internals_1_1_nodal_container_access.html',1,'Kratos::MPIInternals']]],
  ['nodaldata_41845',['NodalData',['../dc/dd1/classcore_1_1xdmf_1_1_nodal_data.html',1,'core.xdmf.NodalData'],['../d1/ddf/class_kratos_1_1_nodal_data.html',1,'Kratos::NodalData']]],
  ['nodaldataaccess_41846',['NodalDataAccess',['../dc/daf/class_kratos_1_1_m_p_i_internals_1_1_nodal_data_access.html',1,'Kratos::MPIInternals']]],
  ['nodaldatavalueinput_41847',['NodalDataValueInput',['../db/d68/classcore_1_1operations_1_1model__part_1_1_nodal_data_value_input.html',1,'core::operations::model_part']]],
  ['nodaldatavalueio_41848',['NodalDataValueIO',['../d7/d89/class_kratos_1_1_h_d_f5_1_1_nodal_data_value_i_o.html',1,'Kratos::HDF5']]],
  ['nodaldatavalueoutput_41849',['NodalDataValueOutput',['../de/d38/classcore_1_1operations_1_1model__part_1_1_nodal_data_value_output.html',1,'core::operations::model_part']]],
  ['nodalextrapolator_41850',['NodalExtrapolator',['../d3/d41/class_kratos_1_1_nodal_extrapolator.html',1,'Kratos']]],
  ['nodalflags_41851',['NodalFlags',['../dc/dea/struct_kratos_1_1_select_elements_mesher_process_1_1_nodal_flags.html',1,'Kratos::SelectElementsMesherProcess']]],
  ['nodalflagsaccess_41852',['NodalFlagsAccess',['../dd/db4/class_kratos_1_1_m_p_i_internals_1_1_nodal_flags_access.html',1,'Kratos::MPIInternals']]],
  ['nodalflagvalueinput_41853',['NodalFlagValueInput',['../dc/dbe/classcore_1_1operations_1_1model__part_1_1_nodal_flag_value_input.html',1,'core::operations::model_part']]],
  ['nodalflagvalueio_41854',['NodalFlagValueIO',['../d1/d9d/class_kratos_1_1_h_d_f5_1_1_nodal_flag_value_i_o.html',1,'Kratos::HDF5']]],
  ['nodalflagvalueoutput_41855',['NodalFlagValueOutput',['../d9/d08/classcore_1_1operations_1_1model__part_1_1_nodal_flag_value_output.html',1,'core::operations::model_part']]],
  ['nodalmanninglaw_41856',['NodalManningLaw',['../d9/d24/class_kratos_1_1_nodal_manning_law.html',1,'Kratos']]],
  ['nodalneighbourssearchprocess_41857',['NodalNeighboursSearchProcess',['../dc/d83/class_kratos_1_1_nodal_neighbours_search_process.html',1,'Kratos']]],
  ['nodalnonhistoricalspatialmethods_41858',['NodalNonHistoricalSpatialMethods',['../d7/d27/class_kratos_1_1_spatial_methods_1_1_nodal_non_historical_spatial_methods.html',1,'Kratos::SpatialMethods']]],
  ['nodalnonhistoricaltemporalmethods_41859',['NodalNonHistoricalTemporalMethods',['../de/dd4/class_kratos_1_1_temporal_methods_1_1_nodal_non_historical_temporal_methods.html',1,'Kratos::TemporalMethods']]],
  ['nodalpositionexpressionio_41860',['NodalPositionExpressionIO',['../d7/d6e/class_kratos_1_1_nodal_position_expression_i_o.html',1,'Kratos']]],
  ['nodalresidualbasedeliminationbuilderandsolver_41861',['NodalResidualBasedEliminationBuilderAndSolver',['../d2/d8d/class_kratos_1_1_nodal_residual_based_elimination_builder_and_solver.html',1,'Kratos']]],
  ['nodalresidualbasedeliminationbuilderandsolvercontinuity_41862',['NodalResidualBasedEliminationBuilderAndSolverContinuity',['../db/de0/class_kratos_1_1_nodal_residual_based_elimination_builder_and_solver_continuity.html',1,'Kratos']]],
  ['nodalresidualbasedeliminationbuilderandsolvercontinuityforfsi_41863',['NodalResidualBasedEliminationBuilderAndSolverContinuityForFSI',['../d6/dc4/class_kratos_1_1_nodal_residual_based_elimination_builder_and_solver_continuity_for_f_s_i.html',1,'Kratos']]],
  ['nodalresidualbasedeliminationbuilderandsolverforfsi_41864',['NodalResidualBasedEliminationBuilderAndSolverForFSI',['../d9/df1/class_kratos_1_1_nodal_residual_based_elimination_builder_and_solver_for_f_s_i.html',1,'Kratos']]],
  ['nodalsolutionstepbossakio_41865',['NodalSolutionStepBossakIO',['../dc/d55/class_kratos_1_1_h_d_f5_1_1_nodal_solution_step_bossak_i_o.html',1,'Kratos::HDF5']]],
  ['nodalsolutionstepdataaccess_41866',['NodalSolutionStepDataAccess',['../da/d0d/class_kratos_1_1_m_p_i_internals_1_1_nodal_solution_step_data_access.html',1,'Kratos::MPIInternals']]],
  ['nodalsolutionstepdatainput_41867',['NodalSolutionStepDataInput',['../d9/df9/classcore_1_1operations_1_1model__part_1_1_nodal_solution_step_data_input.html',1,'core::operations::model_part']]],
  ['nodalsolutionstepdataio_41868',['NodalSolutionStepDataIO',['../d0/dd8/class_kratos_1_1_h_d_f5_1_1_nodal_solution_step_data_i_o.html',1,'Kratos::HDF5']]],
  ['nodalsolutionstepdataoutput_41869',['NodalSolutionStepDataOutput',['../d6/d78/classcore_1_1operations_1_1model__part_1_1_nodal_solution_step_data_output.html',1,'core::operations::model_part']]],
  ['nodalsolutionstepvalueaccess_41870',['NodalSolutionStepValueAccess',['../d2/db6/class_kratos_1_1_m_p_i_internals_1_1_nodal_solution_step_value_access.html',1,'Kratos::MPIInternals']]],
  ['nodaltwostepvpstrategy_41871',['NodalTwoStepVPStrategy',['../de/d10/class_kratos_1_1_nodal_two_step_v_p_strategy.html',1,'Kratos']]],
  ['nodaltwostepvpstrategyforfsi_41872',['NodalTwoStepVPStrategyForFSI',['../d2/d29/class_kratos_1_1_nodal_two_step_v_p_strategy_for_f_s_i.html',1,'Kratos']]],
  ['nodalupdatebaseclass_41873',['NodalUpdateBaseClass',['../d3/da8/class_kratos_1_1_nodal_update_base_class.html',1,'Kratos']]],
  ['nodalupdatenewmark_41874',['NodalUpdateNewmark',['../df/d14/class_kratos_1_1_nodal_update_newmark.html',1,'Kratos']]],
  ['nodalvalueretriever_41875',['NodalValueRetriever',['../d7/dc9/class_kratos_1_1_nodal_value_retriever.html',1,'Kratos']]],
  ['nodalvalueretrieverbaseclass_41876',['NodalValueRetrieverBaseClass',['../d7/d39/class_kratos_1_1_nodal_value_retriever_base_class.html',1,'Kratos']]],
  ['nodalvaluesinterpolationprocess_41877',['NodalValuesInterpolationProcess',['../db/d59/class_kratos_1_1_nodal_values_interpolation_process.html',1,'Kratos']]],
  ['nodalvariablegetter_41878',['NodalVariableGetter',['../da/df0/struct_kratos_1_1_h_d_f5_1_1_nodal_variable_getter.html',1,'Kratos::HDF5']]],
  ['nodalvariablerecordingprocess_41879',['NodalVariableRecordingProcess',['../dc/d34/classnodal__variable__recording__process_1_1_nodal_variable_recording_process.html',1,'nodal_variable_recording_process']]],
  ['node_41880',['Node',['../d5/ddd/class_kratos_1_1_node.html',1,'Kratos']]],
  ['node_41881',['node',['../d5/da1/structnode.html',1,'']]],
  ['nodeconfigure_41882',['NodeConfigure',['../d3/d6d/class_kratos_1_1_node_configure.html',1,'Kratos']]],
  ['nodeconfigurefornodesearch_41883',['NodeConfigureForNodeSearch',['../dc/d3a/class_kratos_1_1_node_configure_for_node_search.html',1,'Kratos']]],
  ['nodesearchutility_41884',['NodeSearchUtility',['../dd/d04/class_kratos_1_1_node_search_utility.html',1,'Kratos']]],
  ['nodeutilities_41885',['NodeUtilities',['../de/d02/class_kratos_1_1_node_utilities.html',1,'Kratos']]],
  ['nonassociativeexplicitplasticflowrule_41886',['NonAssociativeExplicitPlasticFlowRule',['../d7/d9b/class_kratos_1_1_non_associative_explicit_plastic_flow_rule.html',1,'Kratos']]],
  ['nonassociativeplasticitymodel_41887',['NonAssociativePlasticityModel',['../d8/db3/class_kratos_1_1_non_associative_plasticity_model.html',1,'Kratos']]],
  ['nonassociativeplasticitymodel_3c_20borjamodel_2c_20modifiedcamclayyieldsurface_3c_20camclayhardeningrule_20_3e_20_3e_41888',['NonAssociativePlasticityModel&lt; BorjaModel, ModifiedCamClayYieldSurface&lt; CamClayHardeningRule &gt; &gt;',['../d8/db3/class_kratos_1_1_non_associative_plasticity_model.html',1,'Kratos']]],
  ['nonewtonianmonolithicpfem22d_41889',['NoNewtonianMonolithicPFEM22D',['../d9/d4e/class_kratos_1_1_no_newtonian_monolithic_p_f_e_m22_d.html',1,'Kratos']]],
  ['nonewtonianmonolithicpfem23d_41890',['NoNewtonianMonolithicPFEM23D',['../db/d23/class_kratos_1_1_no_newtonian_monolithic_p_f_e_m23_d.html',1,'Kratos']]],
  ['nonexistingmodule_41891',['NonExistingModule',['../d9/dc5/classxdmf__utils_1_1_non_existing_module.html',1,'xdmf_utils']]],
  ['nonhistorical_41892',['NonHistorical',['../de/d27/struct_kratos_1_1_container_data_i_o_tags_1_1_non_historical.html',1,'Kratos::ContainerDataIOTags']]],
  ['nonhistoricaldatavalueretrievalfunctor_41893',['NonHistoricalDataValueRetrievalFunctor',['../db/d46/class_kratos_1_1_method_utilities_1_1_non_historical_data_value_retrieval_functor.html',1,'Kratos::MethodUtilities']]],
  ['nonhistoricalvariable_41894',['NonHistoricalVariable',['../d2/db6/class_kratos_1_1_collective_expression_i_o_1_1_non_historical_variable.html',1,'Kratos::CollectiveExpressionIO']]],
  ['nonhistoricalvariablegetter_41895',['NonHistoricalVariableGetter',['../db/d2b/struct_kratos_1_1_h_d_f5_1_1_non_historical_variable_getter.html',1,'Kratos::HDF5']]],
  ['nonlinearassociativeplasticflowrule_41896',['NonLinearAssociativePlasticFlowRule',['../d9/d71/class_kratos_1_1_non_linear_associative_plastic_flow_rule.html',1,'Kratos']]],
  ['nonlinearassociativeplasticitymodel_41897',['NonLinearAssociativePlasticityModel',['../d4/d91/class_kratos_1_1_non_linear_associative_plasticity_model.html',1,'Kratos']]],
  ['nonlinearassociativeplasticitymodel_3c_20incompressibleneohookeanmodel_2c_20miseshuberthermalyieldsurface_3c_20simoexponentialthermalhardeningrule_20_3e_20_3e_41898',['NonLinearAssociativePlasticityModel&lt; IncompressibleNeoHookeanModel, MisesHuberThermalYieldSurface&lt; SimoExponentialThermalHardeningRule &gt; &gt;',['../d4/d91/class_kratos_1_1_non_linear_associative_plasticity_model.html',1,'Kratos']]],
  ['nonlinearassociativeplasticitymodel_3c_20incompressibleneohookeanmodel_2c_20miseshuberyieldsurface_3c_20simoexponentialhardeningrule_20_3e_20_3e_41899',['NonLinearAssociativePlasticityModel&lt; IncompressibleNeoHookeanModel, MisesHuberYieldSurface&lt; SimoExponentialHardeningRule &gt; &gt;',['../d4/d91/class_kratos_1_1_non_linear_associative_plasticity_model.html',1,'Kratos']]],
  ['nonlinearassociativeplasticitymodel_3c_20isochoricneohookeanmodel_2c_20miseshuberyieldsurface_3c_20simoexponentialhardeningrule_20_3e_20_3e_41900',['NonLinearAssociativePlasticityModel&lt; IsochoricNeoHookeanModel, MisesHuberYieldSurface&lt; SimoExponentialHardeningRule &gt; &gt;',['../d4/d91/class_kratos_1_1_non_linear_associative_plasticity_model.html',1,'Kratos']]],
  ['nonlinearassociativeplasticitymodel_3c_20linearelasticmodel_2c_20miseshuberyieldsurface_3c_20simoexponentialhardeningrule_20_3e_20_3e_41901',['NonLinearAssociativePlasticityModel&lt; LinearElasticModel, MisesHuberYieldSurface&lt; SimoExponentialHardeningRule &gt; &gt;',['../d4/d91/class_kratos_1_1_non_linear_associative_plasticity_model.html',1,'Kratos']]],
  ['nonlinearhenckyelasticplastic3dlaw_41902',['NonLinearHenckyElasticPlastic3DLaw',['../d3/d2e/class_kratos_1_1_non_linear_hencky_elastic_plastic3_d_law.html',1,'Kratos']]],
  ['nonlinearhenckyelasticplasticaxisym2dlaw_41903',['NonLinearHenckyElasticPlasticAxisym2DLaw',['../de/d24/class_kratos_1_1_non_linear_hencky_elastic_plastic_axisym2_d_law.html',1,'Kratos']]],
  ['nonlinearhenckyelasticplasticplanestrain2dlaw_41904',['NonLinearHenckyElasticPlasticPlaneStrain2DLaw',['../d2/d9a/class_kratos_1_1_non_linear_hencky_elastic_plastic_plane_strain2_d_law.html',1,'Kratos']]],
  ['nonlinearhenckyelasticplasticup3dlaw_41905',['NonLinearHenckyElasticPlasticUP3DLaw',['../da/d99/class_kratos_1_1_non_linear_hencky_elastic_plastic_u_p3_d_law.html',1,'Kratos']]],
  ['nonlinearhenckyelasticplasticupaxisym2dlaw_41906',['NonLinearHenckyElasticPlasticUPAxisym2DLaw',['../dd/d2e/class_kratos_1_1_non_linear_hencky_elastic_plastic_u_p_axisym2_d_law.html',1,'Kratos']]],
  ['nonlinearhenckyelasticplasticupplanestrain2dlaw_41907',['NonLinearHenckyElasticPlasticUPPlaneStrain2DLaw',['../d9/d16/class_kratos_1_1_non_linear_hencky_elastic_plastic_u_p_plane_strain2_d_law.html',1,'Kratos']]],
  ['nonlinearisotropickinematichardeninglaw_41908',['NonLinearIsotropicKinematicHardeningLaw',['../dc/d6e/class_kratos_1_1_non_linear_isotropic_kinematic_hardening_law.html',1,'Kratos']]],
  ['nonlinearisotropickinematicthermalhardeninglaw_41909',['NonLinearIsotropicKinematicThermalHardeningLaw',['../dc/df1/class_kratos_1_1_non_linear_isotropic_kinematic_thermal_hardening_law.html',1,'Kratos']]],
  ['nonlinearratedependentplasticflowrule_41910',['NonLinearRateDependentPlasticFlowRule',['../da/dce/class_kratos_1_1_non_linear_rate_dependent_plastic_flow_rule.html',1,'Kratos']]],
  ['nonlinearratedependentplasticitymodel_41911',['NonLinearRateDependentPlasticityModel',['../d4/d3f/class_kratos_1_1_non_linear_rate_dependent_plasticity_model.html',1,'Kratos']]],
  ['nonlinearratedependentplasticitymodel_3c_20incompressibleneohookeanmodel_2c_20miseshuberthermalyieldsurface_3c_20bakerjohnsoncookthermalhardeningrule_20_3e_20_3e_41912',['NonLinearRateDependentPlasticityModel&lt; IncompressibleNeoHookeanModel, MisesHuberThermalYieldSurface&lt; BakerJohnsonCookThermalHardeningRule &gt; &gt;',['../d4/d3f/class_kratos_1_1_non_linear_rate_dependent_plasticity_model.html',1,'Kratos']]],
  ['nonlinearratedependentplasticitymodel_3c_20incompressibleneohookeanmodel_2c_20miseshuberthermalyieldsurface_3c_20johnsoncookthermalhardeningrule_20_3e_20_3e_41913',['NonLinearRateDependentPlasticityModel&lt; IncompressibleNeoHookeanModel, MisesHuberThermalYieldSurface&lt; JohnsonCookThermalHardeningRule &gt; &gt;',['../d4/d3f/class_kratos_1_1_non_linear_rate_dependent_plasticity_model.html',1,'Kratos']]],
  ['nonlocalcamclaymodel_41914',['NonlocalCamClayModel',['../da/dc1/class_kratos_1_1_nonlocal_cam_clay_model.html',1,'Kratos']]],
  ['nonlocaldamage2dutilities_41915',['NonlocalDamage2DUtilities',['../d8/dce/class_kratos_1_1_nonlocal_damage2_d_utilities.html',1,'Kratos']]],
  ['nonlocaldamage3dlaw_41916',['NonlocalDamage3DLaw',['../d1/d0f/class_kratos_1_1_nonlocal_damage3_d_law.html',1,'Kratos']]],
  ['nonlocaldamage3dutilities_41917',['NonlocalDamage3DUtilities',['../d2/d57/class_kratos_1_1_nonlocal_damage3_d_utilities.html',1,'Kratos']]],
  ['nonlocaldamageflowrule_41918',['NonlocalDamageFlowRule',['../d3/d0d/class_kratos_1_1_nonlocal_damage_flow_rule.html',1,'Kratos']]],
  ['nonlocaldamageplanestrain2dlaw_41919',['NonlocalDamagePlaneStrain2DLaw',['../de/dc5/class_kratos_1_1_nonlocal_damage_plane_strain2_d_law.html',1,'Kratos']]],
  ['nonlocaldamageplanestress2dlaw_41920',['NonlocalDamagePlaneStress2DLaw',['../d3/d50/class_kratos_1_1_nonlocal_damage_plane_stress2_d_law.html',1,'Kratos']]],
  ['nonlocaldamageutilities_41921',['NonlocalDamageUtilities',['../dc/d24/class_kratos_1_1_nonlocal_damage_utilities.html',1,'Kratos']]],
  ['nonlocalplasticityprocess_41922',['NonLocalPlasticityProcess',['../d9/d68/class_kratos_1_1_non_local_plasticity_process.html',1,'Kratos::NonLocalPlasticityProcess'],['../db/d5b/classnon__local__plasticity__process_1_1_non_local_plasticity_process.html',1,'non_local_plasticity_process.NonLocalPlasticityProcess']]],
  ['nonlocalv2gensnovamodel_41923',['NonlocalV2GensNovaModel',['../d8/daa/class_kratos_1_1_nonlocal_v2_gens_nova_model.html',1,'Kratos']]],
  ['nontrivialsumreduction_41924',['NonTrivialSumReduction',['../d7/d2c/struct_kratos_1_1_petrov_galerkin_r_o_m_builder_and_solver_1_1_non_trivial_sum_reduction.html',1,'Kratos::PetrovGalerkinROMBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::NonTrivialSumReduction&lt; T &gt;'],['../dd/d0c/struct_kratos_1_1_r_o_m_builder_and_solver_1_1_non_trivial_sum_reduction.html',1,'Kratos::ROMBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::NonTrivialSumReduction&lt; T &gt;']]],
  ['norm_41925',['norm',['../d6/dab/interfacetensors_1_1norm.html',1,'tensors']]],
  ['normalcalculationutils_41926',['NormalCalculationUtils',['../d2/ddc/class_kratos_1_1_normal_calculation_utils.html',1,'Kratos']]],
  ['normalcheckprocess_41927',['NormalCheckProcess',['../de/dc2/class_kratos_1_1_normal_check_process.html',1,'Kratos']]],
  ['normalfaceloadvariables_41928',['NormalFaceLoadVariables',['../d1/d53/struct_kratos_1_1_u_pl_normal_face_load_condition_1_1_normal_face_load_variables.html',1,'Kratos::UPlNormalFaceLoadCondition&lt; TDim, TNumNodes &gt;::NormalFaceLoadVariables'],['../d7/da8/struct_kratos_1_1_u_pw_normal_face_load_condition_1_1_normal_face_load_variables.html',1,'Kratos::UPwNormalFaceLoadCondition&lt; TDim, TNumNodes &gt;::NormalFaceLoadVariables']]],
  ['normalfluxficvariables_41929',['NormalFluxFICVariables',['../dc/d0f/struct_kratos_1_1_u_pw_normal_flux_f_i_c_condition_1_1_normal_flux_f_i_c_variables.html',1,'Kratos::UPwNormalFluxFICCondition']]],
  ['normalfluxvariables_41930',['NormalFluxVariables',['../de/d07/struct_kratos_1_1_pw_normal_flux_condition_1_1_normal_flux_variables.html',1,'Kratos::PwNormalFluxCondition&lt; TDim, TNumNodes &gt;::NormalFluxVariables'],['../d1/d84/struct_kratos_1_1_u_pw_normal_flux_condition_1_1_normal_flux_variables.html',1,'Kratos::UPwNormalFluxCondition&lt; TDim, TNumNodes &gt;::NormalFluxVariables']]],
  ['normalgapprocess_41931',['NormalGapProcess',['../d6/d25/class_kratos_1_1_normal_gap_process.html',1,'Kratos']]],
  ['normalliquidfluxficvariables_41932',['NormalLiquidFluxFICVariables',['../dc/d4a/struct_kratos_1_1_u_pl_normal_liquid_flux_f_i_c_condition_1_1_normal_liquid_flux_f_i_c_variables.html',1,'Kratos::UPlNormalLiquidFluxFICCondition']]],
  ['normalliquidfluxvariables_41933',['NormalLiquidFluxVariables',['../d2/d9c/struct_kratos_1_1_u_pl_normal_liquid_flux_condition_1_1_normal_liquid_flux_variables.html',1,'Kratos::UPlNormalLiquidFluxCondition']]],
  ['normallysmerabsorbingvariables_41934',['NormalLysmerAbsorbingVariables',['../d1/da4/struct_kratos_1_1_u_pw_lysmer_absorbing_condition_1_1_normal_lysmer_absorbing_variables.html',1,'Kratos::UPwLysmerAbsorbingCondition']]],
  ['normmethod_41935',['NormMethod',['../d6/d9e/class_kratos_1_1_temporal_methods_1_1_temporal_max_method_1_1_norm_method.html',1,'Kratos::TemporalMethods::TemporalMaxMethod&lt; TContainerType, TContainerItemType, TDataRetrievalFunctor, TDataStorageFunctor &gt;::NormMethod&lt; TDataType &gt;'],['../d5/dfe/class_kratos_1_1_temporal_methods_1_1_temporal_mean_method_1_1_norm_method.html',1,'Kratos::TemporalMethods::TemporalMeanMethod&lt; TContainerType, TContainerItemType, TDataRetrievalFunctor, TDataStorageFunctor &gt;::NormMethod&lt; TDataType &gt;'],['../d1/d83/class_kratos_1_1_temporal_methods_1_1_temporal_min_method_1_1_norm_method.html',1,'Kratos::TemporalMethods::TemporalMinMethod&lt; TContainerType, TContainerItemType, TDataRetrievalFunctor, TDataStorageFunctor &gt;::NormMethod&lt; TDataType &gt;'],['../df/d3b/class_kratos_1_1_temporal_methods_1_1_temporal_root_mean_square_method_1_1_norm_method.html',1,'Kratos::TemporalMethods::TemporalRootMeanSquareMethod&lt; TContainerType, TContainerItemType, TDataRetrievalFunctor, TDataStorageFunctor &gt;::NormMethod&lt; TDataType &gt;'],['../de/d95/class_kratos_1_1_temporal_methods_1_1_temporal_sum_method_1_1_norm_method.html',1,'Kratos::TemporalMethods::TemporalSumMethod&lt; TContainerType, TContainerItemType, TDataRetrievalFunctor, TDataStorageFunctor &gt;::NormMethod&lt; TDataType &gt;'],['../dd/dae/class_kratos_1_1_temporal_methods_1_1_temporal_variance_method_1_1_norm_method.html',1,'Kratos::TemporalMethods::TemporalVarianceMethod&lt; TContainerType, TContainerItemType, TDataRetrievalFunctor, TDataStorageFunctor &gt;::NormMethod&lt; TDataType &gt;']]],
  ['nset_41936',['nset',['../da/dfd/structnice__names_1_1nset.html',1,'nice_names']]],
  ['nullinitialized_41937',['NullInitialized',['../d7/d4f/struct_kratos_1_1_internals_1_1_null_initialized.html',1,'Kratos::Internals']]],
  ['nullinitialized_3c_20array_5f1d_3c_20tvaluetype_2c_20arraysize_20_3e_20_3e_41938',['NullInitialized&lt; array_1d&lt; TValueType, ArraySize &gt; &gt;',['../d3/d18/struct_kratos_1_1_internals_1_1_null_initialized_3_01array__1d_3_01_t_value_type_00_01_array_size_01_4_01_4.html',1,'Kratos::Internals']]],
  ['numericalintegrationmethod_41939',['NumericalIntegrationMethod',['../d3/dc1/class_kratos_1_1_numerical_integration_method.html',1,'Kratos']]],
  ['nurbscurvegeometry_41940',['NurbsCurveGeometry',['../d4/da1/class_kratos_1_1_nurbs_curve_geometry.html',1,'Kratos']]],
  ['nurbscurveonsurfacegeometry_41941',['NurbsCurveOnSurfaceGeometry',['../d7/df1/class_kratos_1_1_nurbs_curve_on_surface_geometry.html',1,'Kratos']]],
  ['nurbscurveshapefunction_41942',['NurbsCurveShapeFunction',['../da/df5/class_kratos_1_1_nurbs_curve_shape_function.html',1,'Kratos']]],
  ['nurbsgeometrymodeler_41943',['NurbsGeometryModeler',['../d9/d76/class_kratos_1_1_nurbs_geometry_modeler.html',1,'Kratos']]],
  ['nurbsinterval_41944',['NurbsInterval',['../d9/ddb/class_kratos_1_1_nurbs_interval.html',1,'Kratos']]],
  ['nurbssurfacegeometry_41945',['NurbsSurfaceGeometry',['../df/d94/class_kratos_1_1_nurbs_surface_geometry.html',1,'Kratos']]],
  ['nurbssurfacerefinementutilities_41946',['NurbsSurfaceRefinementUtilities',['../d6/d2b/class_kratos_1_1_nurbs_surface_refinement_utilities.html',1,'Kratos']]],
  ['nurbssurfaceshapefunction_41947',['NurbsSurfaceShapeFunction',['../d7/d77/class_kratos_1_1_nurbs_surface_shape_function.html',1,'Kratos']]],
  ['nurbsvolumegeometry_41948',['NurbsVolumeGeometry',['../d5/ddc/class_kratos_1_1_nurbs_volume_geometry.html',1,'Kratos']]],
  ['nurbsvolumerefinementutilities_41949',['NurbsVolumeRefinementUtilities',['../da/da6/class_kratos_1_1_nurbs_volume_refinement_utilities.html',1,'Kratos']]],
  ['nurbsvolumeshapefunction_41950',['NurbsVolumeShapeFunction',['../d1/de6/class_kratos_1_1_nurbs_volume_shape_function.html',1,'Kratos']]],
  ['nurbsvolumeshapefunctions_41951',['NurbsVolumeShapeFunctions',['../dd/d13/class_nurbs_volume_shape_functions.html',1,'']]],
  ['nusseltgunn_41952',['NusseltGunn',['../d5/d43/class_kratos_1_1_nusselt_gunn.html',1,'Kratos']]],
  ['nusselthanzmarshall_41953',['NusseltHanzMarshall',['../d2/d52/class_kratos_1_1_nusselt_hanz_marshall.html',1,'Kratos']]],
  ['nusseltlimason_41954',['NusseltLiMason',['../d1/d37/class_kratos_1_1_nusselt_li_mason.html',1,'Kratos']]],
  ['nusseltwhitaker_41955',['NusseltWhitaker',['../d8/d8e/class_kratos_1_1_nusselt_whitaker.html',1,'Kratos']]]
];
