var searchData=
[
  ['dallavalledraglaw_39215',['DallavalleDragLaw',['../d4/d83/class_kratos_1_1_dallavalle_drag_law.html',1,'Kratos']]],
  ['damaddedmassconditionprocess_39216',['DamAddedMassConditionProcess',['../dc/dab/class_kratos_1_1_dam_added_mass_condition_process.html',1,'Kratos']]],
  ['damagedetectionresponse_39217',['DamageDetectionResponse',['../d2/d2f/classdamage__detection__response_1_1_damage_detection_response.html',1,'damage_detection_response']]],
  ['damagedplusdminusmasonry2dlaw_39218',['DamageDPlusDMinusMasonry2DLaw',['../d6/de5/class_kratos_1_1_damage_d_plus_d_minus_masonry2_d_law.html',1,'Kratos']]],
  ['damagedplusdminusmasonry3dlaw_39219',['DamageDPlusDMinusMasonry3DLaw',['../dc/d8b/class_kratos_1_1_damage_d_plus_d_minus_masonry3_d_law.html',1,'Kratos']]],
  ['damagemodel_39220',['DamageModel',['../da/db6/class_kratos_1_1_damage_model.html',1,'Kratos']]],
  ['damagemodel_3c_20linearelasticmodel_2c_20simojuyieldsurface_3c_20exponentialdamagehardeningrule_20_3e_20_3e_39221',['DamageModel&lt; LinearElasticModel, SimoJuYieldSurface&lt; ExponentialDamageHardeningRule &gt; &gt;',['../da/db6/class_kratos_1_1_damage_model.html',1,'Kratos']]],
  ['damagemodel_3c_20linearelasticmodel_2c_20simojuyieldsurface_3c_20modifiedexponentialdamagehardeningrule_20_3e_20_3e_39222',['DamageModel&lt; LinearElasticModel, SimoJuYieldSurface&lt; ModifiedExponentialDamageHardeningRule &gt; &gt;',['../da/db6/class_kratos_1_1_damage_model.html',1,'Kratos']]],
  ['damageparameters_39223',['DamageParameters',['../df/d71/struct_kratos_1_1_damage_d_plus_d_minus_masonry3_d_law_1_1_damage_parameters.html',1,'Kratos::DamageDPlusDMinusMasonry3DLaw::DamageParameters'],['../de/de9/struct_kratos_1_1_generic_small_strain_dplus_dminus_damage_1_1_damage_parameters.html',1,'Kratos::GenericSmallStrainDplusDminusDamage&lt; TConstLawIntegratorTensionType, TConstLawIntegratorCompressionType &gt;::DamageParameters']]],
  ['damanalysis_39224',['DamAnalysis',['../d5/d66/classdam__analysis_1_1_dam_analysis.html',1,'dam_analysis']]],
  ['damazenhaheatfluxprocess_39225',['DamAzenhaHeatFluxProcess',['../df/d85/class_kratos_1_1_dam_azenha_heat_flux_process.html',1,'Kratos']]],
  ['dambofangconditiontemperatureprocess_39226',['DamBofangConditionTemperatureProcess',['../d7/deb/class_kratos_1_1_dam_bofang_condition_temperature_process.html',1,'Kratos']]],
  ['dambreakbenchmark_39227',['DamBreakBenchmark',['../d7/d5a/classdam__break__benchmark_1_1_dam_break_benchmark.html',1,'dam_break_benchmark']]],
  ['dambreakmodeler_39228',['DamBreakModeler',['../d0/d15/classdam__break__modeler_1_1_dam_break_modeler.html',1,'dam_break_modeler']]],
  ['damchemomechanicalagingyoungprocess_39229',['DamChemoMechanicalAgingYoungProcess',['../db/dc9/class_kratos_1_1_dam_chemo_mechanical_aging_young_process.html',1,'Kratos']]],
  ['damconstructionutility_39230',['DamConstructionUtility',['../d1/dde/classdam__construction__utility_1_1_dam_construction_utility.html',1,'dam_construction_utility']]],
  ['dameigensolver_39231',['DamEigenSolver',['../da/d4a/classdam__eigen__solver_1_1_dam_eigen_solver.html',1,'dam_eigen_solver']]],
  ['damfixtemperatureconditionprocess_39232',['DamFixTemperatureConditionProcess',['../d4/d50/class_kratos_1_1_dam_fix_temperature_condition_process.html',1,'Kratos']]],
  ['damgroutingreferencetemperatureprocess_39233',['DamGroutingReferenceTemperatureProcess',['../d6/d6d/class_kratos_1_1_dam_grouting_reference_temperature_process.html',1,'Kratos']]],
  ['damhydroconditionloadprocess_39234',['DamHydroConditionLoadProcess',['../d1/d93/class_kratos_1_1_dam_hydro_condition_load_process.html',1,'Kratos']]],
  ['daminputtablenodalyoungmodulusprocess_39235',['DamInputTableNodalYoungModulusProcess',['../d4/d1b/class_kratos_1_1_dam_input_table_nodal_young_modulus_process.html',1,'Kratos']]],
  ['dammechanicalsolver_39236',['DamMechanicalSolver',['../d6/dcd/classdam__mechanical__solver_1_1_dam_mechanical_solver.html',1,'dam_mechanical_solver']]],
  ['damnodalreferencetemperatureprocess_39237',['DamNodalReferenceTemperatureProcess',['../dd/dc9/class_kratos_1_1_dam_nodal_reference_temperature_process.html',1,'Kratos']]],
  ['damnodalyoungmodulusprocess_39238',['DamNodalYoungModulusProcess',['../de/d36/class_kratos_1_1_dam_nodal_young_modulus_process.html',1,'Kratos']]],
  ['damnoorzaiheatfluxprocess_39239',['DamNoorzaiHeatFluxProcess',['../df/d74/class_kratos_1_1_dam_noorzai_heat_flux_process.html',1,'Kratos']]],
  ['dampingfunction_39240',['DampingFunction',['../de/d7b/class_kratos_1_1_damping_function.html',1,'Kratos']]],
  ['dampingutilities_39241',['DampingUtilities',['../d1/d07/class_kratos_1_1_damping_utilities.html',1,'Kratos']]],
  ['dampscheme_39242',['DamPScheme',['../d0/dc0/class_kratos_1_1_dam_p_scheme.html',1,'Kratos']]],
  ['damrandomfieldsvariableprocess_39243',['DamRandomFieldsVariableProcess',['../dc/d75/class_kratos_1_1_dam_random_fields_variable_process.html',1,'Kratos']]],
  ['damreservoirconstanttemperatureprocess_39244',['DamReservoirConstantTemperatureProcess',['../d1/d4e/class_kratos_1_1_dam_reservoir_constant_temperature_process.html',1,'Kratos']]],
  ['damreservoirmonitoringtemperatureprocess_39245',['DamReservoirMonitoringTemperatureProcess',['../df/dc3/class_kratos_1_1_dam_reservoir_monitoring_temperature_process.html',1,'Kratos']]],
  ['damselfweightsolver_39246',['DamSelfweightSolver',['../d4/dd6/classdam__selfweight__solver_1_1_dam_selfweight_solver.html',1,'dam_selfweight_solver']]],
  ['damtemperaturebydeviceprocess_39247',['DamTemperaturebyDeviceProcess',['../d0/d9e/class_kratos_1_1_dam_temperatureby_device_process.html',1,'Kratos']]],
  ['damthermomechanicsolver_39248',['DamThermoMechanicSolver',['../dc/d6b/classdam__thermo__mechanic__solver_1_1_dam_thermo_mechanic_solver.html',1,'dam_thermo_mechanic_solver']]],
  ['damtsolairheatfluxprocess_39249',['DamTSolAirHeatFluxProcess',['../d6/d11/class_kratos_1_1_dam_t_sol_air_heat_flux_process.html',1,'Kratos']]],
  ['damupliftcircularconditionloadprocess_39250',['DamUpliftCircularConditionLoadProcess',['../df/d42/class_kratos_1_1_dam_uplift_circular_condition_load_process.html',1,'Kratos']]],
  ['damupliftconditionloadprocess_39251',['DamUpliftConditionLoadProcess',['../da/d2a/class_kratos_1_1_dam_uplift_condition_load_process.html',1,'Kratos']]],
  ['damupmechanicalsolver_39252',['DamUPMechanicalSolver',['../df/d0e/classdam___u_p__mechanical__solver_1_1_dam_u_p_mechanical_solver.html',1,'dam_UP_mechanical_solver']]],
  ['damupscheme_39253',['DamUPScheme',['../d2/da8/class_kratos_1_1_dam_u_p_scheme.html',1,'Kratos']]],
  ['damupsolver_39254',['DamUPSolver',['../dc/d1e/classdam___p__solver_1_1_dam_u_p_solver.html',1,'dam_P_solver']]],
  ['damupthermomechanicsolver_39255',['DamUPThermoMechanicSolver',['../de/d77/classdam___u_p__thermo__mechanic__solver_1_1_dam_u_p_thermo_mechanic_solver.html',1,'dam_UP_thermo_mechanic_solver']]],
  ['damwestergaardconditionloadprocess_39256',['DamWestergaardConditionLoadProcess',['../db/d5f/class_kratos_1_1_dam_westergaard_condition_load_process.html',1,'Kratos']]],
  ['data_39257',['Data',['../d0/d88/class_kratos_1_1_literal_flat_expression_1_1_data.html',1,'Kratos::LiteralFlatExpression']]],
  ['databuffers_39258',['DataBuffers',['../d9/d9a/struct_kratos_1_1_python_1_1_co_sim_i_o___wrappers_1_1_data_buffers.html',1,'Kratos::Python::CoSimIO_Wrappers']]],
  ['datacommunicator_39259',['DataCommunicator',['../dc/d92/class_kratos_1_1_data_communicator.html',1,'Kratos']]],
  ['datadifferenceresidual_39260',['DataDifferenceResidual',['../d3/d14/classconvergence__accelerators_1_1convergence__accelerator__wrapper_1_1_data_difference_residual.html',1,'convergence_accelerators::convergence_accelerator_wrapper']]],
  ['dataitem_39261',['DataItem',['../d5/d8b/classcore_1_1xdmf_1_1_data_item.html',1,'core::xdmf']]],
  ['datalogger_39262',['DataLogger',['../da/d6c/classloggers_1_1data__logger__factory_1_1_data_logger.html',1,'loggers::data_logger_factory']]],
  ['datatransfer3d1dprocess_39263',['DataTransfer3D1DProcess',['../d5/d4b/class_kratos_1_1_data_transfer3_d1_d_process.html',1,'Kratos']]],
  ['datatypetraits_39264',['DataTypeTraits',['../dd/d0b/class_kratos_1_1_data_type_traits.html',1,'Kratos']]],
  ['datatypetraits_3c_20array_5f1d_3c_20tdatatype_2c_20tsize_20_3e_20_3e_39265',['DataTypeTraits&lt; array_1d&lt; TDataType, TSize &gt; &gt;',['../d5/d52/class_kratos_1_1_data_type_traits_3_01array__1d_3_01_t_data_type_00_01_t_size_01_4_01_4.html',1,'Kratos']]],
  ['datatypetraits_3c_20densematrix_3c_20tdatatype_20_3e_20_3e_39266',['DataTypeTraits&lt; DenseMatrix&lt; TDataType &gt; &gt;',['../d3/d44/class_kratos_1_1_data_type_traits_3_01_dense_matrix_3_01_t_data_type_01_4_01_4.html',1,'Kratos']]],
  ['datatypetraits_3c_20densevector_3c_20tdatatype_20_3e_20_3e_39267',['DataTypeTraits&lt; DenseVector&lt; TDataType &gt; &gt;',['../d8/d7b/class_kratos_1_1_data_type_traits_3_01_dense_vector_3_01_t_data_type_01_4_01_4.html',1,'Kratos']]],
  ['datatypetraits_3c_20std_3a_3astring_20_3e_39268',['DataTypeTraits&lt; std::string &gt;',['../d6/dd2/class_kratos_1_1_data_type_traits_3_01std_1_1string_01_4.html',1,'Kratos']]],
  ['datatypetraits_3c_20std_3a_3avector_3c_20tdatatype_20_3e_20_3e_39269',['DataTypeTraits&lt; std::vector&lt; TDataType &gt; &gt;',['../d4/dd4/class_kratos_1_1_data_type_traits_3_01std_1_1vector_3_01_t_data_type_01_4_01_4.html',1,'Kratos']]],
  ['datavaluecontainer_39270',['DataValueContainer',['../d7/dfa/class_kratos_1_1_data_value_container.html',1,'Kratos']]],
  ['dconvectiondiffusionexplicit_39271',['DConvectionDiffusionExplicit',['../d6/d56/class_kratos_1_1_d_convection_diffusion_explicit.html',1,'Kratos']]],
  ['dconvectiondiffusionexplicit_3c_202_2c_203_20_3e_39272',['DConvectionDiffusionExplicit&lt; 2, 3 &gt;',['../d6/d56/class_kratos_1_1_d_convection_diffusion_explicit.html',1,'Kratos']]],
  ['dconvectiondiffusionexplicit_3c_203_2c_204_20_3e_39273',['DConvectionDiffusionExplicit&lt; 3, 4 &gt;',['../d6/d56/class_kratos_1_1_d_convection_diffusion_explicit.html',1,'Kratos']]],
  ['deactivateconditionsoninactiveelements_39274',['DeactivateConditionsOnInactiveElements',['../dd/ded/class_kratos_1_1_deactivate_conditions_on_inactive_elements.html',1,'Kratos']]],
  ['deactivatemodelpartoperation_39275',['DeactivateModelPartOperation',['../d8/de3/class_kratos_1_1_deactivate_model_part_operation.html',1,'Kratos']]],
  ['decompressedmaterialbtstest_39276',['DecompressedMaterialBTSTest',['../d0/db7/classdecompressed__material__bts__test_1_1_decompressed_material_b_t_s_test.html',1,'decompressed_material_bts_test.DecompressedMaterialBTSTest'],['../d2/daa/classdecompressed__material__triaxials__and__bts__tests_1_1_decompressed_material_b_t_s_test.html',1,'decompressed_material_triaxials_and_bts_tests.DecompressedMaterialBTSTest']]],
  ['decompressedmaterialtriaxialtest_39277',['DecompressedMaterialTriaxialTest',['../d1/d17/classdecompressed__material__triaxial__test_1_1_decompressed_material_triaxial_test.html',1,'decompressed_material_triaxial_test.DecompressedMaterialTriaxialTest'],['../d6/d47/classdecompressed__material__triaxials__and__bts__tests_1_1_decompressed_material_triaxial_test.html',1,'decompressed_material_triaxials_and_bts_tests.DecompressedMaterialTriaxialTest']]],
  ['defaultcontroller_39278',['DefaultController',['../d2/d60/classcore_1_1controllers_1_1_default_controller.html',1,'core::controllers']]],
  ['define2dwakeprocess_39279',['Define2DWakeProcess',['../db/dcf/class_kratos_1_1_define2_d_wake_process.html',1,'Kratos']]],
  ['define3dwakeprocess_39280',['Define3DWakeProcess',['../d3/d72/class_kratos_1_1_define3_d_wake_process.html',1,'Kratos']]],
  ['defineembeddedwakeprocess_39281',['DefineEmbeddedWakeProcess',['../df/d56/classdefine__embedded__wake__process__2d_1_1_define_embedded_wake_process.html',1,'define_embedded_wake_process_2d.DefineEmbeddedWakeProcess'],['../de/dd9/class_kratos_1_1_define_embedded_wake_process.html',1,'Kratos::DefineEmbeddedWakeProcess']]],
  ['definewakeprocess_39282',['DefineWakeProcess',['../d6/da1/classdefine__wake__process_1_1_define_wake_process.html',1,'define_wake_process']]],
  ['definewakeprocess2d_39283',['DefineWakeProcess2D',['../d2/d7a/classdefine__wake__process__2d_1_1_define_wake_process2_d.html',1,'define_wake_process_2d']]],
  ['definewakeprocess3d_39284',['DefineWakeProcess3D',['../dd/dc0/classdefine__wake__process__3d_1_1_define_wake_process3_d.html',1,'define_wake_process_3d']]],
  ['deflatedcgsolver_39285',['DeflatedCGSolver',['../d5/d31/class_kratos_1_1_deflated_c_g_solver.html',1,'Kratos']]],
  ['deflationutils_39286',['DeflationUtils',['../d0/dbf/class_kratos_1_1_deflation_utils.html',1,'Kratos']]],
  ['deletemodelpartsmodeler_39287',['DeleteModelPartsModeler',['../d1/db7/classmodelers_1_1delete__model__parts__modeler_1_1_delete_model_parts_modeler.html',1,'modelers::delete_model_parts_modeler']]],
  ['deleteoldh5files_39288',['DeleteOldH5Files',['../d3/d15/classcore_1_1operations_1_1system_1_1_delete_old_h5_files.html',1,'core::operations::system']]],
  ['deltatimeparameters_39289',['DeltaTimeParameters',['../d2/de4/struct_kratos_1_1_explicit_central_differences_scheme_1_1_delta_time_parameters.html',1,'Kratos::ExplicitCentralDifferencesScheme&lt; TSparseSpace, TDenseSpace &gt;::DeltaTimeParameters'],['../d7/d98/struct_kratos_1_1_explicit_hamilton_scheme_1_1_delta_time_parameters.html',1,'Kratos::ExplicitHamiltonScheme&lt; TSparseSpace, TDenseSpace &gt;::DeltaTimeParameters'],['../d2/ddb/struct_kratos_1_1_explicit_multi_stage_kim_scheme_1_1_delta_time_parameters.html',1,'Kratos::ExplicitMultiStageKimScheme&lt; TSparseSpace, TDenseSpace &gt;::DeltaTimeParameters']]],
  ['dem_5fcompound_5fconstitutive_5flaw_39290',['DEM_compound_constitutive_law',['../da/d24/class_kratos_1_1_d_e_m__compound__constitutive__law.html',1,'Kratos']]],
  ['dem_5fcompound_5fconstitutive_5flaw_5ffor_5fpbm_39291',['DEM_compound_constitutive_law_for_PBM',['../d5/d16/class_kratos_1_1_d_e_m__compound__constitutive__law__for___p_b_m.html',1,'Kratos']]],
  ['dem_5fd_5fbentonite_5fcolloid_39292',['DEM_D_Bentonite_Colloid',['../d3/db4/class_kratos_1_1_d_e_m___d___bentonite___colloid.html',1,'Kratos']]],
  ['dem_5fd_5fconical_5fdamage_39293',['DEM_D_Conical_damage',['../dc/d9e/class_kratos_1_1_d_e_m___d___conical__damage.html',1,'Kratos']]],
  ['dem_5fd_5fdmt_5fcohesive_5flaw_39294',['DEM_D_DMT_Cohesive_Law',['../d4/da6/class_kratos_1_1_d_e_m___d___d_m_t___cohesive___law.html',1,'Kratos']]],
  ['dem_5fd_5fhertz_5fconfined_39295',['DEM_D_Hertz_confined',['../d9/d4e/class_kratos_1_1_d_e_m___d___hertz__confined.html',1,'Kratos']]],
  ['dem_5fd_5fhertz_5fviscous_5fcoulomb_39296',['DEM_D_Hertz_viscous_Coulomb',['../df/de3/class_kratos_1_1_d_e_m___d___hertz__viscous___coulomb.html',1,'Kratos']]],
  ['dem_5fd_5fhertz_5fviscous_5fcoulomb2d_39297',['DEM_D_Hertz_viscous_Coulomb2D',['../de/d52/class_kratos_1_1_d_e_m___d___hertz__viscous___coulomb2_d.html',1,'Kratos']]],
  ['dem_5fd_5fhertz_5fviscous_5fcoulomb_5fnestle_39298',['DEM_D_Hertz_viscous_Coulomb_Nestle',['../d8/d3e/class_kratos_1_1_d_e_m___d___hertz__viscous___coulomb___nestle.html',1,'Kratos']]],
  ['dem_5fd_5fjkr_5fcohesive_5flaw_39299',['DEM_D_JKR_Cohesive_Law',['../de/dc0/class_kratos_1_1_d_e_m___d___j_k_r___cohesive___law.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fclassic_39300',['DEM_D_Linear_classic',['../d9/d9a/class_kratos_1_1_d_e_m___d___linear__classic.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fconfined_39301',['DEM_D_Linear_confined',['../d4/dde/class_kratos_1_1_d_e_m___d___linear__confined.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fcustom_5fconstants_39302',['DEM_D_Linear_Custom_Constants',['../dd/d2b/class_kratos_1_1_d_e_m___d___linear___custom___constants.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fhighstiffness_39303',['DEM_D_Linear_HighStiffness',['../d9/db6/class_kratos_1_1_d_e_m___d___linear___high_stiffness.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fhighstiffness_5f2d_39304',['DEM_D_Linear_HighStiffness_2D',['../d5/d5d/class_kratos_1_1_d_e_m___d___linear___high_stiffness__2_d.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fviscous_5fcoulomb_39305',['DEM_D_Linear_viscous_Coulomb',['../d6/d53/class_kratos_1_1_d_e_m___d___linear__viscous___coulomb.html',1,'Kratos']]],
  ['dem_5fd_5flinear_5fviscous_5fcoulomb2d_39306',['DEM_D_Linear_viscous_Coulomb2D',['../d6/de2/class_kratos_1_1_d_e_m___d___linear__viscous___coulomb2_d.html',1,'Kratos']]],
  ['dem_5fd_5fquadratic_39307',['DEM_D_Quadratic',['../d3/d7a/class_kratos_1_1_d_e_m___d___quadratic.html',1,'Kratos']]],
  ['dem_5fd_5fstress_5fdependent_5fcohesive_39308',['DEM_D_Stress_Dependent_Cohesive',['../da/df2/class_kratos_1_1_d_e_m___d___stress___dependent___cohesive.html',1,'Kratos']]],
  ['dem_5fd_5fvoid_39309',['DEM_D_void',['../d0/d05/class_kratos_1_1_d_e_m___d__void.html',1,'Kratos']]],
  ['dem_5fdempack_39310',['DEM_Dempack',['../d1/d5a/class_kratos_1_1_d_e_m___dempack.html',1,'Kratos']]],
  ['dem_5fdempack2d_39311',['DEM_Dempack2D',['../d1/dc8/class_kratos_1_1_d_e_m___dempack2_d.html',1,'Kratos']]],
  ['dem_5fdempack2d_5fdev_39312',['DEM_Dempack2D_dev',['../d8/dc2/class_kratos_1_1_d_e_m___dempack2_d__dev.html',1,'Kratos']]],
  ['dem_5fdempack_5fdev_39313',['DEM_Dempack_dev',['../d2/d18/class_kratos_1_1_d_e_m___dempack__dev.html',1,'Kratos']]],
  ['dem_5fdempack_5ftorque_39314',['DEM_Dempack_torque',['../d3/d8c/class_kratos_1_1_d_e_m___dempack__torque.html',1,'Kratos']]],
  ['dem_5fexponentialhc_39315',['DEM_ExponentialHC',['../d2/d68/class_kratos_1_1_d_e_m___exponential_h_c.html',1,'Kratos']]],
  ['dem_5ffem_5fsearch_39316',['DEM_FEM_Search',['../d3/ddb/class_kratos_1_1_d_e_m___f_e_m___search.html',1,'Kratos']]],
  ['dem_5ffor_5fcoupling_5fsolution_39317',['DEM_for_coupling_Solution',['../de/d61/class_main_d_e_m__for__coupling_1_1_d_e_m__for__coupling___solution.html',1,'MainDEM_for_coupling']]],
  ['dem_5fforce_5fbased_5finlet_39318',['DEM_Force_Based_Inlet',['../d0/d49/class_kratos_1_1_d_e_m___force___based___inlet.html',1,'Kratos']]],
  ['dem_5finlet_39319',['DEM_Inlet',['../de/d2f/class_kratos_1_1_d_e_m___inlet.html',1,'Kratos']]],
  ['dem_5finlet_5fprocess_39320',['DEM_Inlet_Process',['../d5/d22/class_d_e_m__inlet__process_1_1_d_e_m___inlet___process.html',1,'DEM_inlet_process']]],
  ['dem_5fkdem_39321',['DEM_KDEM',['../da/de4/class_kratos_1_1_d_e_m___k_d_e_m.html',1,'Kratos']]],
  ['dem_5fkdem2d_39322',['DEM_KDEM2D',['../dc/d05/class_kratos_1_1_d_e_m___k_d_e_m2_d.html',1,'Kratos']]],
  ['dem_5fkdem_5fcamclay_39323',['DEM_KDEM_CamClay',['../dd/df4/class_kratos_1_1_d_e_m___k_d_e_m___cam_clay.html',1,'Kratos']]],
  ['dem_5fkdem_5ffissured_5frock_5fcl_39324',['DEM_KDEM_Fissured_Rock_CL',['../d9/df1/class_kratos_1_1_d_e_m___k_d_e_m___fissured___rock___c_l.html',1,'Kratos']]],
  ['dem_5fkdem_5fmohr_5fcoulomb_39325',['DEM_KDEM_Mohr_Coulomb',['../d6/d54/class_kratos_1_1_d_e_m___k_d_e_m___mohr___coulomb.html',1,'Kratos']]],
  ['dem_5fkdem_5frankine_39326',['DEM_KDEM_Rankine',['../d5/da1/class_kratos_1_1_d_e_m___k_d_e_m___rankine.html',1,'Kratos']]],
  ['dem_5fkdem_5fsoft_5ftorque_39327',['DEM_KDEM_soft_torque',['../dc/d56/class_kratos_1_1_d_e_m___k_d_e_m__soft__torque.html',1,'Kratos']]],
  ['dem_5fkdem_5fsoft_5ftorque_5fwith_5fnoise_39328',['DEM_KDEM_soft_torque_with_noise',['../d6/d61/class_kratos_1_1_d_e_m___k_d_e_m__soft__torque__with__noise.html',1,'Kratos']]],
  ['dem_5fkdem_5fwith_5fdamage_39329',['DEM_KDEM_with_damage',['../d6/dc8/class_kratos_1_1_d_e_m___k_d_e_m__with__damage.html',1,'Kratos']]],
  ['dem_5fkdem_5fwith_5fdamage_5fparallel_5fbond_39330',['DEM_KDEM_with_damage_parallel_bond',['../db/d54/class_kratos_1_1_d_e_m___k_d_e_m__with__damage__parallel__bond.html',1,'Kratos']]],
  ['dem_5fkdem_5fwith_5fdamage_5fparallel_5fbond_5f2d_39331',['DEM_KDEM_with_damage_parallel_bond_2D',['../d3/d00/class_kratos_1_1_d_e_m___k_d_e_m__with__damage__parallel__bond__2_d.html',1,'Kratos']]],
  ['dem_5fkdem_5fwith_5fdamage_5fparallel_5fbond_5fcapped_39332',['DEM_KDEM_with_damage_parallel_bond_capped',['../de/d4b/class_kratos_1_1_d_e_m___k_d_e_m__with__damage__parallel__bond__capped.html',1,'Kratos']]],
  ['dem_5fkdem_5fwith_5fdamage_5fparallel_5fbond_5fhertz_39333',['DEM_KDEM_with_damage_parallel_bond_Hertz',['../da/d4e/class_kratos_1_1_d_e_m___k_d_e_m__with__damage__parallel__bond___hertz.html',1,'Kratos']]],
  ['dem_5fkdem_5fwith_5fdamage_5fparallel_5fbond_5fhertz_5f2d_39334',['DEM_KDEM_with_damage_parallel_bond_Hertz_2D',['../d4/d5a/class_kratos_1_1_d_e_m___k_d_e_m__with__damage__parallel__bond___hertz__2_d.html',1,'Kratos']]],
  ['dem_5fkdemfabric_39335',['DEM_KDEMFabric',['../d7/d0b/class_kratos_1_1_d_e_m___k_d_e_m_fabric.html',1,'Kratos']]],
  ['dem_5fkdemfabric2d_39336',['DEM_KDEMFabric2D',['../d2/d78/class_kratos_1_1_d_e_m___k_d_e_m_fabric2_d.html',1,'Kratos']]],
  ['dem_5fparallel_5fbond_39337',['DEM_parallel_bond',['../d0/d7f/class_kratos_1_1_d_e_m__parallel__bond.html',1,'Kratos']]],
  ['dem_5fparallel_5fbond_5fbilinear_5fdamage_39338',['DEM_parallel_bond_bilinear_damage',['../d4/d5c/class_kratos_1_1_d_e_m__parallel__bond__bilinear__damage.html',1,'Kratos']]],
  ['dem_5fparallel_5fbond_5fbilinear_5fdamage_5fmixed_39339',['DEM_parallel_bond_bilinear_damage_mixed',['../d1/d86/class_kratos_1_1_d_e_m__parallel__bond__bilinear__damage__mixed.html',1,'Kratos']]],
  ['dem_5fparallel_5fbond_5ffor_5fmembrane_39340',['DEM_parallel_bond_for_membrane',['../db/dd2/class_kratos_1_1_d_e_m__parallel__bond__for__membrane.html',1,'Kratos']]],
  ['dem_5fsmooth_5fjoint_39341',['DEM_smooth_joint',['../d7/de1/class_kratos_1_1_d_e_m__smooth__joint.html',1,'Kratos']]],
  ['demanalysisstage_39342',['DEMAnalysisStage',['../dd/d91/class_d_e_m__analysis__stage_1_1_d_e_m_analysis_stage.html',1,'DEM_analysis_stage']]],
  ['demanalysisstagewithflush_39343',['DEMAnalysisStageWithFlush',['../d2/da8/class_kratos_d_e_m_analysis_1_1_d_e_m_analysis_stage_with_flush.html',1,'KratosDEMAnalysis.DEMAnalysisStageWithFlush'],['../dc/d42/class_main_kratos_thermal_d_e_m_analysis_1_1_d_e_m_analysis_stage_with_flush.html',1,'MainKratosThermalDEMAnalysis.DEMAnalysisStageWithFlush']]],
  ['dembeamconstitutivelaw_39344',['DEMBeamConstitutiveLaw',['../df/d5a/class_kratos_1_1_d_e_m_beam_constitutive_law.html',1,'Kratos']]],
  ['dembenchmarksanalysisstage_39345',['DEMBenchmarksAnalysisStage',['../d3/d15/class_d_e_m__benchmarks__analysis_1_1_d_e_m_benchmarks_analysis_stage.html',1,'DEM_benchmarks_analysis']]],
  ['demcontact_39346',['DemContact',['../d4/d5c/class_kratos_1_1_dem_contact.html',1,'Kratos']]],
  ['demcontinuumconstitutivelaw_39347',['DEMContinuumConstitutiveLaw',['../da/df9/class_kratos_1_1_d_e_m_continuum_constitutive_law.html',1,'Kratos']]],
  ['demcoupledfluiddynamicsanalysis_39348',['DEMCoupledFluidDynamicsAnalysis',['../dd/d98/class_d_e_m__coupled__fluid__dynamics__analysis_1_1_d_e_m_coupled_fluid_dynamics_analysis.html',1,'DEM_coupled_fluid_dynamics_analysis']]],
  ['demcoupledpfemfluiddynamicsanalysis_39349',['DEMCoupledPFEMFluidDynamicsAnalysis',['../dd/d5b/class_d_e_m__coupled__pfem__fluid__dynamics__analysis_1_1_d_e_m_coupled_p_f_e_m_fluid_dynamics_analysis.html',1,'DEM_coupled_pfem_fluid_dynamics_analysis']]],
  ['demdiscontinuumconstitutivelaw_39350',['DEMDiscontinuumConstitutiveLaw',['../d5/dcb/class_kratos_1_1_d_e_m_discontinuum_constitutive_law.html',1,'Kratos']]],
  ['demenergycalculator_39351',['DEMEnergyCalculator',['../d0/def/class_d_e_m__procedures_1_1_d_e_m_energy_calculator.html',1,'DEM_procedures.DEMEnergyCalculator'],['../d4/d42/class_d_e_m__procedures__mpi_1_1_d_e_m_energy_calculator.html',1,'DEM_procedures_mpi.DEMEnergyCalculator']]],
  ['demfemprocedures_39352',['DEMFEMProcedures',['../d6/d8b/class_d_e_m__procedures_1_1_d_e_m_f_e_m_procedures.html',1,'DEM_procedures.DEMFEMProcedures'],['../d4/dc3/class_d_e_m__procedures__mpi_1_1_d_e_m_f_e_m_procedures.html',1,'DEM_procedures_mpi.DEMFEMProcedures']]],
  ['demfemutilities_39353',['DEMFEMUtilities',['../d3/d38/class_kratos_1_1_d_e_m_f_e_m_utilities.html',1,'Kratos']]],
  ['demflags_39354',['DEMFlags',['../d0/d83/class_kratos_1_1_d_e_m_flags.html',1,'Kratos']]],
  ['demintegrationscheme_39355',['DEMIntegrationScheme',['../db/dc1/class_kratos_1_1_d_e_m_integration_scheme.html',1,'Kratos']]],
  ['demio_39356',['DEMIo',['../dd/db9/class_d_e_m__procedures_1_1_d_e_m_io.html',1,'DEM_procedures.DEMIo'],['../d6/d8f/class_d_e_m__procedures__mpi_1_1_d_e_m_io.html',1,'DEM_procedures_mpi.DEMIo'],['../d3/dc4/class_d_e_m__procedures__mpi__no__partitions_1_1_d_e_m_io.html',1,'DEM_procedures_mpi_no_partitions.DEMIo']]],
  ['demporomechanicscouplingsolver_39357',['DemPoroMechanicsCouplingSolver',['../dc/d52/classdem__poromechanics__coupling__analysis__stage_1_1_dem_poro_mechanics_coupling_solver.html',1,'dem_poromechanics_coupling_analysis_stage']]],
  ['demrestartutility_39358',['DEMRestartUtility',['../d8/d41/class_d_e_m__restart__utility_1_1_d_e_m_restart_utility.html',1,'DEM_restart_utility']]],
  ['demrollingfrictionmodel_39359',['DEMRollingFrictionModel',['../d1/d4a/class_kratos_1_1_d_e_m_rolling_friction_model.html',1,'Kratos']]],
  ['demrollingfrictionmodelbounded_39360',['DEMRollingFrictionModelBounded',['../d0/d86/class_kratos_1_1_d_e_m_rolling_friction_model_bounded.html',1,'Kratos']]],
  ['demrollingfrictionmodelconstanttorque_39361',['DEMRollingFrictionModelConstantTorque',['../d0/d18/class_kratos_1_1_d_e_m_rolling_friction_model_constant_torque.html',1,'Kratos']]],
  ['demrollingfrictionmodelviscoustorque_39362',['DEMRollingFrictionModelViscousTorque',['../d1/dce/class_kratos_1_1_d_e_m_rolling_friction_model_viscous_torque.html',1,'Kratos']]],
  ['demsaverestartprocess_39363',['DEMSaveRestartProcess',['../d2/d21/class_d_e_m__save__restart__process_1_1_d_e_m_save_restart_process.html',1,'DEM_save_restart_process']]],
  ['demsearch_39364',['DEMSearch',['../db/da5/class_kratos_1_1_d_e_m_search.html',1,'Kratos']]],
  ['demsearch_3c_20omp_5fdemsearch_20_3e_39365',['DEMSearch&lt; OMP_DEMSearch &gt;',['../db/da5/class_kratos_1_1_d_e_m_search.html',1,'Kratos']]],
  ['demsearchutilities_39366',['DemSearchUtilities',['../df/de0/class_kratos_1_1_dem_search_utilities.html',1,'Kratos']]],
  ['demstructurescouplingflags_39367',['DemStructuresCouplingFlags',['../d0/d3c/class_kratos_1_1_dem_structures_coupling_flags.html',1,'Kratos']]],
  ['demstructurescouplinggidoutput_39368',['DemStructuresCouplingGiDOutput',['../da/dfb/classdem__structures__coupling__gid__output_1_1_dem_structures_coupling_gi_d_output.html',1,'dem_structures_coupling_gid_output']]],
  ['demstructurescouplingutilities_39369',['DemStructuresCouplingUtilities',['../dc/d25/class_kratos_1_1_dem_structures_coupling_utilities.html',1,'Kratos']]],
  ['demthermalflags_39370',['DEMThermalFlags',['../d3/d9f/class_kratos_1_1_d_e_m_thermal_flags.html',1,'Kratos']]],
  ['demwall_39371',['DEMWall',['../d7/d8a/class_kratos_1_1_d_e_m_wall.html',1,'Kratos']]],
  ['demwrapper_39372',['DEMWrapper',['../dc/d13/classsolver__wrappers_1_1kratos_1_1dem__wrapper_1_1_d_e_m_wrapper.html',1,'solver_wrappers::kratos::dem_wrapper']]],
  ['denseeigenvaluesolver_39373',['DenseEigenvalueSolver',['../d1/d60/class_kratos_1_1_dense_eigenvalue_solver.html',1,'Kratos']]],
  ['densehouseholderqrdecomposition_39374',['DenseHouseholderQRDecomposition',['../d4/d05/class_kratos_1_1_dense_householder_q_r_decomposition.html',1,'Kratos']]],
  ['denselinearsolverfactory_39375',['DenseLinearSolverFactory',['../d0/da5/class_kratos_1_1_dense_linear_solver_factory.html',1,'Kratos']]],
  ['denseqrdecomposition_39376',['DenseQRDecomposition',['../db/d82/class_kratos_1_1_dense_q_r_decomposition.html',1,'Kratos']]],
  ['denseqrdecomposition_3c_20tdensespace_20_3e_39377',['DenseQRDecomposition&lt; TDenseSpace &gt;',['../db/d82/class_kratos_1_1_dense_q_r_decomposition.html',1,'Kratos']]],
  ['densesingularvaluedecomposition_39378',['DenseSingularValueDecomposition',['../d7/df0/class_kratos_1_1_dense_singular_value_decomposition.html',1,'Kratos']]],
  ['densesingularvaluedecomposition_3c_20tdensespace_20_3e_39379',['DenseSingularValueDecomposition&lt; TDenseSpace &gt;',['../d7/df0/class_kratos_1_1_dense_singular_value_decomposition.html',1,'Kratos']]],
  ['densityfunction_39380',['DensityFunction',['../d1/dcb/class_kratos_1_1_density_function.html',1,'Kratos']]],
  ['densityfunctionnormal_39381',['DensityFunctionNormal',['../de/db8/class_kratos_1_1_density_function_normal.html',1,'Kratos']]],
  ['densityfunctionpolynomial_39382',['DensityFunctionPolynomial',['../db/d85/class_kratos_1_1_density_function_polynomial.html',1,'Kratos']]],
  ['deprecationmanager_39383',['DeprecationManager',['../d1/d8b/classdeprecation__management_1_1_deprecation_manager.html',1,'deprecation_management']]],
  ['depthintegrationinputprocess_39384',['DepthIntegrationInputProcess',['../dd/dfe/classdepth__integration__input__process_1_1_depth_integration_input_process.html',1,'depth_integration_input_process']]],
  ['depthintegrationoutputprocess_39385',['DepthIntegrationOutputProcess',['../d9/d0f/classdepth__integration__output__process_1_1_depth_integration_output_process.html',1,'depth_integration_output_process']]],
  ['depthintegrationprocess_39386',['DepthIntegrationProcess',['../db/de0/class_kratos_1_1_depth_integration_process.html',1,'Kratos']]],
  ['derivative_39387',['Derivative',['../d7/ddd/class_kratos_1_1_q_s_v_m_s_derivative_utilities_1_1_derivative.html',1,'Kratos::QSVMSDerivativeUtilities']]],
  ['derivative_3c_200_20_3e_39388',['Derivative&lt; 0 &gt;',['../d7/ddd/class_kratos_1_1_q_s_v_m_s_derivative_utilities_1_1_derivative.html',1,'Kratos::QSVMSDerivativeUtilities']]],
  ['derivative_3c_20tcomponentindex_20_3e_39389',['Derivative&lt; TComponentIndex &gt;',['../d7/ddd/class_kratos_1_1_q_s_v_m_s_derivative_utilities_1_1_derivative.html',1,'Kratos::QSVMSDerivativeUtilities']]],
  ['derivativedata_39390',['DerivativeData',['../db/d37/class_kratos_1_1_derivative_data.html',1,'Kratos']]],
  ['derivativedata_3c_20tdim_2c_20tnumnodes_2c_20tnumnodes_20_3e_39391',['DerivativeData&lt; TDim, TNumNodes, TNumNodes &gt;',['../db/d37/class_kratos_1_1_derivative_data.html',1,'Kratos']]],
  ['derivativedatafrictional_39392',['DerivativeDataFrictional',['../d5/d9c/class_kratos_1_1_derivative_data_frictional.html',1,'Kratos']]],
  ['derivativerecovery_39393',['DerivativeRecovery',['../dc/db2/class_kratos_1_1_derivative_recovery.html',1,'Kratos']]],
  ['derivativerecoverymeshingtools_39394',['DerivativeRecoveryMeshingTools',['../d3/de3/class_kratos_1_1_derivative_recovery_meshing_tools.html',1,'Kratos']]],
  ['derivativerecoverystrategy_39395',['DerivativeRecoveryStrategy',['../da/def/classderivative__recovery_1_1derivative__recovery__strategy_1_1_derivative_recovery_strategy.html',1,'derivative_recovery::derivative_recovery_strategy']]],
  ['derivativesrecoverer_39396',['DerivativesRecoverer',['../d4/d08/classderivative__recovery_1_1recoverer_1_1_derivatives_recoverer.html',1,'derivative_recovery::recoverer']]],
  ['derivativesrecoveryprocess_39397',['DerivativesRecoveryProcess',['../d3/d42/classderivatives__recovery__process_1_1_derivatives_recovery_process.html',1,'derivatives_recovery_process']]],
  ['derivativesrecoveryutility_39398',['DerivativesRecoveryUtility',['../db/df0/class_kratos_1_1_derivatives_recovery_utility.html',1,'Kratos']]],
  ['derivativesutilities_39399',['DerivativesUtilities',['../d8/dfa/class_kratos_1_1_derivatives_utilities.html',1,'Kratos']]],
  ['designlogger_39400',['DesignLogger',['../d6/d7d/classloggers_1_1design__logger__base_1_1_design_logger.html',1,'loggers::design_logger_base']]],
  ['designloggergid_39401',['DesignLoggerGID',['../d5/d0a/classloggers_1_1design__logger__gid_1_1_design_logger_g_i_d.html',1,'loggers::design_logger_gid']]],
  ['designloggerunv_39402',['DesignLoggerUNV',['../d4/d23/classloggers_1_1design__logger__unv_1_1_design_logger_u_n_v.html',1,'loggers::design_logger_unv']]],
  ['designloggervtk_39403',['DesignLoggerVTK',['../de/d93/classloggers_1_1design__logger__vtk_1_1_design_logger_v_t_k.html',1,'loggers::design_logger_vtk']]],
  ['designvariableprojection_39404',['DesignVariableProjection',['../d8/d6a/classopt__projection_1_1_design_variable_projection.html',1,'opt_projection']]],
  ['det_39405',['det',['../d1/d12/interfacetensors_1_1det.html',1,'tensors']]],
  ['dev_39406',['dev',['../df/d52/interfacetensors_1_1dev.html',1,'tensors']]],
  ['deviatoricplaneshapeutilities_39407',['DeviatoricPlaneShapeUtilities',['../dc/df3/class_kratos_1_1_deviatoric_plane_shape_utilities.html',1,'Kratos']]],
  ['diagonal_39408',['Diagonal',['../df/d30/struct_kratos_1_1_brep_trimming_utilities_1_1_diagonal.html',1,'Kratos::BrepTrimmingUtilities']]],
  ['diagonalpreconditioner_39409',['DiagonalPreconditioner',['../da/df4/class_kratos_1_1_diagonal_preconditioner.html',1,'Kratos']]],
  ['differentdatadifferenceresidual_39410',['DifferentDataDifferenceResidual',['../d2/dc9/classconvergence__accelerators_1_1convergence__accelerator__wrapper_1_1_different_data_difference_residual.html',1,'convergence_accelerators::convergence_accelerator_wrapper']]],
  ['differentialoperator_39411',['DifferentialOperator',['../d3/dc9/classderivatives__recovery__process_1_1_derivatives_recovery_process_1_1_differential_operator.html',1,'derivatives_recovery_process::DerivativesRecoveryProcess']]],
  ['directconductionbobcomplete_39412',['DirectConductionBOBComplete',['../d5/d46/class_kratos_1_1_direct_conduction_b_o_b_complete.html',1,'Kratos']]],
  ['directconductionbobmodified_39413',['DirectConductionBOBModified',['../d0/d0b/class_kratos_1_1_direct_conduction_b_o_b_modified.html',1,'Kratos']]],
  ['directconductionbobsimple_39414',['DirectConductionBOBSimple',['../d7/df4/class_kratos_1_1_direct_conduction_b_o_b_simple.html',1,'Kratos']]],
  ['directconductioncollision_39415',['DirectConductionCollision',['../d6/d2c/class_kratos_1_1_direct_conduction_collision.html',1,'Kratos']]],
  ['directconductionmodel_39416',['DirectConductionModel',['../d0/daf/class_kratos_1_1_direct_conduction_model.html',1,'Kratos']]],
  ['directconductionpipe_39417',['DirectConductionPipe',['../dd/d00/class_kratos_1_1_direct_conduction_pipe.html',1,'Kratos']]],
  ['directcopytransfer_39418',['DirectCopyTransfer',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20array_5f1d_3c_20double_2c_20tdim_20_3e_20_3e_39419',['DirectCopyTransfer&lt; array_1d&lt; double, TDim &gt; &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20bool_20_3e_39420',['DirectCopyTransfer&lt; bool &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20double_20_3e_39421',['DirectCopyTransfer&lt; double &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20int_20_3e_39422',['DirectCopyTransfer&lt; int &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directcopytransfer_3c_20kratos_3a_3aflags_20_3e_39423',['DirectCopyTransfer&lt; Kratos::Flags &gt;',['../da/dae/struct_kratos_1_1_m_p_i_internals_1_1_direct_copy_transfer.html',1,'Kratos::MPIInternals']]],
  ['directiondampingutilities_39424',['DirectionDampingUtilities',['../d9/df2/class_kratos_1_1_direction_damping_utilities.html',1,'Kratos']]],
  ['directorsvariables_39425',['DirectorsVariables',['../d5/d76/struct_kratos_1_1_beam_element_1_1_directors_variables.html',1,'Kratos::BeamElement']]],
  ['directorutilities_39426',['DirectorUtilities',['../d4/d36/class_kratos_1_1_director_utilities.html',1,'Kratos']]],
  ['directsolver_39427',['DirectSolver',['../df/dc7/class_kratos_1_1_direct_solver.html',1,'Kratos']]],
  ['directsolver_3c_20tsparsespacetype_2c_20tdensespacetype_2c_20reorderer_3c_20tsparsespacetype_2c_20tdensespacetype_20_3e_20_3e_39428',['DirectSolver&lt; TSparseSpaceType, TDenseSpaceType, Reorderer&lt; TSparseSpaceType, TDenseSpaceType &gt; &gt;',['../df/dc7/class_kratos_1_1_direct_solver.html',1,'Kratos']]],
  ['directsolver_3c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3aglobal_2c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_2c_20reorderer_3c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3aglobal_2c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_20_3e_20_3e_39429',['DirectSolver&lt; typename SpaceType&lt; typename TSolverType::Scalar &gt;::Global, typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local, Reorderer&lt; typename SpaceType&lt; typename TSolverType::Scalar &gt;::Global, typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local &gt; &gt;',['../df/dc7/class_kratos_1_1_direct_solver.html',1,'Kratos']]],
  ['directsolver_3c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_2c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_2c_20reorderer_3c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_2c_20typename_20spacetype_3c_20typename_20tsolvertype_3a_3ascalar_20_3e_3a_3alocal_20_3e_20_3e_39430',['DirectSolver&lt; typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local, typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local, Reorderer&lt; typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local, typename SpaceType&lt; typename TSolverType::Scalar &gt;::Local &gt; &gt;',['../df/dc7/class_kratos_1_1_direct_solver.html',1,'Kratos']]],
  ['discontinuousshapefunctionsutilities_39431',['DiscontinuousShapeFunctionsUtilities',['../d7/d64/class_kratos_1_1_discontinuous_shape_functions_utilities.html',1,'Kratos']]],
  ['discontinuousshapefunctionsutilities_5f2d_39432',['DiscontinuousShapeFunctionsUtilities_2D',['../d4/d20/class_kratos_1_1_discontinuous_shape_functions_utilities__2_d.html',1,'Kratos']]],
  ['discreteelement_39433',['DiscreteElement',['../d0/ddc/class_kratos_1_1_discrete_element.html',1,'Kratos']]],
  ['discreteparticleconfigure_39434',['DiscreteParticleConfigure',['../dc/dff/class_kratos_1_1_discrete_particle_configure.html',1,'Kratos']]],
  ['discreterandomvariable_39435',['DiscreteRandomVariable',['../d5/dfa/class_kratos_1_1_discrete_random_variable.html',1,'Kratos']]],
  ['discretevalueresidualresponsefunction_39436',['DiscreteValueResidualResponseFunction',['../da/d9e/classresponses_1_1discrete__value__residual__response__function_1_1_discrete_value_residual_response_function.html',1,'responses::discrete_value_residual_response_function']]],
  ['displacementcontactcriteria_39437',['DisplacementContactCriteria',['../d1/df2/class_kratos_1_1_displacement_contact_criteria.html',1,'Kratos']]],
  ['displacementcontrolcondition_39438',['DisplacementControlCondition',['../d1/dc1/class_kratos_1_1_displacement_control_condition.html',1,'Kratos']]],
  ['displacementcriteria_39439',['DisplacementCriteria',['../d3/d7f/class_kratos_1_1_displacement_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultipliercontactcriteria_39440',['DisplacementLagrangeMultiplierContactCriteria',['../d9/d87/class_kratos_1_1_displacement_lagrange_multiplier_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultiplierfrictionalcontactcriteria_39441',['DisplacementLagrangeMultiplierFrictionalContactCriteria',['../d2/dd3/class_kratos_1_1_displacement_lagrange_multiplier_frictional_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultipliermixedcontactcriteria_39442',['DisplacementLagrangeMultiplierMixedContactCriteria',['../d0/d61/class_kratos_1_1_displacement_lagrange_multiplier_mixed_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultipliermixedfrictionalcontactcriteria_39443',['DisplacementLagrangeMultiplierMixedFrictionalContactCriteria',['../d3/d27/class_kratos_1_1_displacement_lagrange_multiplier_mixed_frictional_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultiplierresidualcontactcriteria_39444',['DisplacementLagrangeMultiplierResidualContactCriteria',['../d0/dbc/class_kratos_1_1_displacement_lagrange_multiplier_residual_contact_criteria.html',1,'Kratos']]],
  ['displacementlagrangemultiplierresidualfrictionalcontactcriteria_39445',['DisplacementLagrangeMultiplierResidualFrictionalContactCriteria',['../d8/df9/class_kratos_1_1_displacement_lagrange_multiplier_residual_frictional_contact_criteria.html',1,'Kratos']]],
  ['displacementresidualcontactcriteria_39446',['DisplacementResidualContactCriteria',['../d8/db2/class_kratos_1_1_displacement_residual_contact_criteria.html',1,'Kratos']]],
  ['displacementsensor_39447',['DisplacementSensor',['../d7/d20/class_kratos_1_1_displacement_sensor.html',1,'Kratos']]],
  ['displacementshiftedboundarycondition_39448',['DisplacementShiftedBoundaryCondition',['../d4/d1b/class_kratos_1_1_displacement_shifted_boundary_condition.html',1,'Kratos']]],
  ['dispnewtonianfluid3dlaw_39449',['DispNewtonianFluid3DLaw',['../d9/d82/class_kratos_1_1_disp_newtonian_fluid3_d_law.html',1,'Kratos']]],
  ['dispnewtonianfluidplanestrain2dlaw_39450',['DispNewtonianFluidPlaneStrain2DLaw',['../d2/da8/class_kratos_1_1_disp_newtonian_fluid_plane_strain2_d_law.html',1,'Kratos']]],
  ['distancecalculationelementsimplex_39451',['DistanceCalculationElementSimplex',['../d7/d6e/class_kratos_1_1_distance_calculation_element_simplex.html',1,'Kratos']]],
  ['distancecalculationelementsimplex_3c_202_20_3e_39452',['DistanceCalculationElementSimplex&lt; 2 &gt;',['../d7/d6e/class_kratos_1_1_distance_calculation_element_simplex.html',1,'Kratos']]],
  ['distancecalculationelementsimplex_3c_203_20_3e_39453',['DistanceCalculationElementSimplex&lt; 3 &gt;',['../d7/d6e/class_kratos_1_1_distance_calculation_element_simplex.html',1,'Kratos']]],
  ['distancecalculator_39454',['DistanceCalculator',['../d9/d3e/class_kratos_1_1_distance_calculator.html',1,'Kratos']]],
  ['distancecalculator1_39455',['DistanceCalculator1',['../d5/d36/class_kratos_1_1_distance_calculator1.html',1,'Kratos']]],
  ['distanceimportutility_39456',['DistanceImportUtility',['../d8/da8/classread__distance__from__file_1_1_distance_import_utility.html',1,'read_distance_from_file']]],
  ['distancematrix_39457',['DistanceMatrix',['../d7/d04/class_kratos_1_1_distance_matrix.html',1,'Kratos']]],
  ['distancemodificationprocess_39458',['DistanceModificationProcess',['../d9/dd2/class_kratos_1_1_distance_modification_process.html',1,'Kratos']]],
  ['distancesmoothingelement_39459',['DistanceSmoothingElement',['../db/dad/class_kratos_1_1_distance_smoothing_element.html',1,'Kratos']]],
  ['distancesmoothingprocess_39460',['DistanceSmoothingProcess',['../d9/d27/class_kratos_1_1_distance_smoothing_process.html',1,'Kratos']]],
  ['distancespatialcontainersconditionconfigure_39461',['DistanceSpatialContainersConditionConfigure',['../da/d90/class_kratos_1_1_distance_spatial_containers_condition_configure.html',1,'Kratos']]],
  ['distancespatialcontainersconfigure_39462',['DistanceSpatialContainersConfigure',['../d1/d71/class_kratos_1_1_distance_spatial_containers_configure.html',1,'Kratos::DistanceSpatialContainersConfigure'],['../d0/d1c/class_kratos_1_1_internals_1_1_distance_spatial_containers_configure.html',1,'Kratos::Internals::DistanceSpatialContainersConfigure']]],
  ['distributedamgclcsrspmmutilities_39463',['DistributedAmgclCSRSpMMUtilities',['../d4/dee/class_kratos_1_1_distributed_amgcl_c_s_r_sp_m_m_utilities.html',1,'Kratos']]],
  ['distributedcsrmatrix_39464',['DistributedCsrMatrix',['../d7/d64/class_kratos_1_1_distributed_csr_matrix.html',1,'Kratos']]],
  ['distributedfilter_39465',['DistributedFilter',['../d7/dc4/class_kratos_1_1_logger_message_1_1_distributed_filter.html',1,'Kratos::LoggerMessage']]],
  ['distributedgidoutputprocess_39466',['DistributedGiDOutputProcess',['../da/d6d/classdistributed__gid__output__process_1_1_distributed_gi_d_output_process.html',1,'distributed_gid_output_process']]],
  ['distributedimportmodelpartutility_39467',['DistributedImportModelPartUtility',['../d9/d32/classdistributed__import__model__part__utility_1_1_distributed_import_model_part_utility.html',1,'distributed_import_model_part_utility']]],
  ['distributedmodelpartinitializer_39468',['DistributedModelPartInitializer',['../dd/db3/class_kratos_1_1_distributed_model_part_initializer.html',1,'Kratos']]],
  ['distributednumbering_39469',['DistributedNumbering',['../da/da4/class_kratos_1_1_distributed_numbering.html',1,'Kratos']]],
  ['distributednumbering_3c_20indextype_20_3e_39470',['DistributedNumbering&lt; IndexType &gt;',['../da/da4/class_kratos_1_1_distributed_numbering.html',1,'Kratos']]],
  ['distributednumbering_3c_20std_3a_3asize_5ft_20_3e_39471',['DistributedNumbering&lt; std::size_t &gt;',['../da/da4/class_kratos_1_1_distributed_numbering.html',1,'Kratos']]],
  ['distributedrestartutility_39472',['DistributedRestartUtility',['../d4/d2d/classdistributed__restart__utility_1_1_distributed_restart_utility.html',1,'distributed_restart_utility']]],
  ['distributedsearchinformation_39473',['DistributedSearchInformation',['../da/d45/struct_kratos_1_1_distributed_search_information.html',1,'Kratos']]],
  ['distributedsparsegraph_39474',['DistributedSparseGraph',['../d2/dcc/class_kratos_1_1_distributed_sparse_graph.html',1,'Kratos']]],
  ['distributedsystemvector_39475',['DistributedSystemVector',['../df/dcf/class_kratos_1_1_distributed_system_vector.html',1,'Kratos']]],
  ['distributedvectorexporter_39476',['DistributedVectorExporter',['../db/d00/class_kratos_1_1_distributed_vector_exporter.html',1,'Kratos']]],
  ['distributedvectorexporter_3c_20std_3a_3asize_5ft_20_3e_39477',['DistributedVectorExporter&lt; std::size_t &gt;',['../db/d00/class_kratos_1_1_distributed_vector_exporter.html',1,'Kratos']]],
  ['distributedvectorimporter_39478',['DistributedVectorImporter',['../d4/d23/class_kratos_1_1_distributed_vector_importer.html',1,'Kratos']]],
  ['distributeloadonsurfaceprocess_39479',['DistributeLoadOnSurfaceProcess',['../d5/d20/class_kratos_1_1_distribute_load_on_surface_process.html',1,'Kratos']]],
  ['distributepointvaluesoperation_39480',['DistributePointValuesOperation',['../dc/d46/classcoupling__operations_1_1distribute__point__values_1_1_distribute_point_values_operation.html',1,'coupling_operations::distribute_point_values']]],
  ['divergencefreerefinementprocess_39481',['DivergenceFreeRefinementProcess',['../d4/de1/classdivergencefree__refinement__process_1_1_divergence_free_refinement_process.html',1,'divergencefree_refinement_process']]],
  ['dividegeometry_39482',['DivideGeometry',['../d6/de8/class_kratos_1_1_divide_geometry.html',1,'Kratos']]],
  ['dividetetrahedra3d4_39483',['DivideTetrahedra3D4',['../db/d9f/class_kratos_1_1_divide_tetrahedra3_d4.html',1,'Kratos']]],
  ['dividetetrahedra3d4_3c_20kratos_3a_3anode_20_3e_39484',['DivideTetrahedra3D4&lt; Kratos::Node &gt;',['../db/d9f/class_kratos_1_1_divide_tetrahedra3_d4.html',1,'Kratos']]],
  ['dividetriangle2d3_39485',['DivideTriangle2D3',['../da/df0/class_kratos_1_1_divide_triangle2_d3.html',1,'Kratos']]],
  ['dividetriangle2d3_3c_20kratos_3a_3anode_20_3e_39486',['DivideTriangle2D3&lt; Kratos::Node &gt;',['../da/df0/class_kratos_1_1_divide_triangle2_d3.html',1,'Kratos']]],
  ['dividetriangle3d3_39487',['DivideTriangle3D3',['../d9/d7d/class_kratos_1_1_divide_triangle3_d3.html',1,'Kratos']]],
  ['division_39488',['Division',['../dc/d2a/struct_kratos_1_1_binary_operations_1_1_division.html',1,'Kratos::BinaryOperations']]],
  ['dof_39489',['Dof',['../dc/d58/class_kratos_1_1_dof.html',1,'Kratos']]],
  ['dof_5fiterator_5fequal_39490',['dof_iterator_equal',['../dd/d0b/struct_kratos_1_1_block_builder_and_solver_1_1dof__iterator__equal.html',1,'Kratos::BlockBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::dof_iterator_equal'],['../d7/d15/struct_kratos_1_1_reduction_builder_and_solver_1_1dof__iterator__equal.html',1,'Kratos::ReductionBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::dof_iterator_equal']]],
  ['dof_5fiterator_5fhash_39491',['dof_iterator_hash',['../d1/d5d/struct_kratos_1_1_block_builder_and_solver_1_1dof__iterator__hash.html',1,'Kratos::BlockBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::dof_iterator_hash'],['../dd/d96/struct_kratos_1_1_reduction_builder_and_solver_1_1dof__iterator__hash.html',1,'Kratos::ReductionBuilderAndSolver&lt; TSparseSpace, TDenseSpace, TLinearSolver &gt;::dof_iterator_hash']]],
  ['dofdata_39492',['DofData',['../d6/ddd/struct_kratos_1_1_mesh_tying_mortar_condition_1_1_dof_data.html',1,'Kratos::MeshTyingMortarCondition']]],
  ['dofidaccess_39493',['DofIdAccess',['../df/d56/class_kratos_1_1_m_p_i_internals_1_1_dof_id_access.html',1,'Kratos::MPIInternals']]],
  ['dofpointerhasher_39494',['DofPointerHasher',['../df/dc1/struct_kratos_1_1_dof_pointer_hasher.html',1,'Kratos']]],
  ['dofscriterion_39495',['DofsCriterion',['../d8/d29/class_kratos_1_1_dofs_criterion.html',1,'Kratos']]],
  ['doftrait_39496',['DofTrait',['../dc/d06/struct_kratos_1_1_dof_trait.html',1,'Kratos']]],
  ['dofupdater_39497',['DofUpdater',['../d3/d3f/class_kratos_1_1_dof_updater.html',1,'Kratos']]],
  ['domain_39498',['Domain',['../d1/d20/classcore_1_1xdmf_1_1_domain.html',1,'core::xdmf']]],
  ['domainentitiesidcontainer_39499',['DomainEntitiesIdContainer',['../d5/d75/class_kratos_1_1_morton_divide_input_to_partitions_process_1_1_domain_entities_id_container.html',1,'Kratos::MortonDivideInputToPartitionsProcess']]],
  ['domainpanel2d_39500',['DomainPanel2D',['../de/dee/classprojection__utilities_1_1_domain_panel2_d.html',1,'projection_utilities']]],
  ['domainpanel3d_39501',['DomainPanel3D',['../d5/d16/classprojection__utilities_1_1_domain_panel3_d.html',1,'projection_utilities']]],
  ['domainsizeexpressionio_39502',['DomainSizeExpressionIO',['../d7/d20/class_kratos_1_1_domain_size_expression_i_o.html',1,'Kratos']]],
  ['domainutilities_39503',['DomainUtilities',['../dc/d27/classdomain__utilities_1_1_domain_utilities.html',1,'domain_utilities']]],
  ['dpgvms_39504',['DPGVMS',['../d7/d1a/class_kratos_1_1_d_p_g_v_m_s.html',1,'Kratos']]],
  ['dpgvms_3c_202_20_3e_39505',['DPGVMS&lt; 2 &gt;',['../d7/d1a/class_kratos_1_1_d_p_g_v_m_s.html',1,'Kratos']]],
  ['dpgvms_3c_203_20_3e_39506',['DPGVMS&lt; 3 &gt;',['../d7/d1a/class_kratos_1_1_d_p_g_v_m_s.html',1,'Kratos']]],
  ['dpstate_39507',['DPState',['../d3/dd5/struct_kratos_1_1_brep_trimming_utilities_1_1_d_p_state.html',1,'Kratos::BrepTrimmingUtilities']]],
  ['dragandmomentutilities_39508',['DragAndMomentUtilities',['../d6/d33/class_kratos_1_1_drag_and_moment_utilities.html',1,'Kratos']]],
  ['draglaw_39509',['DragLaw',['../db/dfa/class_kratos_1_1_drag_law.html',1,'Kratos']]],
  ['dragresponsefunction_39510',['DragResponseFunction',['../d3/de1/class_kratos_1_1_drag_response_function.html',1,'Kratos']]],
  ['dragutilities_39511',['DragUtilities',['../dd/de9/class_kratos_1_1_drag_utilities.html',1,'Kratos']]],
  ['drainedupwsmallstrainelement_39512',['DrainedUPwSmallStrainElement',['../db/d66/class_kratos_1_1_drained_u_pw_small_strain_element.html',1,'Kratos']]],
  ['drainedupwsmallstrainelement_3c_202_2c_203_20_3e_39513',['DrainedUPwSmallStrainElement&lt; 2, 3 &gt;',['../db/d66/class_kratos_1_1_drained_u_pw_small_strain_element.html',1,'Kratos']]],
  ['drainedupwsmallstrainelement_3c_202_2c_204_20_3e_39514',['DrainedUPwSmallStrainElement&lt; 2, 4 &gt;',['../db/d66/class_kratos_1_1_drained_u_pw_small_strain_element.html',1,'Kratos']]],
  ['drainedupwsmallstrainelement_3c_203_2c_204_20_3e_39515',['DrainedUPwSmallStrainElement&lt; 3, 4 &gt;',['../db/d66/class_kratos_1_1_drained_u_pw_small_strain_element.html',1,'Kratos']]],
  ['drainedupwsmallstrainelement_3c_203_2c_208_20_3e_39516',['DrainedUPwSmallStrainElement&lt; 3, 8 &gt;',['../db/d66/class_kratos_1_1_drained_u_pw_small_strain_element.html',1,'Kratos']]],
  ['dropletdynamicsanalysis_39517',['DropletDynamicsAnalysis',['../d3/d17/classdroplet__dynamics__analysis_1_1_droplet_dynamics_analysis.html',1,'droplet_dynamics_analysis']]],
  ['dropletdynamicselement_39518',['DropletDynamicsElement',['../db/da2/class_kratos_1_1_droplet_dynamics_element.html',1,'Kratos']]],
  ['dropletdynamicselement_3c_20kratos_3a_3atwofluidnavierstokesdata_3c_202_2c_203_20_3e_20_3e_39519',['DropletDynamicsElement&lt; Kratos::TwoFluidNavierStokesData&lt; 2, 3 &gt; &gt;',['../db/da2/class_kratos_1_1_droplet_dynamics_element.html',1,'Kratos']]],
  ['dropletdynamicselement_3c_20kratos_3a_3atwofluidnavierstokesdata_3c_203_2c_204_20_3e_20_3e_39520',['DropletDynamicsElement&lt; Kratos::TwoFluidNavierStokesData&lt; 3, 4 &gt; &gt;',['../db/da2/class_kratos_1_1_droplet_dynamics_element.html',1,'Kratos']]],
  ['dropletdynamicssolver_39521',['DropletDynamicsSolver',['../d3/d72/classdroplet__dynamics__solver_1_1_droplet_dynamics_solver.html',1,'droplet_dynamics_solver']]],
  ['druckerpragerplasticpotential_39522',['DruckerPragerPlasticPotential',['../d1/da5/class_kratos_1_1_drucker_prager_plastic_potential.html',1,'Kratos']]],
  ['druckerprageryieldsurface_39523',['DruckerPragerYieldSurface',['../d5/d72/class_kratos_1_1_drucker_prager_yield_surface.html',1,'Kratos']]],
  ['duallagrangemultiplieroperators_39524',['DualLagrangeMultiplierOperators',['../de/d18/class_kratos_1_1_dual_lagrange_multiplier_operators.html',1,'Kratos']]],
  ['duallagrangemultiplieroperators_3c_20tnumnodes_2c_20tnumnodes_20_3e_39525',['DualLagrangeMultiplierOperators&lt; TNumNodes, TNumNodes &gt;',['../de/d18/class_kratos_1_1_dual_lagrange_multiplier_operators.html',1,'Kratos']]],
  ['duallagrangemultiplieroperatorswithderivatives_39526',['DualLagrangeMultiplierOperatorsWithDerivatives',['../d2/de0/class_kratos_1_1_dual_lagrange_multiplier_operators_with_derivatives.html',1,'Kratos']]],
  ['dummyio_39527',['DummyIO',['../db/d0f/classsolver__wrappers_1_1dummy__io_1_1_dummy_i_o.html',1,'solver_wrappers::dummy_io']]],
  ['dummysolverwrapper_39528',['DummySolverWrapper',['../d9/d0b/classhelpers_1_1dummy__solver__wrapper_1_1_dummy_solver_wrapper.html',1,'helpers::dummy_solver_wrapper']]],
  ['duplicatemeshmodeler_39529',['DuplicateMeshModeler',['../de/dc7/class_kratos_1_1_duplicate_mesh_modeler.html',1,'Kratos']]],
  ['dvms_39530',['DVMS',['../dc/d6e/class_kratos_1_1_d_v_m_s.html',1,'Kratos']]],
  ['dvms_3c_20kratos_3a_3aqsvmsdata_3c_202_2c_203_20_3e_20_3e_39531',['DVMS&lt; Kratos::QSVMSData&lt; 2, 3 &gt; &gt;',['../dc/d6e/class_kratos_1_1_d_v_m_s.html',1,'Kratos']]],
  ['dvms_3c_20kratos_3a_3aqsvmsdata_3c_203_2c_204_20_3e_20_3e_39532',['DVMS&lt; Kratos::QSVMSData&lt; 3, 4 &gt; &gt;',['../dc/d6e/class_kratos_1_1_d_v_m_s.html',1,'Kratos']]],
  ['dvmsdemcoupled_39533',['DVMSDEMCoupled',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_202_2c_203_20_3e_20_3e_39534',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 2, 3 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_202_2c_204_20_3e_20_3e_39535',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 2, 4 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_202_2c_206_20_3e_20_3e_39536',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 2, 6 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_202_2c_209_20_3e_20_3e_39537',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 2, 9 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_203_2c_2027_20_3e_20_3e_39538',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 3, 27 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_203_2c_204_20_3e_20_3e_39539',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 3, 4 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dvmsdemcoupled_3c_20kratos_3a_3aqsvmsdemcoupleddata_3c_203_2c_208_20_3e_20_3e_39540',['DVMSDEMCoupled&lt; Kratos::QSVMSDEMCoupledData&lt; 3, 8 &gt; &gt;',['../d1/d68/class_kratos_1_1_d_v_m_s_d_e_m_coupled.html',1,'Kratos']]],
  ['dynamicarraytypetransfer_39541',['DynamicArrayTypeTransfer',['../d9/d1c/struct_kratos_1_1_m_p_i_internals_1_1_dynamic_array_type_transfer.html',1,'Kratos::MPIInternals']]],
  ['dynamicarraytypetransfer_3c_20matrix_20_3e_39542',['DynamicArrayTypeTransfer&lt; Matrix &gt;',['../d9/d1c/struct_kratos_1_1_m_p_i_internals_1_1_dynamic_array_type_transfer.html',1,'Kratos::MPIInternals']]],
  ['dynamicarraytypetransfer_3c_20vector_20_3e_39543',['DynamicArrayTypeTransfer&lt; Vector &gt;',['../d9/d1c/struct_kratos_1_1_m_p_i_internals_1_1_dynamic_array_type_transfer.html',1,'Kratos::MPIInternals']]],
  ['dynamicscheme_39544',['DynamicScheme',['../db/d8f/class_kratos_1_1_dynamic_scheme.html',1,'Kratos']]],
  ['dynamicsmagorinsky_39545',['DynamicSmagorinsky',['../d3/d3f/classdynamic__smagorinsky__utilities_1_1_dynamic_smagorinsky.html',1,'dynamic_smagorinsky_utilities']]],
  ['dynamicsmagorinskyutils_39546',['DynamicSmagorinskyUtils',['../d7/dd1/class_kratos_1_1_dynamic_smagorinsky_utils.html',1,'Kratos']]],
  ['dynamicvms_39547',['DynamicVMS',['../de/d8f/class_kratos_1_1_dynamic_v_m_s.html',1,'Kratos']]]
];
